### ISSUE TITLE
Feeds stopped updating

### ISSUE THREAD

**Issue by silverfoxy** [FreshRSS/FreshRSS#1020]
Feeds from all users from all sources stopped updating at a certain date, the actualize script says that it successfully updated and took 2 seconds to do so every day but the output doesn't change. Manually actualizing the feeds doesn't do anything either.

I also tried exporting the feeds, removing them and importing them again, now the dates are up to date but the content is the old cached ones not the ones that are present in the actual feeds.

It stopped updating in august, now the date says october but the news are still the ones from august.

I have the master branch version and the database is SQLite.

edit: If I add a url manually it shows up, up to date, but if I import my opml file, it shows news from august.

**Comment by Alkarex** [comment]
- Check that the installation is still fine `http://localhost/FreshRSS/p/i/?c=update&a=checkInstall` (you may have to adapt the URL)
- Please check the logs (HTTP, and FreshRSS logs in ./data/).
- Erase `./data/cache/*.spc`
- Erase `*.freshrss.lock` in your temp directory (e.g. `/tmp/` on Debian / Ubuntu)

**Comment by Pazns** [comment]
First time I used FreshRSS, it took me way too long to realize that setting "Do not automatically refresh more often than :" in the Archiving configuration screen to "Infinity" meant "Never update anymore."
Is this related to your case ?

**Comment by Alkarex** [comment]
Feel free to re-open if needed.

**Comment by lepazca** [comment]
I have exactly the same problem right now, If I delete the files that you mention early the feed gets updated once but the next time, same issue again.  regards

**Comment by Alkarex** [comment]
@leandropc Do you have anything in the FreshRSS, HTTP, and system logs?
Do you mean updating by cron or manually via the Web interface? Did you do a combination of the two?
Please check the permissions `ls -la` of your `./data/cache/` in particular.
Did you have some `/tmp/*.freshrss.lock` files?
If you have a cron update, please check the output of it 

Here is an example of my own `/etc/cron.d/FreshRSS` on Ubuntu, in which case one can check `/tmp/FreshRSS.log`:

```
7,37 * * * * www-data php -f /path/to/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
```

**Comment by spackmat** [comment]
In my fresh installation, some of my feeds only refresh, when I delete their cache files in `./data/cache`, while others work fine. `https://host/i/?c=update&a=checkInstall` has all green. I removed those feeds and then added them freshly without changing their settings, but still the same: they only get updated, when I delete the corresponding `.spc` file from the cache. The FreshRSS.log from the cronjob has nothing to say, it seems as it thinks it had nothing to to and looks like this:

    Starting feed actualization at 2018-10-10T09:50:01+02:00
    Actualize myuser...
    Done.
    Ending feed actualization at 2018-10-10T09:50:01+02:00
    Feed actualizations took 0 day(s), 0 hour(s),  0 minute(s) and 0 seconds for 1 users
    Results:
    myuser OK
    End.

One of the feeds not properly updating is https://www.shopblogger.de/blog/feeds/index.rss2

**Comment by Frenzie** [comment]
It might have something to do with that weird last-modified date 20+ years from now.

```
$ curl -I https://www.shopblogger.de/blog/feeds/index.rss2
HTTP/1.1 200 OK
Date: Wed, 10 Oct 2018 16:21:12 GMT
Server: Apache
Status: 200 OK
Set-Cookie: s9y_9ce05021fd953978f892c53f81ef8ee7=m6d8jnk361tdvj732sh80n0df1; path=/; secure
Expires: 0
Cache-Control: private, pre-check=0, post-check=0, max-age=0
Pragma: no-cache
Set-Cookie: s9y_9ce05021fd953978f892c53f81ef8ee7=7g31r5d2io2js4s9senv39ok77; path=/; secure
X-Session-Reinit: true
X-Serendipity-InterfaceLangSource: Content-Negotiation
X-Serendipity-InterfaceLang: de
Last-Modified: Sat, 16 Nov 2041 19:11:00 GMT
ETag: "Sat, 16 Nov 2041 19:11:00 GMT"
Content-Type: text/xml; charset=utf-8
```

**Comment by spackmat** [comment]
Thats plausible, I'll have a look at the other feeds that don't update. This one is my testcase, since it has several posts per day and thus I can reproduce the issue frequently.

So if this is the cause, how can I deal with that? Feedly and before Google Reader didn't mind and updated the feed well. This should be the behavior of a feed-aggregator IMHO. I sent a notice to the author auf shopblogger.de, but I need a forgiving aggregator since I cannot repair all weird feeds out there that work well with feedly et al.

So question is: Is there a setting that overrides the last-modified-header of broken feeds?

**Comment by Alkarex** [comment]
The problem is not so much that the date is in the future, but more that it does not seem to change. The ETag is wrong as well, also in its format.
The reason FreshRSS does not see any change is that the server returns a "304 Not Modified".

```
$ curl -H "If-Modified-Since: Sat, 16 Nov 2041 19:11:00 GMT" -H "If-None-Match: ""Sat, 16 Nov 2041 19:11:00 GMT""" -I "https://www.shopblogger.de/blog/feeds/index.rss2"
HTTP/1.0 304 Not Modified
Date: Thu, 11 Oct 2018 18:48:56 GMT
Server: Apache
Connection: close
ETag: "Sat, 16 Nov 2041 19:11:00 GMT"
Expires: 0
Cache-Control: private, pre-check=0, post-check=0, max-age=0
Set-Cookie: s9y_9ce05021fd953978f892c53f81ef8ee7=jdvve237rar24ood9tj8e4a0u6; path=/; secure
Set-Cookie: s9y_9ce05021fd953978f892c53f81ef8ee7=82qvqmg9ne16pgqoiajabqrds2; path=/; secure
```

The feed is thus not HTTP/1.1 compliant. This is really something the feed should fix. It is a behaviour that is negative for the rest of the Web (if we were to make a fix for them, it would make the situation worse for good feeds).

While waiting for this feed to be fixed, there is a number of options, such as:
1. Make a batch job that deletes the local cache of the problematic feeds
2. Make a small extension specific to those bad feeds, on the model of https://github.com/FreshRSS/FreshRSS/blob/dev/extensions/Tumblr-GDPR/extension.php to change the cURL parameters with something like that in the callback:

```php
$simplePie->set_curl_options(array(
		CURLOPT_HTTPHEADER => array(
			'if-modified-since: 0',
			'if-none-match: "0"',
		),
	));
```

3. Introduce a new feed option in FreshRSS, to disable local caching of specific feeds (like we do for feeds with bad SSL parameters)

**Comment by spackmat** [comment]
I moved back to Feedly for now as reliable feed-updates is important to me and I don't want to invest any hassle to find out, wich are the (rarely updated) feeds, that are not updating. In my first test, i saw three of them, but maybe there are more that didn't update within the short timespan of my testing. I simply don't know.

Nevertheless I like FreshRSS and a feed option to disable caching for those problematic feeds would be a crucial feature for me to use it. The extension-solution is a cool thing, but noting I would recommend other users that are not developers.

**Comment by Alkarex** [comment]
@spackmat I have made a little patch for you https://github.com/FreshRSS/FreshRSS/pull/2052 (will be in FreshRSS 1.12.0, coming soon). Needs a bit of testing before merging in the /dev branch.

I like Feedly and the role they play in maintaining a lively RSS ecosystem. They do not have the same ideology than FreshRSS though, by using a centralised model as opposed to a decentralised one like FreshRSS. In a centralised model, it is enough to have the single big instance to work, and one does not have to care as much about the scaling to thousands of instances.
In a decentralised model like FreshRSS, it is important to ensure that each instance is as much as possible a good net-citizen, in particular by minimizing their impact on the news sources, and this includes complying to HTTP caching standards.

I honestly believe that FreshRSS is quite robust at fetching feeds, and we spend quite some efforts to support various kinds of invalid inputs, as illustrated by our [dedicated issue category](https://github.com/FreshRSS/FreshRSS/issues?q=is%3Aissue+label%3A%22Feed+problem+%3Anewspaper_roll%3A%22+is%3Aclosed). However, it is not acceptable to negatively affect the vast majority of feeds just to support a single broken feed. For the health of the RSS ecosystem, it is also important (and much easier) to fix problems upstream than having to deal with a plethora of bugs in the readers. If Feedly had been less lenient, your broken feed might already have been fixed and would thus have worked in FreshRSS as well as in the many other RSS readers. So it is a balance...

**Comment by spackmat** [comment]
First: thanks for the patch, I try it out and observe over the next days.

I totally with you in all your points, with a bit of falling in love with what your philosophy behind FreshRSS is. This was the reason, I installed it in the first place although feedly works great for me since Google switched off their Reader. Your patch enables me to use FreshRSS even for those broken feeds. Because the nicest self-hosted reader is nothing worth, when it fails to update all my feeds.
