### ISSUE TITLE
Install script checks for php-dom vs php-xml

### ISSUE THREAD

**Issue by plietar** [FreshRSS/FreshRSS#1094]
Hi,
I've noticed an issue in the extension checks done by the install script :
If the `dom` extension is missing, the install script asks the user to install the `xml` extension.
If the `dom` extension is present but the `xml` is not, the install script happily proceeds, but retrieving feeds will fail as SimplePie requires it.

Both extensions are required by FreshRSS I believe, and should have their own check.

**Comment by Alkarex** [comment]
Thanks for the bug report. I thought the XML extension was always available, but indeed, it is possible to explicitly opt-out http://php.net/manual/xml.installation.php

If you have time, it would be great if you could make a pull request (otherwise, I will try to add a check before the next beta). See:
- https://github.com/FreshRSS/FreshRSS/blob/dev/app/install.php#L310
- http://simplepie.org/wiki/setup/requirements

**Comment by Alkarex** [comment]
Check added in https://github.com/FreshRSS/FreshRSS/pull/1097
