### ISSUE TITLE
Manual refresh not working (Global actualize)

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1168]
Hi, new user here.

I imported an opml file into FreshRSS and the feeds updated properly (there was an issue with the categories not populating, but I think that has been addressed in the dev version). But, whenever I click on the global actualize button, I get the following message:

> There is no feed to refresh…

But individually refreshing a feed works fine.

I have tried it with the following versions:
- 1.3.2-beta
- 1.3.3-dev

I am using Ubuntu 14.04.

**Comment by Alkarex** [comment]
Hello @notfoss 
It seems to work fine on my machine. Please note that there is a timer, preventing the feeds from being updated too often (see in archiving options). Maybe that is your issue?

Otherwise, please try to see if you have anything in your FreshRSS or Web server or MySQL logs.

It should not be necessary, but if the problem persist, you can also try to manually delete `/FreshRSS/data/cache/*.spc` and erase `*.freshrss.lock` in your temp directory (e.g. `/tmp/` on Debian / Ubuntu).

Could be related to https://github.com/FreshRSS/FreshRSS/issues/1020 which I was not able to reproduce.

**Comment by ghost** [comment]
Hi @Alkarex 

> Please note that there is a timer, preventing the feeds from being updated too often (see in archiving options). Maybe that is your issue?

Thanks, that did the trick! But from what I could understand, the text "Do not automatically refresh more often than" referred to automatic refreshing of the feeds. I didn't know that it had an effect on manual refreshing as well. Perhaps the text can be changed to better reflect the actual purpose.

Thanks!
