### ISSUE TITLE
Firefox security warnings

### ISSUE THREAD

**Issue by canyapan** [FreshRSS/FreshRSS#1173]
Hi,
I noticed following security warnings on "/p/i/" page.
- Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead.
- An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
- Content Security Policy: The page's settings blocked the loading of a resource at self ("default-src https://freshrss/").

FreshRSS v1.3.2-beta
FF v47.0.1 (latest)

**Comment by Alkarex** [comment]
Hello @canyapan 
Thanks for the feedback.
This looks all fine.
- We use both the new `child-src` and `frame-src` in order to support old browsers for a little period of time. `child-src` has only been added in Firefox 45 (March 2016).
- I do not know better alternatives for the `iframe` settings, if we want to support iframes for videos (e.g. YouTube) and comments (e.g. Slashdot). Furthermore, as far as I know, the security warning is only for iframes served from the same domain than where FreshRSS is hosted - and FreshRSS is not using iframes. We could make the warning disappear by removing the iframe security, which would make it less secure... 
- I would need a concrete example of the situation when you experience the CSP blocking of `self`. The current CSP rules should be fine. Have you changed your HTTP to HTTPS, or use a proxy?

**Comment by canyapan** [comment]
Hello @Alkarex,
I am not using proxy for the connection. Just redirecting http to https using vhost configurations.

```
server {
  listen 80;
  listen [::]:80;

  server_name freshrss;

  return 301 https://freshrss$request_uri;
}
```

Certificate used by TLS connection is a self signed certificate, which is added to trust store of local user.

**Comment by Alkarex** [comment]
Feel free to re-open if some elements are blocked, which should not be blocked, or vice versa.
