### ISSUE TITLE
Category filter

### ISSUE THREAD

**Issue by yapbreak** [FreshRSS/FreshRSS#1174]
Hi,
I did not find information on my issue in already written issues so, I open mine.
Back in the old days, I used RssLounge and it has a useful feature: each category has its own numbered priority, and when you read all your feed, you had two sliders to show only category between those sliders.
It was useful if, like me, you have one specific category (say NSFW), that I do not want to show at work but I want to read all the other categories. I try to "fake" it with filter, but I did not success to create a filter by removing a category or by showing multiple categories…

Is there any way to do that with the actual Freshrss? (I use version 1.3.2-beta)

Thank you
(and thank you for your software!)

**Comment by aledeg** [comment]
What you can do is remove the feed from that category from the main page. This way you wont see those articles when you browse it.
Unfortunatly, you will still see the content of that specific category if you click on it since it will be visible in the menu.
What you could do is have another user with the feeds from that category.

**Comment by yapbreak** [comment]
Oh, I forget that I could remove a feed from main page!
That would fit my need. Thank you.
