### ISSUE TITLE
Feed error don't know why

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1190]
Hello I'm trying to build a new bridge for RSSBridge but it does not appears to be valid. Is it possible to know why ?

http://bridge.prysme.net/?action=display&bridge=ArstechnicaBridge&format=AtomFormat

Thanks.

**Comment by Alkarex** [comment]
Checking with W3C Feed Validator is a good start (but it looks good there):
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fbridge.prysme.net%2F%3Faction%3Ddisplay%26bridge%3DArstechnicaBridge%26format%3DAtomFormat

Then, you can try to look at the FreshRSS logs (you can get more info by setting `'environment' => 'development'`, in `./data/config.php`).

In case of problem, it is a good idea to try to curl from your server:

``` sh
curl -v 'http://bridge.prysme.net/?action=display&bridge=ArstechnicaBridge&format=AtomFormat'
```

It works in my FreshRSS from my server, but takes 11.5s, so it is possible you hit a timeout (which is 15s since FreshRSS 1.3.2-beta, and was 10s before). You can change the default timeout in `./data/config.php`:

``` php
'timeout' => 20,
```

**Comment by ghost** [comment]
My bad, now it's working properly. I've made a pull request to add my ArsTechnica bridge to RSSBridge now.
Thanks

**Comment by Alkarex** [comment]
Just for the record, Ars Technica has an RSS feed http://feeds.arstechnica.com/arstechnica/index (truncated to the first 3 paragraphs, but PubSubHubbub enabled for push notifications)

**Comment by ghost** [comment]
Agreed, but I wanted to get the full content and remove the crap.
