### ISSUE TITLE
How to cron the feeds

### ISSUE THREAD

**Issue by sant527** [FreshRSS/FreshRSS#1426]
I have 30 feeds. Is it possible that each one of them keep updating every 25minutes. But not all at once. I mean every 4-5 min atleast two feed keep updating. So whole day i can keep updated with the feeds.

**Comment by Alkarex** [comment]
Hello,
In the configuration of each feed, you can specify a refresh rate.
So you can have a refresh cron set for instance at 15min and it will only update the feeds that need to be refreshed, based on the feed individual settings.
I would not recommend refreshing feeds more often than every ~15min otherwise you risk being banned by those Web sites (either by IP, or even worse, by user agent).
FreshRSS is also compatible with the push protocol PubSubHubbub, which will give you instant updates in FreshRSS when compatible Web sites are publishing a new article.
I hope this helps.

**Comment by sant527** [comment]
ok
