### ISSUE TITLE
FreshRSS on Cloudron

### ISSUE THREAD

**Issue by gramakri** [FreshRSS/FreshRSS#1432]
Hi,
Thanks for FreshRSS! The Cloudron community (@dswd) has contributed a FreshRSS app for Cloudron. You can try it out here - https://my-demo.cloudron.me (install FreshRSS from the App Store).

The code for the app itself is at https://git.cloudron.io/dswd/freshrss-app and also has selenium based tests at https://git.cloudron.io/dswd/freshrss-app/tree/master/test.

Let me know if you had any comments/suggestions. I will make a PR to add Cloudron as an installation method.

**Comment by Alkarex** [comment]
Hello @gramakri 
And thanks for this contribution 👍 

I have a few questions:
1. What happens when there is a new version of FreshRSS?
2. What was the problem that required this patch? https://git.cloudron.io/dswd/freshrss-app/blob/master/change-ttrss-file-path.patch Maybe we can address in FreshRSS itself
3. Did you see there is a CLI (command-line interface)? https://github.com/FreshRSS/FreshRSS/tree/master/cli Could you try to see whether it can be used instead of the manual settings of https://git.cloudron.io/dswd/freshrss-app/blob/master/start.sh
    * Let me know if any other CLI option could help
4. What would you need for Cloudron authentication? https://git.cloudron.io/dswd/freshrss-app/blob/master/POSTINSTALL.md

**Comment by dswd** [comment]
Hi @Alkarex, let me answer these questions as I did the packaging.

1) I am subscribed to Github releases for FreshRSS (via RSS) and I will hopefully be able to package new releases for Cloudron when they come out. I got a personal interest in packaging the new releases as I use FreshRSS on Cloudron for my daily feed reading.

2) The underlying problem of that patch was that Cloudron distinguishes between code and data in a way that makes code read-only. Since the api directory is clearly code I wanted to keep it in the read-only code directory. As the ttrss plugin wanted to write into that api folder a simple symlink approach is not enough as the folder itself needs to be writable. Therefore I went with the small patch that makes the plugin write its file to a writable location instead which in turn allows me to use a symlink in the api folder again. (I hope that was no too confusing)

3) Actually I saw it too late. I did not expect to find such a tool and I did not see it in the documentation (at least not in the english version). As far as I can see it could help me with setting up the initial config and db scheme but currently it does not seem to support overwriting the db settings on already installed instances. Such a feature would be useful to me, yes.

4) Cloudron auth integration would require LDAP support. There are also some other less common alternatives but I think LDAP should be used in this case. Also it would be nice if one could disable the whole update panel with a config option as Cloudron will handle updates on its own.

**Comment by Alkarex** [comment]
Thanks for the answers, @dswd.

1. and 4. Let me know whether you could think of an automated update system, which would not require a person to make an update on Cloudron side. In any case, I am pleased to hear you are an active user :-)
    * If not possible, please open an issue for an option disabling the update feature (which currently works eather by downloading a full new ZIP file, or by automatically running a `git pull` behind the scenes.
    * Reference to LDAP: https://github.com/FreshRSS/FreshRSS/issues/1053

2. Ok. Maybe we should move this extension in the FreshRSS core and avoid this problem. (Suggestion for @marienfressinaud )

3. You can already call several times `./cli/do-install.php`, which only updates `data/config.php`, but if you need an explicit API to update specific parameters without affecting the others, please open a new issue.

**Comment by dswd** [comment]
1) I think this would collide with the read-only code folders in Cloudron. Also Cloudron has the functionality of reverting to a previous backup including the code. So I guess distinct app versions will be the way to go. @gramakri what is you opinion on that?

2) My suggestion would be to have a special folder (e.g. `api/custom`) for custom apis that I could move to the writable data folder via symlinks like I already do. Maybe you could use .htaccess files with the rewrite module to give those files their old URL back.

3) Ok, I will have to investigate this script further.

**Comment by gramakri** [comment]
@Alkarex Cloudron relies on immutable containers for it's update strategy. At a high level, main advantages are that I can run multiple instances of app container for scaling up (otherwise, one might be updated and other's are not yet and we might have db schema incompat), updates can be delivered as a whole image (for example, I can even update php/nginx etc as required by the app), simpler backup strategy (code is not part of backup), some security advantages (code cannot be tampered by outsider) etc. And of course, our approach also makes it work for apps which don't have an auto-updater to start with.

1. So, it would be great if we can disable the auto-update (this is what we do for most of our apps where it is available).

2. For extensions, the existing apps we have usually have a configurable plugin/extension directory. Is that possible already in FreshRSS? (@dswd is a better person to tackle all these questions in any case since I didn't package the app myself).

Thanks again.

**Comment by dswd** [comment]
@gramakri FreshRSS extensions in general are handled properly. There is a writable extension folder and the official extensions are part of the code folder and symlinked to the writable folder. My issue is only with one specific extension that wants to write in a readonly code folder.
