### ISSUE TITLE
Mise à jour 1.6.3 non proposée

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#1488]
Hello.

Je suis en 1.6.2 mais le script ne me propose pas de mise à jour disponible.

Screenshot : 
![maj-frss](https://cloud.githubusercontent.com/assets/1558487/24788652/f71dcad0-1b6e-11e7-90d2-0c632fe9cd75.png)

**Comment by axel-dd** [comment]
same problem here

**Comment by Alkarex** [comment]
While waiting for an improved automatic update process https://github.com/FreshRSS/FreshRSS/issues/907 , automatic updates via ZIP archives require a manual refresh of the update server (ping @marienfressinaud ;-) )

Alternatively, if you install FreshRSS via git instead of ZIP, the automatic update will work. If not git, then manually unzipping the new version will work too.

Related issues:
* https://github.com/FreshRSS/FreshRSS/issues/861
* https://github.com/FreshRSS/FreshRSS/issues/1234
* https://github.com/FreshRSS/FreshRSS/issues/1235

**Comment by marienfressinaud** [comment]
Mmm, actually automatic update via ZIP archive is broken in FreshRSS itself :( The reason is the bug refactoring in https://github.com/FreshRSS/FreshRSS/commit/21e63595083d556bd4a6ff56c4ccaab5cd318dd4#diff-8909572edfc3021317cf2dc7ed59e628L114 and the `require(UPDATE_FILENAME);` is not available anymore line 196.

So to make it works, you'll need to update file `./app/Controllers/updateController.php` and move the `require` to the line 168.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1498

**Comment by Alwaysin** [comment]
Works great with the workaround provided by @marienfressinaud !

**Comment by axel-dd** [comment]
adding 
`require(UPDATE_FILENAME);`
to line 196 fixed it. Now I am at 1.9.3.

Thanks

**Comment by Vincent14** [comment]
I can confirm I just updated my FreshRSS following your instruction, it works fine! Ouf!

**Comment by Alkarex** [comment]
@marienfressinaud When you can find time to put the new version 1.7.0 on the update server, could you please confirm that it works?

**Comment by angristan** [comment]
What do we have to modify to update from 1.6.3 to 1.7.0 ?

**Comment by Alkarex** [comment]
@Angristan Sorry for the delay. Nothing special between those two versions. It depends on how you installed FreshRSS.
For instance, if you installed via git, see https://github.com/FreshRSS/FreshRSS/tree/master/cli#using-git

**Comment by marienfressinaud** [comment]
Sorry I missed your message @Alkarex, I'll update the server this evening

**Comment by marienfressinaud** [comment]
1.7.0 solves this update issue indeed, but unfortunately since the bug was still in 1.6.3, you'll have to do the same manipulation as describe above:

> […] the `require(UPDATE_FILENAME);` is not available anymore line 196. So to make it works, you'll need to update file `./app/Controllers/updateController.php` and move the `require` to the line 168.

**Comment by Alkarex** [comment]
@marienfressinaud If you can, it would be good if you could make a manual test to check that the current upgrade code in 1.7.0 will work when updating to the next version

**Comment by marienfressinaud** [comment]
I already did it :)

I opened a new (explicit) ticket to indicate the manipulation : https://github.com/FreshRSS/FreshRSS/issues/1577

**Comment by marienfressinaud** [comment]
Btw, version in `dev` branch should be `1.8.0-dev ` now

**Comment by Alkarex** [comment]
Yes :-)
