### ISSUE TITLE
MySQL high memory usage

### ISSUE THREAD

**Issue by psukys** [FreshRSS/FreshRSS#1514]
Hello,

when using MySQL database I have abnormally high memory usage (I am the sole user at the moment)

![FreshRSS archive](http://i.imgur.com/thVVRM1.png)

and in my machine the memory consumption is over 1GB

![Memory consumption](http://i.imgur.com/kZHKjOD.png)

Looking into the size of tables in the database, the sizes look normal.

![database table sizes](http://i.imgur.com/FdKnuz5.png)

I do not use the database for anything else. Tried with a fresh install for both mysql and freshrss, yet the memory consumption is still high (after some time). How can I reduce the memory consumption?

**Comment by Alkarex** [comment]
Hello,
I am not sure this ps size information is relevant. It does not reflect the amount of physical memory used.
This looks quite normal for MySQL, and is not much related to FreshRSS.
In any case, MySQL memory usage is controlled in MySQL settings https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html
You can also use the tool `mysqltuner` to get some tips.
Remember that a database engine is supposed to use as much memory as possible to be efficient.
You can also consider using SQLite instead of MySQL. For a small instance, performances would not be that different, and you will get a memory usage of 0 (except during FreshRSS queries).

**Comment by psukys** [comment]
@Alkarex thank you, I will try SQLite out!
