### ISSUE TITLE
Clicking horizontally outside article area closes the article

### ISSUE THREAD

**Issue by psukys** [FreshRSS/FreshRSS#1530]
A rather unexpected functionality, where pressing outside the article area closes the articles. An example of this area (marked in red):
![area that closes article](https://i.imgur.com/EsMBXLL.gif)

At least, personally, I find this functionality frustrating.
As I have a general idea how to fix this, I could as well work on fixing if it's decided on.

**Comment by Alwaysin** [comment]
I think it has been done on purpose, so that when you have a very long article, you can click this area to close it and don't have to scroll all the way back up. 
I use this feature but I have to admit that sometimes I close articles without wanting to (when I select text with the mouse first in this area). Could be a user option or could find a better approach to deal with this.

**Comment by Alkarex** [comment]
I do not have a strong feeling either way. Let's see if others have some input.

**Comment by aledeg** [comment]
I like the idea of having the option rather than deleting that behavior. I use it all the time while reading long articles instead of scrolling. But I understand that if you don't want that type of behavior, it can be frustrating.

**Comment by psukys** [comment]
True, in this case maybe adding a settings option would be a better approach overall

**Comment by Alwaysin** [comment]
If https://github.com/FreshRSS/FreshRSS/issues/1177 could be resolved at the same time, it would be so great :D

**Comment by GLLM** [comment]
Salut,

On my side, this 'Close when click on blank part' "feature" has always annoyed me :(
It'd live very well without it ! :)

Thanks

**Comment by Alkarex** [comment]
The discussion continues in https://github.com/FreshRSS/FreshRSS/pull/1539
