### ISSUE TITLE
[Feature request] JSON Feed

### ISSUE THREAD

**Issue by Epy** [FreshRSS/FreshRSS#1551]
Hello
I drop this here only for later, if someone wants to add this or I may try to do it by myself

A couple of devs is pushing a JSON Feed format to replace RSS/Atom ones based on XML:
https://jsonfeed.org/version/1

This feels like already a new format although we didn't already push XML to its limits but it's not so stupid: JSON is lighter and they thought of compatbility upwards

**Comment by aledeg** [comment]
I think it's doable when a lib to convert JSON feed to Atom is released. Or maybe included in SimplePie library. See https://github.com/simplepie/simplepie/issues/519 for more info on that.

**Comment by Frenzie** [comment]
I hope that won't lead to an increase of websites like this one: https://frerejones.com/blog

Without JS there's nothing there. With JS enabled it loads the blog content from https://frerejones.com/api/articles

Oh well, adding a converter to SimplePie and/or rss-bridge should be simple enough I guess.

> For most developers, JSON is *far* easier to read and write than XML. 

Nonsense. JSON's inability to quickly comment out a line makes it much harder to write than XML in spite of it otherwise being mostly easier. YAML or some such is much more straightforward imho.

**Comment by Alkarex** [comment]
I am in favour of supporting this format when it starts being used, but I otherwise do not think it helps to have yet another format. The current problems with RSS/Atom are not due to XML, quite the contrary. If the spec is very precise and very strict, then it might be OK in the long run; if not, then it will be yet another problematic format to support.

**Comment by Frenzie** [comment]
Atom's good; RSS 2 isn't problematic either. The wild days were in the early 2000s with the conflicting RSS standards, half a lifetime ago (for me). 

Incidentally, glancing at that page again I came across this beauty.

> `version` (required, string) is the URL of the version of the format the feed uses. This should appear at the very top, though we recognize that not all JSON generators allow for ordering.

There's a format where order is significant. It's not JSON. I think it starts with an X…

**Comment by Frenzie** [comment]
> I think you forgot about it stuck_out_tongue

Haha, indeed, except I was less diplomatic in the words I chose a few years ago than those I chose yesterday. I definitely don't see the point since at best it's just Atom in JSON, and most of their arguments read like a parody of trendy hackers.

Like this one:

> Developers may groan at picking up an XML parser, but decoding JSON is often just a single line of code.

That doesn't make a lick of sense. Reading junk like that is exactly why my opinion went from /shrug to negative three years ago, and the same applies today.

**Comment by edsu** [comment]
I just ran across my first feed that was only expressed as a JSON-Feed. 

    https://orgorgorgorgorg.org/feed.json

I'd love to be able to subscribe to it in FreshRSS!

**Comment by xppx99** [comment]
I've came into my Reddit personal feed, which is only available in json format... 
This is important because is the only way to subscribe to private subredits (via personal feed). 

![imagem](https://user-images.githubusercontent.com/52202278/151630804-ecb63a56-a02c-408b-9a5d-5b6dd05ddeee.png)

**Comment by Frenzie** [comment]
I don't know why you don't see RSS feeds, but that JSON is completely unrelated to "JSON Feed format". It's just some random JSON.

![Screenshot_20220128_235918](https://user-images.githubusercontent.com/202757/151633209-0ddf9887-096c-4e80-8b87-dd8b29d00f0c.png)

**Comment by isabelgk** [comment]
I wanted to subscribe to https://www.fluentcpp.com/feed/ and found it's only a JSON feed and I can't subscribe with freshrss, so just a small +1 for the request, although I may also try asking for them to publish an XML feed as well. :)

**Comment by Alkarex** [comment]
> I wanted to subscribe to https://www.fluentcpp.com/feed/ and found it's only a JSON feed and I can't subscribe with freshrss, so just a small +1 for the request, although I may also try asking for them to publish an XML feed as well. :)

@isabelgk https://www.fluentcpp.com/feed/ seems to work (again) as proper XML RSS

**Comment by gingerbeardman** [comment]
I had to find new feed URLs for 8 feeds in my imported OPML.

- No error messages were shown on import into FreshRSS
- I had to ask why they were showing as red/warning, see: https://github.com/FreshRSS/FreshRSS/discussions/4359

So, it would be good to get support for JSON feeds to help the next person have an easier time.

**Comment by gingerbeardman** [comment]
Another JSON feed I can't add.

- https://blog.kinopio.club/feed.json

**Comment by gingerbeardman** [comment]
@Alkarex I just used this small php script to convert a JSON feed to RSS.

https://gist.github.com/daveajones/be26f5ca9cb7559d0c33549b53323770

I hosted it locally on my own web server, and then added the resulting link to FreshRSS.

**Comment by appletalk** [comment]
This would be a great feature. I track many software updates in FreshRSS but various OEMs don't seem to provide RSS feeds for their software, however you can often find a json response endpoint.
I have some small custom scripts to build RSS feeds out of these but having this integrated would be even better.

Some example endpoints
**HPE Software API**
https://support.hpe.com/hpesc/public/api/software/MTX_729b6d22f37f4f229dfccbc3a9/history

Dell requires headers to get a response, but you can find the below url queried to load content on this page.
https://www.dell.com/support/home/en-ca/product-support/product/latitude-14-7420-2-in-1-laptop/drivers

**Dell API call**
https://www.dell.com/support/driver/en-ca/ips/api/driverlist/fetchdriversbyproduct?productcode=latitude-14-7420-2-in-1-laptop&oscode=WT64A&lob=Latitude&initialload=true&_=1669277774317

**Comment by Frenzie** [comment]
"JSON Feed" here means the same thing as RSS or Atom (except with JSON instead of XML). Random JSON is something completely different.

**Comment by appletalk** [comment]
Oh my apologies, I misunderstood the feature functionality

**Comment by Frenzie** [comment]
Implementing your request would make this one a breeze while the reverse may not necessarily apply, so I think it's a good thing to keep in mind for anyone interested. ;-)

**Comment by brainsik** [comment]
Hello. I recently migrated off Feedbin to my own FreshRSS instance. It ended up being a bit bumpy due to 20 of the feeds using the JSON Feed format. This meant a manual process of identifying each broken feed in the web interface and editing it with a link to the XML feed. It was surprisingly click/scroll heavy. Additionally, for some sites it was tricky to find the XML as they default to JSON. For those, I had to URL hack / dig around for the XML one.

The migration ended up taking a couple of hours instead of a couple of minutes. It would be great if JSON Feed was supported. :)

**Comment by Alkarex** [comment]
Related experimental PR: https://github.com/FreshRSS/FreshRSS/pull/5079

**Comment by Alkarex** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/5662

**Comment by ghost** [comment]
@Alkarex Hi, when you say "Fixed by #5662" does this mean that people can now subscribe to [JSON feeds](https://www.jsonfeed.org/) with FreshRSS?

**Comment by Frenzie** [comment]
Yes, since 1.24.0.

**Comment by ghost** [comment]
> Yes, since 1.24.0.

Perfect, thank you.
