### ISSUE TITLE
Some duplicates at first refresh when updating to version 1.7?

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#1552]
@Frenzie https://github.com/FreshRSS/FreshRSS/issues/1548#issuecomment-304350170

The change regarding GUID was to target the case of empty GUID (which is invalid), not of missing GUID (which is OK):
https://github.com/FreshRSS/FreshRSS/issues/1482
https://github.com/FreshRSS/FreshRSS/pull/1483

Would you have some example of feeds where you have observed those duplicates when upgrading to version 1.7?

**Comment by Frenzie** [comment]
(Edited out an irrelevant statement because I didn't take the time to read and comprehend properly.) I think basically all of my examples are missing a GUID, not invalidly declaring it empty.

The example I already gave was:
http://onzetaal.nl/rss/taaladviezen/

Some others:
http://www.weblettres.net/blogs/rss.php?w=MonplaisirLett
http://www.stonemakerargument.com/feed.xml
http://apprendre.tv5monde.com/fr/rss
http://www.librarything.com/rss/reviews/.Monkey.

Now this one that was also duplicated is even more curious. Unlike the above feeds which seem to have missing GUIDs in common, this one has completely valid GUIDs:
http://blogs.opera.com/mobile/feed/

<del>Edit:
This one also has a valid GUID:
http://www.hardware.fr/backend/news.xml</del> (I think I was mistaken about this one being duplicated.)

**Comment by Alkarex** [comment]
If you can, could you please compare in your database two duplicate articles (e.g. the guid, link, hash fields)?

**Comment by Frenzie** [comment]
I'll do you one better. Here's two complete <del>drops</del><ins>dumps (dropping and dumping something are pretty similar in normal language… slightly iffier in SQL :-P)</ins>.

* [Opera Mobile](https://github.com/FreshRSS/FreshRSS/files/1033782/freshrss_Frenzie_entry-1.sql.txt)
* [Taaladviezen](https://github.com/FreshRSS/FreshRSS/files/1033789/freshrss_Frenzie_entry.sql.txt)

Here's a relevant excerpt:

```sql
(1495821665227328, 
'http://blogs.opera.com/mobile/?p=1120', 
'Opera Max 3.0 becomes your Android smart assistance', 
'Sergey Lossev', 
lalala,
'http://blogs.opera.com/mobile/2017/05/opera-max-3-0-becomes-android-smart-assistance/', 
1493971200, 
1495821631, 
0x84f5ec5f2eb1afb4ce553a5dd6376eb0, 
1, 
0, 
123, 
'#Opera Max #data saving #facebook #news'),
```

```sql
(1493972126812015, 
'http://www.opera.com/blogs/mobile/?p=1120', 
'Opera Max 3.0 becomes your Android smart assistance', 
'Sergey Lossev', 
lalala,
'http://www.opera.com/blogs/mobile/2017/05/opera-max-3-0-becomes-android-smart-assistance/', 
1493971200, 
1493976632, 
0xed95f9057c7cb9876954e5f292c91e21, 
1, 
0, 
123, 
'#Opera Max #data saving #facebook #news'),
```

Only the hash seems to differ for Opera Mobile, but in the others it's clear that the hash has been used as GUID on newer entries and not the value of `link`. That's definitely not the right behavior.

**Comment by Alkarex** [comment]
Ah, it is due to a SimplePie update: https://github.com/simplepie/simplepie/commit/f1aab12aeffddebddb1d7fa6f14094974747ff99#diff-1c04fa997590b0127d726933eb3bdb1f

current version: https://github.com/simplepie/simplepie/blob/90973c656e81fe750cef6bdace5ba1a14c926c1f/library/SimplePie/Item.php#L212-L252

included as part of my partial manual merge: https://github.com/FreshRSS/FreshRSS/pull/1472/commits/cc235c6af36e4cbfcdced1ee323559a32ca65114#diff-9a793ee134b92c0141960a499229ac6b

I will try to fix.

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1558
Tests needed
