### ISSUE TITLE
Impossible to subscribe to some RSS feed because of lack of HTTP headers

### ISSUE THREAD

**Issue by Massedil** [FreshRSS/FreshRSS#1627]
Some feed required a browser's User-Agent HTTP header, an "Accept-Language" HTTP header or an "Accept" HTTP header, for example.

It would be great if we could add or override the HTTP headers for each RSS feed.

**Comment by aledeg** [comment]
It's a good idea

**Comment by aledeg** [comment]
@Massedil Do you have any feeds falling in that use case?

**Comment by Massedil** [comment]
Yes. 
"https://www.mondialisation.ca/feed" needs a "User-Agent" HTTP header.
"http://www.nord.gouv.fr/syndication/flux/rss_feed_69" doesn't work with FreshRSS, but I don't know why.

**Comment by aledeg** [comment]
Thank you. I'll have a look at them to figure out why they are not working and how to make them work in FreshRSS.

**Comment by Alkarex** [comment]
`nord.gouv.fr` is another example blocking SimplePie:

```sh
curl -v -A "SimplePie/1.3" 'http://www.nord.gouv.fr/syndication/flux/rss_feed_69'
*   Trying 90.85.16.36...
* Connected to www.nord.gouv.fr (90.85.16.36) port 80 (#0)
> GET /syndication/flux/rss_feed_69 HTTP/1.1
> Host: www.nord.gouv.fr
> User-Agent: SimplePie/1.3
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Server: nginx
< Date: Sat, 07 Oct 2017 11:16:27 GMT
< Content-Type: text/html; charset=iso-8859-1
< Content-Length: 230
< Connection: keep-alive
< Vary: Accept-Encoding
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /syndication/flux/rss_feed_69
on this server.</p>
</body></html>
```

**Comment by Alkarex** [comment]
Can now be implemented more easily with https://github.com/FreshRSS/FreshRSS/pull/1838

**Comment by Alkarex** [comment]
There is a new simple extension mechanism to do that.
See https://github.com/FreshRSS/FreshRSS/pull/1924 and included example for Tumblr:

https://github.com/FreshRSS/FreshRSS/blob/7868f2d2f46048164fc9942aa80988f9f1bbdba8/extensions/Tumblr-GDPR/extension.php#L1-L13

Both for security reasons and due to the fact that we cache feed responses between users, we cannot currently allow individual users to use random HTTP headers and other custom cURL parameters; only the admin user can do so.

It is also possible to add some global parameters (in `./data/config.php`) such as `Accept-Language`, which will apply to all feeds.

I hope this will suffice for now.
