### ISSUE TITLE
Maximize bandwidth performance

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1632]
Hello, 

I would like to know if there is some restriction on fressrss code about the number of thread started during the rss actualization ? I'm using freshrss on the a small cpu server with 100Mbits bandwidth, and my cpu during the actualization is only using about 20% and according the monitoring I'm pretty sure that the cpu is waiting for the web request to comeback before launching another request on a different stream.

Is there any tweak possible to maximize the bandwidth and the cpu by starting more thread ?

I hope I'm clear enough :)

Thanks.
e.

**Comment by Alkarex** [comment]
Hello @prysme01 
Indeed, FreshRSS tries to be gentle with the server and should not use too much resources. Indeed, the network latency (waiting from distant servers to answer) is likely to be the main bottleneck.
Please clarify whether you are talking about a manual refresh from the Web interface, or about automated refresh during a cron job?

**Comment by ghost** [comment]
I'm using the web interface to refresh. Can you point me in the right php file to make modifications ?

**Comment by Alkarex** [comment]
In manual refresh from the Web UI, there is already several tasks done in parallel.
See https://github.com/FreshRSS/FreshRSS/blob/eb84d4f8ff8a53f7eac52edf61951e5dba5906fc/p/scripts/main.js#L877-L879
I do not think putting a value higher than 10 will help, because your Web browser will probably not allow many more requests in parallel to your server, and your server will also limit the number of concurrent HTTP requests per client. You can check on your server whether the 10 requests are well processed in parallel as expected.
In any case, I would suggest you add a cron on your server to do the automatic refresh.

**Comment by ghost** [comment]
ok actually it seems limited already to 5 as I can see during the actualization (5 php-fpm process)
I will go with the cron.

And what about the cron option and actualize php script and the concurrent request ?

**Comment by Alkarex** [comment]
The cron job processes feeds sequentially one at a time, in order to avoid using too much resources. When the cron job works in the background, speed is not as important than for a manual refresh during which the user is waiting.

**Comment by ghost** [comment]
Thanks for your time, I will go with cron then.
