### ISSUE TITLE
What is happening when two users have the same feed 

### ISSUE THREAD

**Issue by husimo** [FreshRSS/FreshRSS#1652]
Hello,
I would like to know, what is happening when two users have the same feed, are articles downloaded twice are only once ?
I guess twice since each user can have different update policy.
Thank you

**Comment by Alkarex** [comment]
Hello,
Feeds are only retrieved once, even when there are multiple users.
Since version 1.6.0, when a feed is refreshed for one user, then the other users are also benefiting from it (either immediately or at the next cron, depending on the order the users have had in the cron) https://github.com/FreshRSS/FreshRSS/pull/1280
And even for older versions, the local cache prevented downloading multiple times.
