### ISSUE TITLE
Can't properly use "author" filter

### ISSUE THREAD

**Issue by husimo** [FreshRSS/FreshRSS#1684]
Hello,
I can't use properly "author" filter, It's not working. Or I don't know how to use it.
I have a feed called "Se coucher moins bête" and the author name in feed source is "Se coucher moins bête" be when I use the filter "author:'Se Coucher Moins Bête'" items are not displayed.
Thanks a lot !

**Comment by Frenzie** [comment]
It seems to work for me by author, but the problem is that the author doesn't seem to be displayed anywhere so it's rather difficult to figure out what to search for.

Did you try, e.g., `author:"Se coucher"`? Maybe the `Bête` isn't working out for some reason.

PS Assuming you mean http://secouchermoinsbete.fr/feeds.atom I actually see stuff like this:

```xml
    <author>
      <name>Kranholm</name>
      <uri>http://secouchermoinsbete.fr/users/17932890-kranholm</uri>
    </author>
```
So then I would expect `author:Kranholm` to show results but probably not `Se coucher etc.` NB This isn't based on reading the code, just on intuition plus a quick test.

**Comment by aledeg** [comment]
@Frenzie is right, the author is not the site but the user. If you browse your feed, you can see the author name at the top of the message. And it's not the site.
If you want to filter the feed, you can just click on it in the left panel or on its name in the right panel.

**Comment by husimo** [comment]
Yeah, you are right, my mistake. Thank you.
It would be useful to have a "filter feed". Indeed I can display a specific feed, but if I want only to display only "feed1", "feed2" without using categories (one feed can only have one category :'( ), I can't do it.

**Comment by Alkarex** [comment]
@husimo Please open a new issue for your proposition for filtering by multiple feeds, and close here if your initial question is solved
