### ISSUE TITLE
Views shortcuts are broken

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#1757]
The shortcuts introduced in #1755 are broken since #1714. It relies on css class but those have been replaced by the same class.
I think we should rethink #1714 for the nav bar generation. Or find a better way to match the buttons.

**Comment by aledeg** [comment]
I've got that idea for matching the buttons. There might be a better way to handle that though.

**Comment by kevinpapst** [comment]
Can you please have a look at the comments in #1714 - I guess the last fix merge could lead to strange behaviour ... in the case an extension changes the list of reading modes which is possible since #1714. 
Even though there is only one demo extension existing by now that makes use of the dynamic list of reading modes / views, I guess we could improve the fix to match the links more safely.

**Comment by Alkarex** [comment]
Can this be closed?
