### ISSUE TITLE
Streams do not sort by date correctly

### ISSUE THREAD

**Issue by MorganRamsay** [FreshRSS/FreshRSS#1771]
Streams appear to sort by feed first, then by date, so instead of a mix of articles, you get clumps.

[See this screenshot.](https://i.imgur.com/qI4evfg.jpg)

**Comment by Alkarex** [comment]
Hello,
If you have just installed FreshRSS, this is normal. As soon as you start refreshing feeds (in particular if using a cron job), the articles will be in a more chronological order, especially for FreshRSS versions newer than 1.7.0 (there is a long history https://github.com/FreshRSS/FreshRSS/issues/530 ).
Please check again after a few refresh, and let us know whether there is still a problem.

**Comment by MorganRamsay** [comment]
I have 1.9.0 installed with ~100 feeds. Default refresh time over 2 days. Just "actualized" again.

Articles are still out of order.

**Comment by Frenzie** [comment]
Out of order in which sense? They should be added in the order in which they come in. So if I add a feed that wasn't updated since 2007 it'll still be at the top. The "newest" in `Newest first` is a bit ambiguous I suppose.

**Comment by MorganRamsay** [comment]
Out of order in the sense that posts dated 2017 are interspersed with posts dated 2018. There's no sense to the order in which articles appear in streams. The stream view shouldn't sort differently from the feed view.

Anyway, I looked into this a bit and fixed the issue on my end by changing the SQL queries directly.

I understand the problem the current solution is intended to solve (articles without pub dates), but it is unintuitive, hence the numerous issues that have been posted. In my opinion, "sort by ID" should be an optional sort order for those who subscribe to feeds without the necessary data.

**Comment by Frenzie** [comment]
> I understand the problem the current solution is intended to solve (articles without pub dates)

Is that really what it's intended to do? If there is a technical limitation involved I would imagine it's that sorting by date is hard period, with articles lacking publication dates merely being a cherry on top. :-)

(Sorting by date itself maybe only be hard on the CPU, but if you mark all as read and a new feed entry just showed up with a publication date in the past, what would happen? Mark all as read based on max ID doesn't have to worry about any such issues.)

> but it is unintuitive

I found it quite intuitive that the feed I just added was added at the top regardless when it claims to have been originally published. That way everything else remains exactly as I left it.

**Comment by Alkarex** [comment]
The sorting behaviour has been carefully considered and discussed: Feeds are updated as a group, then new articles are sorted by declared date, then new articles are inserted in database, and articles are then sorted like the database order.

In other words, the sort order is the discovery date, taking into account the declared date within one discovery process.

In a nutshell, for features such as the mobile API, paging,  mark as read a group of articles, to be implemented in a light way, we need guaranties that the declared date does not provide. Furthermore, feeds declared dates are often wrong or problematic. For instance, entries 1 year in the future or the past would respectively stay at the top (annoying) or the bottom (not visible). There is more to it, but this is the short version.

Many other aggregators (past or present) have a similar approach, such as Google Reader, Feedly, The Old Reader, Digg, AOL Reader, etc., simply because sorting by declared date does not work well.

Having a faster refresh rate (e.g. ~2 hours) and more frequent cron (e.g. ~30 min) reduce the problem.

@Frenzie As you can read French, a more detailed explanation can be found in https://github.com/FreshRSS/FreshRSS/issues/530#issuecomment-236394571 (and related issues) and the last optimisation was implemented in https://github.com/FreshRSS/FreshRSS/pull/1470

Here is an example on one of my instances:

![image](https://user-images.githubusercontent.com/1008324/35187493-d63ae32c-fe24-11e7-8878-bcce7b51e261.png)

**Comment by Frenzie** [comment]
@MorganRamsay I gave a very explicit example of the sort of thing I meant by hard. I suppose phrasing it as "sorting is hard" was a bit unfortunate. ;-)

> I personally only care about retrieval date - because I want my "inbox" to feel like an e-mail client.

Hold on, that means the program is acting exactly how you want it to.

**Comment by Alkarex** [comment]
`entry.id` indicates when the article was discovered, and `entry.date` contains the declared date.
We sort by discovery date, i.e. `entry.id`.

The current behaviour is indeed akin to what typical e-mail clients do (e.g. GMail, Outlook, ...), so it sounds like FreshRSS is already doing what you want.

The column on the right-hand side of the Web UI shows the declared date, not the discovery date.

@MorganRamsay What we see on your screenshot seems to be what happens when new feeds are added (i.e. after an OPML import, or manually adding feeds). Could you please post a newer screenshot (without your manual SQL changes)?

Please tell also what the frequency of your refresh cron job is (if any), and what setting you use for refresh rate. Examples:

```
root@srv3:~# cat /etc/cron.d/FreshRSS
MAILTO=root
5,35 * * * * www-data php -f /.../FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1 | grep -v '^PHP Notice'
```

![image](https://user-images.githubusercontent.com/1008324/35193341-550b39be-fea1-11e7-8a6e-094018fc3d0d.png)

**Comment by dcuddeback** [comment]
In case it helps anyone else, I was able to fix this in my database by reassigning the `id` column based on the `date` column after importing my feeds. Something like this in PostgreSQL:

```sql
WITH entry_ids AS (
  SELECT
    id AS old_id,
    date::bigint*1000000 + ROW_NUMBER() OVER(PARTITION BY date) - 1 AS new_id
  FROM freshrss_david_entry
)
UPDATE freshrss_david_entry e
SET id = t.new_id
FROM entry_ids t
WHERE e.id = t.old_id;
```

Then going forward, I expect that a regular cron job for fetching new articles will keep them sorted well, so hopefully this is just needed after setting up the feeds for the first time.

**Comment by dimme** [comment]
I rewrote @dcuddeback's query to run on my MySQL installation where `WITH` statements are not supported. There's probably a more elegant way, but this did it for me:

```sql
CREATE TABLE temp AS SELECT id AS old_id, (date*1000000 + ROW_NUMBER() OVER(PARTITION BY date) - 1) AS new_id FROM username_entry;
UPDATE username_entry INNER JOIN temp ON id = old_id SET id = new_id WHERE id = old_id;
DROP TABLE temp;
```

**Comment by edent** [comment]
@dimme OMG! That is exactly what I was looking for. Took a second to run and my feeds are now sorted correctly. Thank you so much.

**Comment by ProjectMoon** [comment]
Edit: this does not seem to work anymore in 1.22.

Similar for SQLIte:

```sql
CREATE TABLE temp AS SELECT id AS old_id, (date*1000000 + ROW_NUMBER() OVER(PARTITION BY date) - 1) AS new_id FROM entry;
UPDATE entry set id = (select new_id from temp WHERE old_id = id);
drop temp;
```

**Comment by BrodyStone21** [comment]
I'm running freshrss and mariadb in Docker. How would I do this?

**Comment by LeifAndersen** [comment]
@ProjectMoon Shouldn't the last line be DROP TABLE? Making your chunk be:

```
CREATE TABLE temp AS SELECT id AS old_id, (date*1000000 + ROW_NUMBER() OVER(PARTITION BY date) - 1) AS new_id FROM entry;
UPDATE entry set id = (select new_id from temp WHERE old_id = id);
DROP TABLE temp;
```

(As for you @BrodyStone21, I sadly have no idea as I've never used MariaDB before. :( Sorry )

**Comment by lonseidman** [comment]
> I rewrote @dcuddeback's query to run on my MySQL installation where `WITH` statements are not supported. There's probably a more elegant way, but this did it for me:

Awesome !! thank you!

BUT - Subsequent adds still have the same issue. When I run the code again I'm getting duplicate primary key errors as this is dependent on the row number. Any code we can run for subsequent additions to the database?

**Comment by Philcomputing** [comment]
I receive the following error message when I execute the query: 

`"#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OVER(PARTITION BY date) - 1) AS new_id FROM username_entry' at line 1"`

What am I doing wrong?

Is there now a plugin that ungroups feeds and displays articles chronologically by the publication date?

**Comment by remy56k** [comment]
> Edit: this does not seem to work anymore in 1.22.
> 
> Similar for SQLIte:
> 
> ```sql
> CREATE TABLE temp AS SELECT id AS old_id, (date*1000000 + ROW_NUMBER() OVER(PARTITION BY date) - 1) AS new_id FROM entry;
> UPDATE entry set id = (select new_id from temp WHERE old_id = id);
> drop temp;
> ```

Thanks, it's perfect to reorder the feed as a true timeline after new URLs are added. But sometimes I have an error about `UNIQUE constraint`.

This is my workaround, before run your query, just give a dumb id to each entry, so when the update comes, there are no more errors : 

```sql
-- Reset the existing id to avoid UNIQUE constraint during the update
WITH numbered_rows AS (
  SELECT ROWID AS rowid, ROW_NUMBER() OVER () AS new_id
  FROM entry
)
UPDATE entry
SET id = (SELECT new_id FROM numbered_rows WHERE entry.ROWID = numbered_rows.rowid);
-- Create new id from publication date
CREATE TABLE temp AS SELECT id AS old_id, (date*1000000 + ROW_NUMBER() OVER(PARTITION BY date) - 1) AS new_id FROM entry;
-- Update with the reordered id
UPDATE entry set id = (select new_id from temp WHERE old_id = id);
-- Drop the temp table
DROP TABLE temp;
```

I've wrapped the queries in a little Go binary, wich make a backup before run queries. So now I just need to execute the binary with the path of the db, the backup is created and all entries are ordered by publication date.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/7149

**Comment by ibm-cloud-storage189** [comment]
https://phps.space/questions/the-solution-for-querying-your-inbox-using-sql Check out this explanation
