### ISSUE TITLE
Date sorting of feeds strange in my 1.9.0 install

### ISSUE THREAD

**Issue by poVoq** [FreshRSS/FreshRSS#1782]
First off, awesome work on this!

I have a strange issue though... if you check my site: https://watsan.eu/feeds/

And scroll down a bit you will notice that there are again newer entries below older ones. Previously I was using a different rss reader with the same feeds and I never noticed any strange sorting. So I guess FreshRSS is somehow parsing the posted dates and visible dates differently?

Also, is there a way to enable some date separators like day or week? Right now it only shows the date of today on top. But I saw on some older screenshots that feeds were separated by date. I don't see that option any were in the settings though.

Thanks for the help.

**Comment by Frenzie** [comment]
The entries are sorted in the order they come in, like e-mails. What's displayed is the original publication date. It's only on the first import that it might look a touch odd; after that it'll only happen when you add a new feed, and it'd be annoying if it didn't. ;-) A present date would be very misleading, and sticking it in "where it belongs" would be harder to use because suddenly your newest stuff would be at the bottom.

![screenshot_2018-02-09_21-39-21](https://user-images.githubusercontent.com/202757/36049085-d11c3c02-0de1-11e8-9a4d-e14fc86ba817.png)

After a couple of days they will split in today, yesterday, and before yesterday.

**Comment by poVoq** [comment]
So if I add a low volume feed it will put all the months old posts at the top?
That seems like a very counter intuitive way of handling things, when the original publication date would be much more logical.

**Comment by aledeg** [comment]
We already have that kind of discussion.
Here are some reading:
- #1771 
- #530 
- #1430 
I hope it will help you understand how it's done and why.

**Comment by poVoq** [comment]
Ok fine. I guess there are worse things in life ;)

**Comment by Frenzie** [comment]
The issue is closed, but since I just added a feed I have an even better illustration. :-P

![screenshot_2018-02-12_12-48-11](https://user-images.githubusercontent.com/202757/36095583-12cdb564-0ff3-11e8-9f94-2d766193d9c0.png)

**Comment by Frenzie** [comment]
I certainly think both sorting options are sensible, but that this one makes the most sense for the main view.

The funny thing is that my reaction was the opposite, as in I really like this default. I used Opera for many years. After its demise I took a brief excursion with QuiteRSS, but I realized that I needed some kind of sync because I sometimes missed stuff if I didn't start the program for a while. Anyway, out of all the features that I presume to be Google Reader-esque, most of which I consider neutral at best,[1] this is the one I'm really into. 

I never liked it when something new just randomly polluted the timeline. So what if it's from days, weeks, months or even years ago? It's new to me. :-) This is why in QuiteRSS you have `published` and `received`. The (minor) problem in QuiteRSS is that I only care for received as a sorting mechanism. As general visual information I just find it distracting, but as far as I know sorting by `received` is only easily possible in the program if you display the column.

I suppose that ideally, FreshRSS would also have sort by published. But it falls in the category of things for which you'd only have a rather small chance of getting me to write something in the area by somehow piquing my interest. ;-D

[1] On the below neutral side, I like a distinction between deleted (even if that technically might mean hidden), read, and unread. Instead you have this big blob of read, among which you need to navigate with favorites and external saving. I'm mostly used to it now, some two and a half years later. :-P More seriously it probably only took a few weeks to months. I didn't write [my first contribution](https://github.com/FreshRSS/Extensions/pull/4) until after I decided I could stick with it for the long run. But I still [disprefer](http://languagelog.ldc.upenn.edu/nll/?p=2186) it.
