### ISSUE TITLE
Fix translation inconsistencies

### ISSUE THREAD

**Issue by poVoq** [FreshRSS/FreshRSS#1783]
"Your RSS feeds" and "Your Favourites" sounds a bit strange when it is in fact a public view of the default user.

Would be nice if this minor issue was solved :) Thanks!

**Edit** There are more inconsistencies in the translations than the one reported originally. That's why I've edited the title and the original issue. -aledeg-
- [ ] ```Your RSS feeds``` vs ```Main stream```
- [ ] ```Your favourites``` vs ```Favourites```
- [x] ```User queries``` vs ```User filters```

**Comment by Frenzie** [comment]
I was a bit confused about where these strings even occur, but it's in the window title. :-)

Setting aside whether it should say "your", I find the discrepancy somewhat odd.

**Comment by poVoq** [comment]
Not only the window title but also very large in light grey on the top right. At least with the flat theme.

**Comment by Frenzie** [comment]
Heh, I guess I never really look up there in the corner. I'd say get rid of that visual distraction completely. :-P

**Comment by aledeg** [comment]
It occurs also in other themes. It is supposed to reflect your selection in the menu, so it displays the category or feed you've used as a filter.
There is a discrepancy between what's written in the top right corner and what is selected in the menu. The same discrepancy occurs in the title.

We should correct those discrepancies. But we should also think if we need redundancy for that type of information. I know it's useful when you browse on a mobile device since the menu is hidden.

**Comment by Frenzie** [comment]
Oh yes, good point. I probably look at that on my phone almost daily. But all the other categories simply take their category name. So yes, just "Main stream" and "Favorites." Besides which, some silly part of me is also bothered by that RSS since I go for Atom whenever I can.

**Comment by aledeg** [comment]
See #1823
