### ISSUE TITLE
Mobile : No access to parameters

### ISSUE THREAD

**Issue by Glaived** [FreshRSS/FreshRSS#1876]
Hi,

on a smartphone, there is no icon to access the settings, would it be possible to fix it?

![capture-20180430220226-375x387](https://user-images.githubusercontent.com/1835170/39447501-3b042cb4-4cc2-11e8-8515-d86d089a60ea.png)

**Comment by seboss666** [comment]
Hello,
I see this issue is still opened but not much activity, so i'll add my two cents just in case.
With the current behaviour of feed management settings, I can understand that convert the settings interface is not a trivial task so mask it at first place is not necesarily bad. But it's not good when your main use of FreshRSS is from mobile (and not a third party app like easyrss that does not work correctly on my phone).
Do you have at least some ideas about how you plan to do that ? Maybe at first just expose the feeds managements settings (categories, feed addition/modifications), as I think it's the main feature freshrss may manipulate in a day-to-day usage. Sadly I'm not skilled enough particularly in CSS to help it, aside from testing.

**Comment by seboss666** [comment]
I've tried it from the bookmarklet to see how it copes. It is not broken as we could have expected, but it's clearly not suitable for mobile viewport. I've posted a screen on my last blog post (the reason I'm getting here in fact :) ) : https://blog.seboss666.info/2018/12/les-flux-rss-sur-youtube-la-fin-de-mon-compte-google/

**Comment by Frenzie** [comment]
Oh, I guess I only looked at the subscriptions management window.

There's the padding in .post.

There's the left in `#slider.active` and the left margin in .form-group .group-controls which takes care of the worst of it.
```css
.form-group .group-controls {
    min-width: 250px;
    /* margin: 0 0 0 220px; */
}
```

And there's the width of textarea:

```css
textarea {
    /* width: 360px; */
    height: 100px;
}
```

Not quite right, but anyway, that's just a few minutes of preliminary investigation. ;-)

![screenshot_2018-12-24_10-52-34](https://user-images.githubusercontent.com/202757/50396404-20d0e680-076a-11e9-8d02-f3f7fcf748a9.png)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1929
