### ISSUE TITLE
API Password error

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1885]
Hello,

When trying to define API password for an user, we get an error 403 - Forbidden with Firefox Developper Edition 61.0b3 (64bits), FreshRSS v1.10.2.

Did not see anything in the log, but I may have miss this.

Ok with Firefox "normal edition" and Chromium Browser.

Thanks,

xakan

**Comment by ghost** [comment]
I applied all code changes seen [here](https://github.com/FreshRSS/FreshRSS/pull/1877/files), and it seems it's still not working.

**Comment by DrXala** [comment]
Hi @Alkarex ,
Yes, I have user and password account autocompleted. I have not any autocomplete with Chromium.

**Comment by DrXala** [comment]
Ok, when I delete password account autocompleted, it's work!

**Comment by Alkarex** [comment]
I believe the problem is that after changing the API password, some users might get a prompt from their password autocomplete manager, asking them whether they want to update the password used to log into FreshRSS, and they click yes, which is wrong.
We could give a warning to users. On the technical side, we could avoid using the `password` input type, but I am not sure to want to do that - as from my point of view, it is the behaviour of some automatic password managers that is wrong.
