### ISSUE TITLE
Fever API: Error on favorites display

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1923]
Hi!

Context : I tried Unread iOS app and configured it with fever api.

I made some tests, especially about favorites.

I read some articles, unmarked as favorites, and marked some others.

When going back to browser interface, my number of favorited articles was correct, but not displayed (see attached screenshot).
![capture du 2018-06-07 08-10-51](https://user-images.githubusercontent.com/7924208/41098553-17272f96-6a5c-11e8-85d9-4678006af499.png)

The following query returned 59 rows : SELECT * FROM freshrss_xakan_entry where is_favortie = 1;

This morning, I saw that one of my feeds was in an error state, so I deleted it form the list. After that, everything went fine again.

I did not see anything special in my user's log, but I can give it if needed.

xakan

Edit : For information, that feed was in this state since a week, not only since yesterday.

**Comment by Alkarex** [comment]
@xakan In the screenshot you have posted, it looks like there is one unread favourite (the one shown), and a number of read favourites (by default, a few shows only unread articles, if there are any - this can be tuned in the options). I think everything is working as expected, although we should probably tweak the UI a bit to make it more obvious.

**Comment by xakan** [comment]
All my favorites are unread. I use to mark as favorite in order to read it later.

Here, I have 60 favorites. All are displayed.

![capture d ecran 2018-06-08 a 07 33 18](https://user-images.githubusercontent.com/7924208/41140542-5cd4de52-6aee-11e8-8c68-31a1d09e7604.png)

I never changed anything in the options, except here :
![capture d ecran 2018-06-08 a 07 36 18](https://user-images.githubusercontent.com/7924208/41140593-ac77b06a-6aee-11e8-9838-c4fc50be4b63.png)

**Comment by ghost** [comment]
Ok, just saw that, but not before because my favourites are always marked as read.

Thank you for your explanation, and sorry for the issue, you can close if you want :)
