### ISSUE TITLE
Make a user an admin

### ISSUE THREAD

**Issue by Wdavery** [FreshRSS/FreshRSS#1987]
Not sure if I am missing this, but is there a way to make a user an admin? I can't find it in the GUI or in the CLI tools, like update-user.php where I thought the option would be.

**Comment by Alkarex** [comment]
Hello,
From the CLI, try `./cli/reconfigure.php --default_user YourNewAdmin`
https://github.com/FreshRSS/FreshRSS/tree/master/cli#commands

**Comment by Wdavery** [comment]
Thats the ticket! Thank you.

It would be nice to have the as part of the "Manage Users" GUI as an admin.

**Comment by jfmessierdotca** [comment]
Does this mean that a single user is an admin, everyone else is a regular user ? How can I make someone else an admin ?

**Comment by Alkarex** [comment]
@jfmessierdotca Indeed. Currently, we have one *main user*, also called *default user*, or *admin*. All the others are regular users. There is no UI for changing it, but a CLI (see above), or manually by editing the text file `./FreshRSS/data/config.php` and change `'default_user' => 'alice',` to the user you want.

**Comment by jfmessierdotca** [comment]
This is what I was suspecting, and since the initial installation (to be shared) had my own name (jf) instead of "admin" or "root", I actually added the user when I was administrating the sire under my name, and then changed the admin username in the config.php to the newly created "admin". Any plan on having a web-absed admin management, with perhaps different levels of privileges ?

**Comment by Alkarex** [comment]
@jfmessierdotca A Web UI to change the admin would be trivial. The different levels of privilege would not be too difficult to add, but we do not really have seen a use-case for that yet.

**Comment by jfmessierdotca** [comment]
Also, having more than one user as an admin could be interesting. We have a web site for our Linux user group, and we are mainly two managing the site. In order to keep our own passwords separate, we have to create a separate user, like "admin" with basically no feeds, and share the password, as opposed to have our two users with admin privileges. But this is not a big deal at this point. I guess it was more that this was not something so obvious in the documentation. And I realize that most of the time, this is for a single user. But in my case, we may be 20-30 users on this server having different reading interests.........................  
  
Thanks for the response :-)

**Comment by Alkarex** [comment]
@jfmessierdotca Ok. Could you please open a new dedicated issue for the case of multiple admins (explaining again the use-case), so we can keep track of it?
FreshRSS is supposed to scale quite well to many users, also on small servers, and there is a number of deployment tweaks that can be done for even larger instances. I would be interested in getting some feedback on how well this works for you.

**Comment by jfmessierdotca** [comment]
Sure I can. I am perhaps  less familiar with the way GitHub works for "Cases", sure I can open a new case for this. I will take a look and let you know how this works. I should be able to figure this out.
