### ISSUE TITLE
Preview mode?

### ISSUE THREAD

**Issue by planetahuevo** [FreshRSS/FreshRSS#2038]
Hi,
I was using my FreshRSS today and was wondering if is it possible to have a "preview mode" for the list.

The idea is to be able to read the first paragraph of the content, instead of only the title.
With so many "click bait titles" or not titles that are really bad, I end up opening each article to decide if it is interesting or not.
It would be fantastic to have this option on the "view modes".
Thanks

**Comment by math-GH** [comment]
@planetahuevo have you tried the "Reading view"? Does it solve your feature request?

![grafik](https://user-images.githubusercontent.com/1645099/127050500-ff5eefd4-1c84-48d4-9c3b-70d8b7f12c0d.png)

The "Reading view" shows title and teaser without opening the feed item with a click

![grafik](https://user-images.githubusercontent.com/1645099/127050945-47e24c7e-bcc4-4f8c-b86d-fc2e3d17d67e.png)

**Comment by ORelio** [comment]
I think #561 (implemented in #3805) might address this, at least partially, because it allows displaying a bit of text for each article:

![image](https://user-images.githubusercontent.com/1128206/130869429-f9e70a0d-5d05-43ab-884c-7e00e444fc20.png)

It's not a whole paragraph, but might suffice to decide whether to open the article or not. Also you can disable the thumbnail.
