### ISSUE TITLE
Cannot close an article that is opened and marked as unread

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#2085]
Steps to reproduce : 
- open an article,
- mark it as unread
- try to close it by clicking on the title

-> not working

**Comment by Alwaysin** [comment]
Cannot say for sure but I think I would have noticed if it was already there!

**Comment by pattems** [comment]
I'm not really well-versed in javascript, but I'm poking at this a bit to see if I can work something out; the issue is bigger than reported, however. The addition of the .keep_unread class makes a flux element completely non-interactive as long as the keep_unread class exists. (Manually marking an item previously marked as keep_unread only clears not_read, and doesn't clear keep_unread until a page reload; this has to be unrelated since it also worked that way in 11.2, but possibly behaviour that should be changed?)

**Comment by Alkarex** [comment]
Fixed by @pattems in https://github.com/FreshRSS/FreshRSS/pull/2092
