### ISSUE TITLE
Docs update: Firefox 63+ no longer includes browser.contentHandlers.types

### ISSUE THREAD

**Issue by ryliejamesthomas** [FreshRSS/FreshRSS#2100]
Hi! Unfortunately Firefox no longer supports adding browser-based subscription services, as it's removed the `browser.contentHandlers.types` preferences in about:config :(

So the documentation at https://freshrss.github.io/FreshRSS/en/users/04_Subscriptions.html#firefox-subscription-service is no longer relevant.

Was gunna do a pull request, but not sure if you want to leave the text there for users on older versions or not.

**Comment by Frenzie** [comment]
Why would they remove such a thing? Another victim of the "just make/install an extension for it" craze? :-/

Firefox 60 ESR will be supported for another year, so I'd say it'd be a tad early to remove it.

**Comment by Alkarex** [comment]
😢 Another sad move by Firefox (still my favourite browser, but I am annoyed by e.g. the removal of RSS).
I agree with @Frenzie to keep it a bit longer, but @ryliejamesthomas , could you please make a PR to explain that this feature is removed from Firefox after version X?

**Comment by ryliejamesthomas** [comment]
Yep, I'll get to it over the weekend @Alkarex

**Comment by Leepic** [comment]
@Frenzie @Alkarex : 
The [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/2/Adding_feed_readers_to_Firefox#Adding_a_new_web-based_feed_reader) say that this feature was removed because it's not in the HTML5 spec:

>Support for adding feed readers from the web was removed from the HTML5 spec, and Firefox support is scheduled for removal in Firefox 62.

On Firefox Mobile it's still present (for the moment), tested with the nightly build number 65.0a1 (2018-11-03).

**Comment by ryliejamesthomas** [comment]
@Leepic that's specifically referring to using JS to add subscription services, by my understanding?

Manually adding them has nothing to do with HTML5

**Comment by Frenzie** [comment]
> Manually adding them has nothing to do with HTML5

They are somewhat related. The website-based JS is/was a convenient method for web services to make it easier to add themselves to those very preferences. It's just weird that they thought it'd be a good idea to go back to pre-'05(?)ish as far as this feature goes. I haven't investigated if there are workarounds yet because admittedly I don't use the feature myself.

![screenshot_2018-11-04_08-36-50](https://user-images.githubusercontent.com/202757/47961542-4a448000-e00d-11e8-8981-d5a95041b2f8.png)

**Comment by Alkarex** [comment]
@ryliejamesthomas or @Frenzie Would you please make a small PR to update the doc, now that Firefox 64 is out?

**Comment by Frenzie** [comment]
I'm not on a computer with Git atm. Was it indeed removed?

**Comment by Alkarex** [comment]
Yes, removed. I am trying the extension https://addons.mozilla.org/firefox/addon/want-my-rss/

**Comment by aledeg** [comment]
I think we could close that issue

**Comment by Frenzie** [comment]
Will be fixed by #2590, so I'll close this now.
