### ISSUE TITLE
Suggestion: Drop support for Internet Explorer

### ISSUE THREAD

**Issue by pattems** [FreshRSS/FreshRSS#2159]
I'd initially started writing this in my most recent message on the scrollbar pr, but I figured it would get more visibility for potential discussion as an issue.

If there's not already a timeline in place for dropping support for Internet Explorer 11, I'd suggest that the time has come to start thinking about it. Per Microsoft, when they released Edge, "The latest features and platform updates will only be available in Microsoft Edge. We will continue to deliver security updates to Internet Explorer 11 through its supported lifespan."(1) As Windows 10 has an indefinite End Of Life date and IE11 will (allegedly, anyways) be supported until the EOL date of Windows 10, this leaves FreshRSS indefinitely stuck with either using web technologies available in IE11, circa 2015, or relying on polyfills for that browser, which has a rapidly shrinking userbase.

According to StatCounter's Global Stats, in the last 3 years, Internet Explorer Usage has dropped from 9.65% to 2.8% (2), and Desktop usage has fallen from 16.79% to 5.36%. (3)

I'm not suggesting anything as drastic as immediately dropping support for IE, but I think it's time to consider a timeline for phasing out support in the future.

Thoughts, Questions, Concerns?

(1) https://web.archive.org/web/20160716113141/https://developer.microsoft.com/en-us/microsoft-edge/platform/faq/ (General Platform Questions -> Will Internet Explorer 11 continue to receive updates?)
(2) http://gs.statcounter.com/browser-market-share#monthly-201511-201811
(3) http://gs.statcounter.com/browser-market-share/desktop/worldwide#monthly-201511-201811

**Comment by Frenzie** [comment]
There's a difference between dropping support and accepting it won't get all the fancy new stuff. But I'm not sure if I understand why there should be a timeline? Unless by "timeline" you mean a set of conditions completely unrelated to time.

**Comment by pattems** [comment]
In my mind, supporting a browser means that it should have feature parity with other browsers. If the aim of supported is just being usable even if the UX is different on different browsers, then I'll adjust my definition and close the issue.

Perhaps Roadmap would have been a better choice of terms, because I didn't suggest a condition. It could be time based (at the end of some year), or it could be conditional (when global/desktop usage drops under a certain threshold, when X amount of features would have to be polyfilled to reasonably support IE).  Again, this is only a relevant concern now and in the near future if the aim is feature-parity.

Ultimately, my point is that IE is a dead browser walking, and at some point in the future the project will need to stop supporting it (for whatever definition of support we're using), and it's a good idea to have an idea in mind for when that deadline will be, so you're not just jerking the rug out from under any potentially impacted users when the time comes.

**Comment by Alkarex** [comment]
Yes, as just answered partially on https://github.com/FreshRSS/FreshRSS/pull/2117#issuecomment-443421100 , I think we should just ensure that FreshRSS is OK-usable with IE11, but not seek to have full feature parity with all the details. So concretely, we should update the README to reflect that, not to give the impression that IE11 is as well supported as the others. I think this aligns quite well with what @Frenzie just wrote.

**Comment by Alkarex** [comment]
In related news, Edge is dead: https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/
On a personal note, I think it is a great loss for the Web to have one less engine :(
https://blog.mozilla.org/blog/2018/12/06/goodbye-edge/

**Comment by Frenzie** [comment]
Agreed. I hope they'll make a decent contribution to the Blink engine.

As an aside, for all the bug reports I've submitted people from Google said "meh" or "is this still an issue on Blink" (yes, I linked to the WebKit bug report because it was never fixed at all like I wrote, grrrrr), but then in several cases someone from Intel stepped in and fixed it.

So if nothing else, I hope Microsoft will be like Intel.

I'm sharing that mostly because I was surprised to see people from Intel working on regular SVG/CSS stuff as opposed to a few Intel/x86-related speed optimizations or something along those lines.

**Comment by pattems** [comment]
Just as a dissenting opinion, I don't view the loss of a closed-source engine with a small market share as a great loss on it's own. It certainly has the potential to be a loss if Microsoft doesn't contribute to Blink, but it's in their best interests to do so.

I recognize that having options for viewing the web is important, and wish the folks at Mozilla continued success... but at the same time I have a hard time being sad about a closed-source component being replaced by one that's open.

This could be pure naïveté on my part, and I may live to eat my words, but at this point I remain cautiously optimistic about these developments.

**Comment by Alkarex** [comment]
If everybody is on Blink, then Web standards are dead, as it becomes a proprietary technology (albeit an open source one). A key aspect of a (Web) standard is to have multiple independent and interoperable implementations.

See e.g. https://www.w3.org/TR/css3-conditional/ (which is now fine, given its implementation in Gecko, Blink, EdgeHTML, but just as an example):
> The ‘`@supports`’ rule is at risk; if interoperable implementations are not found, it may be removed to advance the other features in this specification to Proposed Recommendation.

Without that key aspect, bugs becomes features, SHOULD / MAY become MUST or MUST NOT, and it becomes near-impossible for a new actor to emerge. With a big dominance of one single engine, alternative ones will be in a *follow-or-die* position, because (bad) development will solely target that engine. We are back to a situation similar than the IE6 era.

To exemplify that, this post (in French, sorry) from a few days ago https://framapiaf.org/@framasky/101233620110887691 where the guy says that IE11 must die because it caches an HTTP response (when Chrome does not), except that... IE11 was right :P This allowed the discovery of a bug (or at least bad practice) in the guy's code.

With all that said, and given the situation, I do hope just like you that Microsoft's involvement in Blink will counterbalance a bit Google's monopoly...

**Comment by Alkarex** [comment]
Historically, HTTPS caching in some browsers has been more opt-in, while HTTP caching has mostly been more opt-out, but we digress 🤓
