### ISSUE TITLE
Please make the Feed URL a unique key

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#2167]
I subscribed to a feed twice. It would be great to have a constraint, which does not allow to do so.

**Comment by Alkarex** [comment]
Hum, there is already a constraint to avoid duplicates. There is most likely a difference in your different copies, such as an HTTP vs. HTTPS version. Could you please send a screenshot?

**Comment by Alkarex** [comment]
What type of database are you using?

**Comment by ddeimeke** [comment]
> Hum, there is already a constraint to avoid duplicates. There is most likely a difference in your different copies, such as an HTTP vs. HTTPS version. Could you please send a screenshot?

Unfortunately not, I deleted the second entry.

> What type of database are you using?

MariaDB 10.3.11 with PHP 7.2.13

**Comment by Frenzie** [comment]
I was also thinking something with redirects. @Alkarex's hypothesis is correct since it leads to reproducible double subscriptions:

![screenshot_2018-12-08_08-01-48](https://user-images.githubusercontent.com/202757/49683100-b4928980-fabf-11e8-84a5-d6492930928b.png)
![screenshot_2018-12-08_08-03-03](https://user-images.githubusercontent.com/202757/49683102-b52b2000-fabf-11e8-8281-923a5b17d1a8.png)
![screenshot_2018-12-08_08-03-39](https://user-images.githubusercontent.com/202757/49683109-c96f1d00-fabf-11e8-971e-be18210f99cf.png)

Since we're dealing with a 301 from HTTP to HTTPS, I thought the feed URL was supposed to update itself automatically?

https://github.com/FreshRSS/FreshRSS/blob/e04804d0f67dd43fd3f072b9a127768ee7b7b56c/app/Controllers/feedController.php#L453-L456

Note that there's a distinct lack of a notification like that in my logs.

**Comment by ddeimeke** [comment]
I am pretty sure, that I used the https link, but I can not reproduce it.

**Comment by Frenzie** [comment]
You should be able to add one of `http://www.kuketz-blog.de/feed/` or `https://www.kuketz-blog.de/feed/`.

> Since we're dealing with a 301 from HTTP to HTTPS, I thought the feed URL was supposed to update itself automatically?

It only now occurred to me that this will only happen after adding the feed, unless I missed a piece of logic somewhere.

**Comment by Alkarex** [comment]
Yes indeed, it is because the redirection rules are first applied after adding the initial address in the database. And if there is already a feed at the same address than the redirections, the renaming of the URL cannot happen. We should be able to fix the logic when adding the feed. But we will still have the problem when subscribing to feeds A and B and at some point later, they both start redirecting to the same address C.

**Comment by math-GH** [comment]
Does it make any troubles? It is not so nice to have a feed twice, but it should be easy to remove one of them, isn't it?

**Comment by math-GH** [comment]
I cannot reproduce it anymore. @ddeimeke Could you please check with 1.19/1.20?

**Comment by Alkarex** [comment]
In any case, the problem is not uniqueness, which we already have, but conflicting redirections

**Comment by ddeimeke** [comment]
@math-GH I can not reproduce it either and I second @Alkarex that it is most probably the result of redirections.
