### ISSUE TITLE
New articles banner in mobile UI breaks article emersion

### ISSUE THREAD

**Issue by goodnewz** [FreshRSS/FreshRSS#2379]
When new articles are available, in mobile view, the blue banner that displays the message stays in the middle of the article content and breaks article reading emersion. See the screenshot below. 

There should be a way to either dismiss that message or have it appear on top of the page in mobile view. 
 
![Screenshot_20190403-220306](https://user-images.githubusercontent.com/25808527/56449297-56837780-62e5-11e9-8d7b-a7a1a6214e3a.jpg)
![Screenshot_20190419-090426](https://user-images.githubusercontent.com/25808527/56449298-56837780-62e5-11e9-95fb-5d33de0df386.jpg)

**Comment by pattems** [comment]
This _should_ be a Swage specific issue, because my theme is pretty much made of pure hackiness and this is a thing I didn't consider. Should be as simple as the two-line fix I just committed to my repo. ~~Got to test it, but I should be able to submit this as a PR tomorrow~~.

Edit: Turns out I _did_ still have a dev instance sitting around, so PR's been submitted.
