### ISSUE TITLE
Allow @ sign in username

### ISSUE THREAD

**Issue by brknkfr** [FreshRSS/FreshRSS#2391]
As I am using an IMAP-Backend for authentication I want to be able to use mail addresses as usernames.

Using the cli interface it's no problem to add usernames with an @ sign, but unfortunately it's not allowed on the web interface.

Please change 

`const USERNAME_PATTERN = '[0-9a-zA-Z_][0-9a-zA-Z_.]{1,38}|[0-9a-zA-Z]';`

in

`app/Controllers/userController.php`

to something more useful like maybe

`const USERNAME_PATTERN = '[0-9a-zA-Z_][0-9a-zA-Z_.@]{1,38}|[0-9a-zA-Z]';`

(Added only an @ in pattern.)

**Comment by Frenzie** [comment]
Also see #2062 and #1423 for previous relaxations. I can only imagine the username characters are so restrictive for compatibility reasons of some sort.

Looking at the history it used to be [ctype_alnum()](https://www.php.net/manual/en/function.ctype-alnum.php), so perhaps it was just because it's a simple, foolproof check. See https://github.com/FreshRSS/FreshRSS/commit/1ac09e7fe4a5408290d06116c6fb8152e018fe26.

> Using the cli interface it's no problem to add usernames with an @ sign, but unfortunately it's not allowed on the web interface.

Sounds like a bug. ;-) The checkUsername() method (or whatever its precise name is) should be used there too.

**Comment by aledeg** [comment]
The problem is the pattern. When use in ```checkUsername``` it behave like if we are testing ```^0-9a-zA-Z_][0-9a-zA-Z_.]{1,38}``` or ```[0-9a-zA-Z]$```. I assume that what we want is ```^0-9a-zA-Z_][0-9a-zA-Z_.]{1,38}$``` or ```^[0-9a-zA-Z]$```.

See #1511 and #1512. @Alkarex what was the basic idea behind that fix? Did I missed something?

**Comment by Alkarex** [comment]
@aledeg You are correct, that is a bug. I am testing a new pattern

Edit: https://github.com/FreshRSS/FreshRSS/pull/2407#issuecomment-502468456

**Comment by Alkarex** [comment]
Merged in the /dev branch. Tests welcome
