### ISSUE TITLE
[feature request] keyboard shortcut to go to main stream

### ISSUE THREAD

**Issue by nekr0z** [FreshRSS/FreshRSS#2405]
Such a shortcut would be extremely useful.

Common scenario: a user has their FresRSS open in a browser tab, reads articles using keyboard shortcuts. New articles appear after refresh, but the user can not access them without clicking...

**Comment by aledeg** [comment]
@nekr0z Actually, such shortcut already exists. It does not show in the configuration page because of a misplaced field. It will be fixed as soon as my PR is merged.
If you use "Open the first article" and "Open the last article" with the "Alt" modifier, FRSS should behave the way you want.

Let me know if all of this make sense.

**Comment by nekr0z** [comment]
@aledeg It does make sense, it does work, it does do its job, so the only thing missing is exposure - as a user I'd never have guessed it exists. I guess your PR fixes that, too. Thank you!

**Comment by aledeg** [comment]
:+1: great! So I'll close this issue as soon as the PR is merged. The exposure is fixed in it.

**Comment by aledeg** [comment]
@nekr0z It's available in dev branch. It will be in the next release but if you cannot wait you can use the dev branch.
