### ISSUE TITLE
Question: Exclude via css path fetching?

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#2425]
Sometimes there are div's or paragraphs containing ads  or some other unwanted content in a css path fetched article. Is there some way to exclude/filter this content?

for example:
```
<div id='article'>
<p class='content'>wanted content</p>
<p class='add'>unwanted content</p>
<p class='content'>wanted content</p>
</div>
```
I want to have all .content, but not .add

**Comment by Frenzie** [comment]
It wouldn't necessarily be overly difficult to add.

https://github.com/FreshRSS/FreshRSS/blob/d413f67dd28738f4a6d8cf036e00714737f757b8/app/Models/Entry.php#L318-L378

Over in the `if ($html)` block you could remove some childnodes matching removal selectors.

https://github.com/FreshRSS/FreshRSS/blob/d413f67dd28738f4a6d8cf036e00714737f757b8/app/Models/Entry.php#L361-L375

**Comment by printfuck** [comment]
I think this would be a useful feature, too.

But in the given case there is still an easy solution. Your Filter would be the following:

`#article p.content`

The problem would still exist in the following case:
```
<div id='article'>
<h2>wanted</h2>
<p class='content'>wanted content</p>
<p class='add'>unwanted content</p>
<h2>wanted</h2>
<p class='content'>wanted content</p>
<h2>wanted</h2>
<p class='add'>unwanted content</p>
<p class='content'>wanted content</p>
</div>
```
Now you could theoretically use an expression like:

`#article p.content, #article h2`

Which would select content and header but, due to the bad implementaion of the comma, in lib_phpQuery.php they would be in that order with headers after the content blocks.

I'd suggest changing the implemention in lib_phpQuery by adding a sort at the end of the find() method. You can sort by getLineNo() on an xmlNode. 

You'd just have to add the following to the `phpQueryObject` class:
```
private function cmpByLineNo($a , $b ) {
    return ( $a->getLineNo() <= $b->getLineNo() ) ? -1 : 1;
}
```
And the following to the find() function in the same class:
Before:
https://github.com/FreshRSS/FreshRSS/blob/03208771f7d38771f7b9c965b79877d97cce311a/lib/lib_phpQuery.php#L1958-L1962
After:
```
 						$stack[] = $node; 
 			}
			usort($stack, array('phpQueryObject','cmpByLineNo'));
			$this->elements = $stack;
			return $this->newInstance();
		}
```
I could also open a Pull Request, if you want.

**Comment by Alkarex** [comment]
A PR would be nice @printfuck
