### ISSUE TITLE
Access to database is denied with MariaDB

### ISSUE THREAD

**Issue by binalloy** [FreshRSS/FreshRSS#2493]
I am trying to run FreshRSS with MariaDB 10 on my NAS. Everything was fine while the installation until I tried to log in. I got the following error:
```
### Application problem ###
See logs files
```
and the content in `/data/users/username/log.txt`
```
Access to database is denied for `freshrss` (`mysql:host=localhost;dbname=freshrss;charset=utf8mb4;port=3307`)
```
I run the script given in https://github.com/FreshRSS/FreshRSS/issues/1243#issuecomment-244941741, and get the following:
```
PHP version:	7.0.33
MySQL version:	5.5.5-10.3.7-MariaDB
Array
(
    [0] => Array
        (
            [VERSION()] => 10.3.7-MariaDB
        )

)
Array
(
    [0] => Array
        (
            [cs] => utf8
        )

    [1] => Array
        (
            [cs] => utf8mb4
        )

    [2] => Array
        (
            [cs] => utf16
        )

    [3] => Array
        (
            [cs] => utf16le
        )

    [4] => Array
        (
            [cs] => utf32
        )

)
Array
(
    [0] => Array
        (
            [id] => 1
            [name] => Uncategorized
        )

)
```
The connection to the database seems fine. I can't figure out what's wrong.

**Comment by Alkarex** [comment]
Hello,
Hum, I cannot immediately think of what the problem could be.
I have just tested with MariaDB 10.4.7-bionic from https://hub.docker.com/_/mariadb and it seems to work fine.
Do you have a command line to the database? If yes, could you check:
```sql
SHOW grants;
```

**Comment by Alkarex** [comment]
You could also try with SQLite, PostgreSQL, or MySQL

**Comment by binalloy** [comment]
I found that my default setting of MariaDB 10 package is not the same as usual, which is `port: 3307, socket: /run/mysqld/mysqld10.sock`, and that made the trouble. When I tried to log in the database in the command line using `localhost` and port, I got prompt `Can't connect to local MySQL server through socket`. But I could successfully log in with `127.0.0.1` and port. Later after google, I realized that the connection to the database will go through socket when you specify the hostname as `localhost` while through the TCP when specify as `127.0.0.1`.

So there are two options for my case.
- use `127.0.0.1` as hostname
- change the `pdo_mysql.default_socket` to `/run/mysqld/mysqld10.sock` in the PHP configuration.

I tried both and both of them works fine.

The tricky thing is that during the installation, the hostname `localhost:3307` seemed to be solved to `127.0.0.1:3307` before the connection so that the installation was fine, but not after the installation completed.

Anyway, thanks for your hint!

**Comment by Alkarex** [comment]
Thanks for the feedback @binalloy 
I cannot immediately think of what could explain a resolution difference during install and after it. That would require a bit more investigation. In any case, we should try to use the main code during the install process to reduce differences.

**Comment by gpion** [comment]
> * use `127.0.0.1` as hostname

Thanks for the tip!
I was facing the same issue on my NAS after a recent package update (not sure if its was PHP or MariaDB).
Anyway I'm really confused that using "127.0.0.1"  instead of "localhost" can make any difference. Nut the fact *is* that it did!

**Comment by Alkarex** [comment]
This happens when either IPv4 or IPv6 is not correctly set up, or when the database is not listening on IPv4 or IPv6. Everything defaults more and more to IPv6, but there are sometimes elements that are lagging behind.
For the record, the install procedure has been reworked to use the same code than when using FreshRSS https://github.com/FreshRSS/FreshRSS/pull/2522

**Comment by gpion** [comment]
> This happens when either IPv4 or IPv6 is not correctly set up,

I'm using very basic default setup on my NAS regarding network, so I would be surprised this could be the root cause 

> or when the database is not listening on IPv4 or IPv6. Everything defaults more and more to IPv6, but there are sometimes elements that are lagging behind.

Looks like, on my NAS, MariaDB is only listening on IPv4, that could be the explanation:
```
root@fserv:/var/services/web > netstat -tlnp | grep mysql
tcp        0      0 0.0.0.0:3307            0.0.0.0:*               LISTEN      13987/mysqld        
```
> For the record, the install procedure has been reworked to use the same code than when using FreshRSS #2522

I not sure if reinstalling from scratch would be a good idea for me.
Anyway, as long as it is fixed after having edited config.php  with setting '127.0.0.1:3307' for $config['db']['host'] I'm fine.

**Comment by Alkarex** [comment]
No need to reinstall @gpion , the new code would only catch the problem earlier.

**Comment by gpion** [comment]
> No need to reinstall @gpion , the new code would only catch the problem earlier.

No need to reinstall to use the "reworked install procedure" ? Sorry I dont understand.

**Comment by Alkarex** [comment]
I just meant that if your current deployment works, you can just keep it as it is :-)

**Comment by gpion** [comment]
Anyway, I've just found why MariaDB was only listening on IPv4  and not IPv6
I still had Mariadb5 installed (but not running) and it's my.cnf was symlinked in the default place ("/etc/my.cnf") overriding Mariadb10 defaults.
Specifically the "bind-address" setting of the "[mysqld]" section was explicitly set to "0.0.0.0" instead of "*".
After having uninstalled version 5 of MariaDB and restarted vesion 10,  the daemon now listens on IPV6  socket as you can see:
```
$ > netstat -tlnp | grep mysql
tcp6       0      0 :::3307                 :::*                    LISTEN      9576/mysqld         

```
