### ISSUE TITLE
Système d'extension

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#252]
Envisager un système d'extensions simples, permettant d’intercaler des fonctions PHP à certains moments intéressants, comme par exemple :
- avant l'insertion de texte dans la base de données (altération du texte et possibilité de rejeter l'insertion)
- avant affichage (par exemple pour surligner certains mots clefs)
- à l'ajout ou à la lecture des URLs des articles, pour les altérer/nettoyer
  - suppression des xtor et autres utm
  - `/[#?&]{1,3}(xtor=|utm_).*$/i`
  - remplacer les "http://" par des protocoles relatifs "//" pour les images ou les vidéos (iframe) de certains services tels YouTube, DailyMotion, Vimeo, afin que ces ressources soient correctement chargées lorsque FreshRSS est hébergé en HTTPS.

D'une manière générale, pour permettre des choses qui n'ont pas vraiment droit à une place "officielle" dans FreshRSS, par exemple parce que ce n'est pas très propre.

Voir les autres requêtes de cette catégorie https://github.com/marienfressinaud/FreshRSS/issues?labels=Extension

**Comment by marienfressinaud** [comment]
I have created a repository to store all the **official** extensions : https://github.com/FreshRSS/Extensions. Since I will have to maintain these extensions, to be added to this repo, extension source code must follow coding style guidelines.

The first extension is CSSCustom which give a way to overwrite CSS rules for the user. It is very basic but it does the job.

Now I'll merge the extension branch in dev. I still have some work to do on that but major features are here ;).

Please note previous primitive extension system is not compatible anymore.

**Comment by aledeg** [comment]
I've just added an extension to replace my local modifications for reddit feeds. See my comments [here](https://github.com/FreshRSS/FreshRSS/issues/252#issuecomment-29623497) and [here](https://github.com/FreshRSS/FreshRSS/issues/252#issuecomment-65909673).
It's available [here](https://github.com/aledeg/FreshRSS-extensions) if anyone is interested. I've also modified the README page in the official extension repository to add a third-party link to it.

**Comment by aledeg** [comment]
@marienfressinaud Do you remember why this issue is still open and why it is tagged as `documentation`?
Either we should close it or document it then close it. But we need to do something about it!

**Comment by marienfressinaud** [comment]
Because the documentation is still very light, but people seem to be able to create extensions anyway :)
