### ISSUE TITLE
Question about "Archiving" options

### ISSUE THREAD

**Issue by Ribero** [FreshRSS/FreshRSS#2595]
I'm trying to understand some options of the Archiving section of FreshRSS settings. More specifically I'm looking for information about "_Do not automatically refresh more often than_"

The minimum value of this settings seems to be 20minutes. I would like to reduce it at 15 minutes (4 sync per hour). I was searching in config files where the value of this parameter is stored.

I had a look in: `config.default.php` and `config-user.default.php` or `data/config.php` but not sure it is stored here.

Does this setting active / used by FreshRSS ?
How can I reduce it to 15min ?

Thanks !

**Comment by Alkarex** [comment]
Hello, 
The max refresh rate should be located elsewhere than under archiving options. We need to improve that (PR welcome).
Under the settings for individual feeds, you can go down to 15min.
The lowest global/default purposely cannot be set faster than every 20 minutes, to avoid wasting resources and make sure the RSS ecosystem remains sane.
We have regularly seen some sites blocking by IP, or worse, by user agent, due to abuses with too frequent refreshes. 
For faster / near instant updates, I suggest looking into the WebSub protocol (formerly PubSubHubbub), which is supported by FreshRSS. For that to work, your server needs to be routable (visible from Internet), in order to receive callbacks as soon as there is something new. 
I hope this clarifies the situation 🙂

**Comment by Ribero** [comment]
Thanks

> Under the settings for individual feeds, you can go down to 15min.

So the global value which minimum is 20min will be overridden by the one of the feed. A would have prefer to have the global setting to be the one user cannot override. But OK.

> The lowest global/default purposely cannot be set faster than every 20 minutes, to avoid wasting resources and make sure the RSS ecosystem remains sane.

If my cron is refreshing every 15minutes and global is set to 20min do you confirm that all feeds set to 15min will be refreshed ?

> We have regularly seen some sites blocking by IP, or worse, by user agent, due to abuses with too frequent refreshes.

I understand, However I use 15min refresh time for many years with my current Fever server without any issues.

> For faster / near instant updates, I suggest looking into the WebSub protocol (formerly PubSubHubbub), which is supported by FreshRSS. For that to work, your server needs to be routable (visible from Internet), in order to receive callbacks as soon as there is something new.

Unfortunately none of the feeds subscribed have the option selectable... Is there something to do ? (Server is routable)

**Comment by Alkarex** [comment]
> If my cron is refreshing every 15minutes and global is set to 20min do you confirm that all feeds set to 15min will be refreshed ?

Yes, except that if you have a cron and max refresh set exactly to the same value, and since it takes a few seconds to refresh feeds, they might not be included in the next batch of refreshes. The cron job retrieves a list of feeds that need to be refreshed at the beginning of the cron job. So you might want a cron job set to execute more frequently than your max feed refresh frequency.

For WebSub, try first to see if you can get this test feed to work: https://push-pub.appspot.com

**Comment by Ribero** [comment]
> For WebSub, try first to see if you can get this test feed to work: https://push-pub.appspot.com

I can see 20 articles, but option is still not available:

<img width="675" alt="Capture d’écran 2019-10-25 à 19 38 42" src="https://user-images.githubusercontent.com/2266264/67592181-603bdb00-f75f-11e9-88fe-65a078f6b5da.png">

**Comment by Alkarex** [comment]
The checkbox will be automatically enabled when it works (i.e. after you have successfully received the first push message). (The UI could maybe be improved, or at least with a help text)
But I can see you have not tried to write anything on https://push-pub.appspot.com.
Give it a go :-)
If it still does not work, check in `data/config.php` that your `base_url` is correct and `'pubsubhubbub_enabled` is true.
You can also have a look at the log `./data/users/_/log_pshb.txt`

**Comment by Ribero** [comment]
Works fine, very impressive. 
But if I understand how it works, I just have to find compatible feed sources 😄
Right now, all sources I know do not provide WebSub integration yet.

**Comment by Alkarex** [comment]
A few examples of sites with WebSub enabled:

* http://rss.slashdot.org/slashdot/slashdotMain
* http://feeds.arstechnica.com/arstechnica/index
* https://hackaday.com/feed/
* https://feeds.feedburner.com/techcrunch and other feeds served via Feedburner (many)
* https://www.blogger.com/feeds/2471378914199150966/posts/default and other Blogger sites
* WordPress sites hosted on https://wordpress.com or using https://wordpress.org/plugins/pubsubhubbub/
* [Friendica](https://friendi.ca/) instances such as https://f.a80.fr/feed/alkarex/
* Etc.
