### ISSUE TITLE
No update available via web

### ISSUE THREAD

**Issue by fedione** [FreshRSS/FreshRSS#2623]
I'm running FreshRRS 1.14.3. but after checking for new versions there is still no new one available.

![201911020920](https://user-images.githubusercontent.com/55923612/68068130-329ff480-fd52-11e9-8af9-c24e0f68b57d.png)

**Comment by Alkarex** [comment]
Auto-update via ZIP is always a bit delayed (compared to git and Docker). We are working on a new process, but it is also partially on purpose to wait a bit, to ensure quality. Similar approach than e.g. an Ubuntu release and when it becomes available to existing installations.
For instance, a few regressions were just found, which will be fixed in a [fast release 1.15.1](https://github.com/FreshRSS/FreshRSS/milestones/1.15.1).

**Comment by fedione** [comment]
No problem, if it will arrive... one day 😉

**Comment by fedione** [comment]
No problem if it arrives at some point 😉

**Comment by aledeg** [comment]
Can't we attach the zip on the release as an asset and change the location to retrieve the file?

**Comment by Frenzie** [comment]
@aledeg There's already an auto-generated asset; for FreshRSS that's all you need?

**Comment by aledeg** [comment]
@Frenzie I don't really know. I've never read the code for that part. But maybe just the auto-generated asset is enough.

**Comment by Frenzie** [comment]
@aledeg https://github.com/FreshRSS/update.freshrss.org/blob/5ce759a3e9748c6047e0a1d448d5c25131cd6fb7/scripts/update_to_1.14.3.php#L3

**Comment by Alkarex** [comment]
@aledeg There is a GitHub API to do such things, e.g. https://api.github.com/repos/FreshRSS/FreshRSS/releases/latest

**Comment by marienfressinaud** [comment]
It should be OK now, 1.15.1 is available! Let me know if it doesn't work :)

Concerning assets, there is nothing to generate, what @Frenzie points is all we need. What we really want is to finish https://github.com/FreshRSS/FreshRSS/pull/1760 so the update server will no longer be needed :) (I'll do at some point)

**Comment by fedione** [comment]
Works perfect - thanks :)
