### ISSUE TITLE
Redirect to /p/i instead of /i

### ISSUE THREAD

**Issue by jdckr** [FreshRSS/FreshRSS#2624]
Hello,
I just set up my FreshRSS instance using docker. If I access it using `http://<host-ip>:8080` it works fine and I am forwarded to `http://<host-ip>:8080/i/`. When trying to access it via nginx reverse proxy I am forwarded to `http://my-domain.com/p/i` which results in **requested url not found**. When I directly access `http://my-domain.com/i` there's no problem.
I encountered the same problem when trying to set it up without docker.

What am I doing wrong?

**Comment by jdckr** [comment]
When using https instead of http it works.

**Comment by Alkarex** [comment]
Hello,
First, I would suggest using a dedicated reverse proxy such as Traefik instead of nginx (easier, faster, more robust, less error-prone). See https://github.com/FreshRSS/FreshRSS/blob/dev/Docker/README.md

You might have a cache problem in your browser. Try to clear it and/or with another browser.

Otherwise, please show your nginx config file.

**Comment by jdckr** [comment]
Clearing the browser cache fixed the problem. Ty!
