### ISSUE TITLE
Share by email doesnt open in new tab in Firefox

### ISSUE THREAD

**Issue by Fake4d** [FreshRSS/FreshRSS#2666]
I share a lot of articles by email and really hate the behaviour that sharing an email doesnt open in a new tab in Firefox.

I found this Firefox Bug which is open quite a long time..:
https://bugzilla.mozilla.org/show_bug.cgi?id=646552

I tried to code the suggestion from the last comment in FreshRSS but didnt get a good solution:
https://bugzilla.mozilla.org/show_bug.cgi?id=646552#c28

Maybe there is a workaround (maybe sharing per Email with Firefox ;-) - otherwise we could close this issue and I have to wait until Firefox fixes this behaviour! 

Thank you in advance!

**Comment by Fake4d** [comment]
Relevant code in following file: https://github.com/FreshRSS/FreshRSS/blob/master/app/shares.php

**Comment by Frenzie** [comment]
> I found this Firefox Bug which is open quite a long time..:
https://bugzilla.mozilla.org/show_bug.cgi?id=646552

I don't think target=_blank is the issue really; in effect target=_blank is *already* a workaround for the actual issue.

> I tried to code the suggestion from the last comment in FreshRSS but didnt get a good solution:

What exactly did you try? ;-)

**Comment by Fake4d** [comment]
I tried to fix around some javascript:

`window.open('mailto:`

I found another website by googleing the firefox bug where someone suggests something like this:

`<a onclick="javascript:window.open('mailto:mail@domain.com','mail');event.preventDefault()" href="mailto:mail@domain.com">`

This example is working on my firefox and opens Gmail in a new tab!

**Comment by math-GH** [comment]
Is this issue still actual? 
For me (Firefox 95, Windows 10) works fine. It opens my mail app (Mozilla Thunderbird).

**Comment by Frenzie** [comment]
It's still current. It makes no difference when using a native client, but when selecting a webmail client as your default mailto handler, it browses away from the tab. I forgot about it but given that it's not being fixed we should also add an onclick=window.open or some such.

**Comment by Frenzie** [comment]
Open about:preferences, search for mail, set it to GMail or Yahoo Mail to see the effect. (You can also add your own with `navigator.registerProtocolHandler()`, but I'm not sure if there's an easy GUI way to do that.)

Edit: but anyway, hence why I said target=_blank is itself already the workaround since I'm not convinced the mailto behavior makes much sense. But it is what it is.

**Comment by math-GH** [comment]
I do not understand the issue. When I click on a mailto link, than the mail app opens. FreshRSS keeps unchanged.

Why does @Fake4d need that mailto opens in a new tab?
As I know it is up to the user/browser settings how to handle mailto links

**Comment by Frenzie** [comment]
Any website can be a mailto handler, not just dedicated software on your own PC. If a website is selected as the mailto handler, it's not opened in a new tab.

**Comment by math-GH** [comment]
"Only" Firefox is affected, when using a web mailer.
Firefox + dedicated mail app is not affected.
Is any other browser affected?

**Comment by Frenzie** [comment]
At the very least Chromia honor `_blank` on `mailto:` links, so affected or not the basic workaround works.

See `https://github.com/whatwg/html/issues/5289` for discussion.

**Comment by math-GH** [comment]
@Fake4d @Frenzie Could you please check 1.20? The `mailto` link has a `target="blank"`

**Comment by Frenzie** [comment]
Nothing has changed.

**Comment by Frenzie** [comment]
Since Firefox doesn't seem to be interested in closing their bug, if someone wants to work on this they might add an onclick attribute in sharing.

https://github.com/FreshRSS/FreshRSS/blob/442019a0548d3f1d888419930d38f1986e5cd773/app/shares.php#L58-L63

That'd also need some work in https://github.com/FreshRSS/FreshRSS/blob/442019a0548d3f1d888419930d38f1986e5cd773/app/Models/Share.php and the template.

And then it could simply look something like:

```php
 	'onclick' => 'javascript:window.open(this.href); return false;',
```

Alternatively, since it's something like a `.item.share [type="email"]` it could make sense to do something similar entirely client-side.

Of course the user can also just middle click or shift + click, and presumably there's a Firefox extension for it as well.

I suppose I'll leave it at PRs welcome. ;-)

**Comment by Fake4d** [comment]
> @Fake4d @Frenzie Could you please check 1.20? The `mailto` link has a `target="blank"`

I checked and as @Frenzie I didnt see any difference... Sorry for that..
