### ISSUE TITLE
unable to login: what is the password policy ?

### ISSUE THREAD

**Issue by JOduMonT** [FreshRSS/FreshRSS#2791]
I read about this issue but still unable to figure it out
- https://github.com/FreshRSS/FreshRSS/issues/1224
- ...

## Technical info
- run with docker **freshrss/freshrss** ( ⓘ Your current version of FreshRSS is 1.15.4-dev. )
- db linuxserver/mariadb (the installation create 6 tables)
- proxy linuxserver/letsencrypt ([config](https://github.com/linuxserver/reverse-proxy-confs/blob/master/freshrss.subdomain.conf.sample))

## What I tried
The only way I'm able to login is when I put
`'auth_type' => 'none',`

but then even if I cut and past a simple **alphanumeric 16 characters password** and put back `'auth_type' => 'form',` it is not working

## base on the log
````
2020-02-05 09:55:39Password mismatch for user=rss, nonce=, c=
2020-02-05 09:49:36Password mismatch for user=rss, nonce=, c=
2020-02-05 09:49:28Password mismatch for user=rss, nonce=, c=
````

**Comment by JOduMonT** [comment]
should I have more than this ?
![image](https://user-images.githubusercontent.com/5204724/73807481-3040b100-47ff-11ea-9f54-d33ae7c32b68.png)

**Comment by marienfressinaud** [comment]
Hi @JOduMonT, the password policy is explicit: at least 7 characters. Your problem is probably not related to your password but to some configuration. `nonce` and `c` parameters are empty which is not good. Have you some browser extensions that would block JavaScript? Did you try with a different browser?

Edit: don't worry about your DB, it looks fine and users are not saved here but on disk, in the `data/users/` folder.

**Comment by JOduMonT** [comment]
I'll close the issue but keep in mind your suggestion for the next time I try
thank for your time
