### ISSUE TITLE
[GReader API] feed ids provided by 'unread-count' do not follow the standard

### ISSUE THREAD

**Issue by barijaona** [FreshRSS/FreshRSS#2834]
I am currently trying to improve the strategy used by Vienna-RSS to fetch feeds (something similar but not identical to the one suggested at #2566)

I use the '`unread-count`' request. I notice that responses provided by FreshRSS are quite different from responses given by other servers.

According to :
https://ranchero.com/downloads/GoogleReaderAPI-2009.pdf
and https://feedhq.readthedocs.io/en/latest/api/reference.html#unread-count
feed IDs are expected to refer to feed's URL and should look like `feed/http://www.engadget.com/rss.xml`

Instead of that, FreshRSS provides a numerical reference like `feed/8`

I think I can get around the problem (I will have to memorize feed IDs provided by FreshRSS), but I suggest you reconsider this implementation.

**Comment by Frenzie** [comment]
When it changes to `https://www.engadget.com/rss.xml` because of the 301 moved permanently, does that mean you've now got a double? Alternatively `http://www.engadget.com/rss.xml` is just a really long and profoundly misleading way of saying the same thing as `8` (i.e., it's just an identifier without inherent meaning).

So frankly, that sounds like a really bad idea. But @Alkarex knows significantly more about the practical side of this.

**Comment by Alkarex** [comment]
Hello @barijaona ,
Thanks for the feedback. Always welcome.
`unread-count` is not the only call affected; there is also `subscription/list`.
What I believe is important is to be consistent, so that all the calls are using the same IDs.
I do not think that the documentation states that one can rely on the IDs to infer the feed URL, does it?
Is it something you rely on in your implementation?
For the same reasons than what @Frenzie wrote, I would rather not change the ID to be more than "just an ID" (with some meaningful prefixes, though), if we can avoid it. Let me know :-)

**Comment by Alkarex** [comment]
@barijaona Just FYI, I have just made a slightly related patch https://github.com/FreshRSS/FreshRSS/pull/2840
