### ISSUE TITLE
ⓘ Reload articles and fetch complete content - HTTP ERROR 500

### ISSUE THREAD

**Issue by infominer33** [FreshRSS/FreshRSS#2923]
I'm trying out selectors to pull truncated content, but I can't really tell if I'm doing it right.

I'm trying to get the complete comment thread from github issues using maybe `discussion_bucket` or `js-discussion`

no matter what I enter, if I click the eye next to that, I just get a blank popout window.. then if I go to the bottom of the page and click "Reload articles" I get http error 500.

any insight would be appreciated
thank you.

**Comment by Frenzie** [comment]
As a quick aside, that'd be `#discussion_bucket`(`#` for id) and `.js-discussion` (`.` for class).

I don't think using a "wrong" selector should result in anything other than nothing though. That'll have to be investigated, but it's a bit late over here. :-)

**Comment by infominer33** [comment]
Brilliant! `.js-discussion` for the win! I figured this out by importing the opml to a different account and setting the selector before actualizing :) Though I see now I could have simply deleted the articles and re-actualized.

Anyhow, I can confirm the selector works, but preview and reload do not. 

(Any chance there is a way to set selector for an entire category at once, perhaps by command-line?)

**Comment by Leepic** [comment]
I've the same error on FreshRSS 1.16.1-dev but with the right HTML selector. My example is https://www.fdn.fr/feed/ with #wrapper 

If I click on preview or "Reload articles" the HTTP 500 error appears with this in my apache logs:

`
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function execute() on bool in /var/www/html/FreshRSS/app/Models/FeedDAO.php:266\nStack trace:\n#0 /var/www/html/FreshRSS/app/Models/Entry.php(116): FreshRSS_FeedDAO->searchById(340)\n#1 /var/www/html/FreshRSS/app/Controllers/feedController.php(770): FreshRSS_Entry->feed(true)\n#2 /var/www/html/FreshRSS/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->contentSelectorPreviewAction()\n#3 /var/www/html/FreshRSS/lib/Minz/Dispatcher.php(47): Minz_Dispatcher->launchAction('contentSelector...')\n#4 /var/www/html/FreshRSS/lib/Minz/FrontController.php(84): Minz_Dispatcher->run()\n#5 /var/www/html/FreshRSS/p/i/index.php(48): Minz_FrontController->run()\n#6 {main}\n  thrown in /var/www/html/FreshRSS/app/Models/FeedDAO.php on line 266'
`

The requests: 

* "Reload articles"
 https://www.example.com/FreshRSS/p/i/?c=feed&a=reload&id=340

* "preview"
 https://www.example.com/FreshRSS/p/i/?c=feed&a=contentSelectorPreview&id=340&selector=%23wrapper

The workaround is to delete all articles in the corresponding feed and reload articles. The error is still present (HTTP 500) but the feed is correctly refresh with the selector.

Note that this issue is not specific to news feeds, adding a selector to an old feed cause the same error.

**Comment by Alkarex** [comment]
I cannot reproduce the error. Could one of you try again with the current master branch, and provide a few more details about the setup (database, platform...)?

**Comment by Leepic** [comment]
The problem still persist with FreshRSS 1.16.1-dev. I've used the same feed describe above.
Note that the workaround seem to doesn't works now.

The apache error log:

`[proxy_fcgi:error] [pid 25337] [client hidden] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function execute() on bool in /var/www/html/FreshRSS/app/Models/FeedDAO.php:266\nStack trace:\n#0 /var/www/html/FreshRSS/app/Models/Entry.php(116): FreshRSS_FeedDAO->searchById(341)\n#1 /var/www/html/FreshRSS/app/Controllers/feedController.php(768): FreshRSS_Entry->feed(true)\n#2 /var/www/html/FreshRSS/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->contentSelectorPreviewAction()\n#3 /var/www/html/FreshRSS/lib/Minz/Dispatcher.php(47): Minz_Dispatcher->launchAction('contentSelector...')\n#4 /var/www/html/FreshRSS/lib/Minz/FrontController.php(84): Minz_Dispatcher->run()\n#5 /var/www/html/FreshRSS/p/i/index.php(48): Minz_FrontController->run()\n#6 {main}\n  thrown in /var/www/html/FreshRSS/app/Models/FeedDAO.php on line 266'`

My setup:

- Debian 10.1 Buster amd64 on an OVH VPS
- Apache 2.4.38 with proxy_fcgi 2.3.9
-  PHP 7.3.14 with PHP-FPM
- MariaDB 10.3.17

If useful I can install FreshRSS and import my data on another server, or if you want more informations, test something, don't hesitate to tell me.

**Comment by Alkarex** [comment]
Ok, I could reproduce with MariaDB. Please try this fix https://github.com/FreshRSS/FreshRSS/pull/2993
