### ISSUE TITLE
actualizer logs non-error messages to stderr

### ISSUE THREAD

**Issue by candrews** [FreshRSS/FreshRSS#2975]
https://github.com/FreshRSS/FreshRSS/pull/2964 caused a change in actualizer behavior regarding logging.

actualizer used to write informational, non-error messages to stdout. Now it writes this to stderr.

These outputs:
`FreshRSS starts feeds actualization at...`
`FreshRSS actualize <user>`
`FreshRSS actualization done for...`
are all informative so they should go to stdout, not stderr.

Using stdout vs stderr is important because systems like cron will alert root if a scheduled job logs output to stderr.

**Comment by Alkarex** [comment]
Thanks for testing /master, @candrews 👍 
You are right, I am reverting. Please see https://github.com/FreshRSS/FreshRSS/pull/2979

It is actually unfortunate that some cron jobs by default are testing stderr instead of testing exit code.
In our other CLI scripts, STDOUT is used for data, STDERR for various diagnostic messages.
See (e.g. for a suggestion of code to check exit code):
* https://github.com/FreshRSS/FreshRSS/blob/master/cli/README.md#note-about-cron
* https://github.com/FreshRSS/FreshRSS/issues/2452#issuecomment-513720548

https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout
> stderr is also the place where you print stuff like help docs when an invalid argument is passed to a command. In this case its help docs should be printed, but not be passed on to the next program.
