### ISSUE TITLE
Can't add Windows Blog feed

### ISSUE THREAD

**Issue by myuki** [FreshRSS/FreshRSS#2984]
## URL:

<https://blogs.windows.com/insider/feed/atom/>

## Log
```
2020-05-18 10:48:50 cURL error 35: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure [https://blogs.windows.com/feed/atom/]
2020-05-18 10:41:37 Unknown error for feed [https://blogs.windows.com/feed/atom/]
2020-05-18 10:33:41 Unknown error for feed [https://blogs.windows.com/feed/atom/]
2020-05-18 10:33:31 cURL error 35: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure [https://blogs.windows.com/feed/atom/]
```

**Comment by Alkarex** [comment]
It should be that one https://blogs.windows.com/feed/ because your URL points to an empty feed.

But it has some TLS issues, not related to FreshRSS:
https://validator.w3.org/feed/check.cgi?url=https://blogs.windows.com/insider/feed/

```
curl -v 'https://blogs.windows.com/insider/feed/'
*   Trying 198.61.151.140:443...
* TCP_NODELAY set
* Connected to blogs.windows.com (198.61.151.140) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

https://www.ssllabs.com/ssltest/analyze.html?d=blogs.windows.com

![image](https://user-images.githubusercontent.com/1008324/82235574-27e62f00-9933-11ea-9c7c-b2f147948efd.png)

**Comment by Alkarex** [comment]
I do not even have any quick workaround to propose, at it would require making a little bridge/proxy that supports the TLS requirements of that site. If `curl` does not work from your server, FreshRSS cannot work either.
