### ISSUE TITLE
Unable to connect my FreshRSS instance with the Freshrss App

### ISSUE THREAD

**Issue by Wasabules** [FreshRSS/FreshRSS#3059]
Hi,
My FreshRSS api link is "https://rss.geoffrey-lecoq.fr/api/greader.php"
but when i put it on the app i have an "This URL is not correct" message.

I have try "rss.geoffrey-lecoq.fr" and "rss.geoffrey-lecoq.fr/api" and "https://rss.geoffrey-lecoq.fr/api/" etc...
No one work, can you help me ?
Thanks and great job !

**Comment by Alkarex** [comment]
Please tell a bit about your system (FreshRSS version, type of installation, OS, Web server, ...)

Please check https://rss.geoffrey-lecoq.fr/api/ in your Web browser and fix any warning.

You might also have some logs in `./FreshRSS/data/users/_/log_api.txt` or for your Web server.

Then, try to trouble-shoot either manually or with another app to find out whether the problems lies server side or client side

* Manually with curl, see the requests at the bottom of:
https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html

* Other apps:
https://github.com/FreshRSS/FreshRSS/#apis--native-apps

If the problem is with the app, please report issues on
https://git.feneas.org/christophehenry/freshrss-android

**Comment by Wasabules** [comment]
Je pense qu'il est mieux de parler en français!
Du-coup j'ai réglé le souci mais peut importe l'application où je me rend je n'ai pas possibilité.
Avec l'app "Readrops" j'ai une erreur 400 par exemple.
Alors que j'ai renseigné "https://rss.geoffrey-lecoq.fr/api/greader.php" et j'ai mis le mot de passe et l'identifiant de mon compte

**Comment by Alkarex** [comment]
* Qu'avez-vous dans vos logs, par exemple `./FreshRSS/data/users/_/log_api.txt` ?
* Quelle version de FreshRSS, installation, OS, serveur Web...

Si vous voulez, vous pouvez m'envoyer un compte temporaire de test

**Comment by Wasabules** [comment]
Le fichier n'est pas généré, il n'y a pas de "log_api.txt"
Et il s'agit de la version " 1.16.3-dev"

Voici un utilisateur :
test
6^ozHf$wv9M#6o

Pour ce qui est des infos de PHP & cie, tout est là : https://www.geoffrey-lecoq.fr/

**Comment by Alkarex** [comment]
@Wasabules Cela semble marcher très bien :-)

```
curl -v 'https://rss.geoffrey-lecoq.fr/api/greader.php/accounts/ClientLogin?Email=test&Passwd=testtest'

curl -s -H "Authorization:GoogleLogin auth=test/bfc1563d6a0f5e1104ac51d85ba819eb8d624f13" 'https://rss.geoffrey-lecoq.fr/api/greader.php/reader/api/0/subscription/list?output=json'
```

Testé avec Readrops sans problème (Readrops ajoute lui-même la fin de l'adresse, du coup il faut utiliser https://rss.geoffrey-lecoq.fr/ )

**Comment by Alkarex** [comment]
Attention de bien penser à mettre un mot de passe API
![image](https://user-images.githubusercontent.com/1008324/84665289-f5265b00-af1f-11ea-9c3c-a867ca89070c.png)

**Comment by Alkarex** [comment]
![Screenshot_20200615-155112_Readrops](https://user-images.githubusercontent.com/1008324/84665736-7aaa0b00-af20-11ea-8d74-96c4e0965885.jpg)

**Comment by Wasabules** [comment]
ça vient peut-être de mes mot de passe à rallonge générer avec Bitwarden et les 40 caractères

**Comment by Alkarex** [comment]
Je viens de tester avec l'application de Christophe Henry (*FreshRSS for Android*) et cela marche aussi.
Vous pouvez effacer le compte

**Comment by Alkarex** [comment]
Si vous trouvez un mot de passe qui ne fonctionne pas, merci d'ouvrir un autre ticket à ce sujet
