### ISSUE TITLE
Prompt to open grey.gif

### ISSUE THREAD

**Issue by dmusican** [FreshRSS/FreshRSS#3080]
Whenever I navigate to my local FreshRSS installation, I'm prompted to open the file gray.gif, which looks to me to be a one-pixel file. I can just cancel the browser pop-up to open the file, but it happens again sometimes when I switch to another feed. Any idea what's going on here?

**Comment by SuperSandro2000** [comment]
Sounds to me like the mime type might be wrong.

**Comment by hanshafner** [comment]
I have the same issue. It started out of the blue, although I have FreshRSS set to auto-update (I think...)

But more to the point: what do we have to change where for the correct MIME type...

**Comment by Frenzie** [comment]
Normally that would be the webserver.

**Comment by hanshafner** [comment]
I've checked the webserver and nginx.conf has the line 

include /etc/nginx/mime.types

and the file mime.types has the line:

types {
...
image/gif    gif;
...
}

So where else could this unwanted gif-download-behaviour be mistriggered?

**Comment by Frenzie** [comment]
Did you check what the headers are?

```
$ curl -I https://some.url/themes/icons/grey.gif
HTTP/1.1 200 OK
Date: Tue, 30 Jun 2020 10:02:20 GMT
Server: Apache/2.4.25 (Debian)
Upgrade: h2,h2c
Connection: Upgrade
Last-Modified: Sun, 31 May 2020 21:07:25 GMT
ETag: "38-5a6f810acd92c"
Accept-Ranges: bytes
Content-Length: 56
Content-Type: image/gif
```

**Comment by hanshafner** [comment]
Thank you helping me through this.

  The headers returned are:
  HTTP/1.1 200 OK
  Content-Type: application/octet-stream
  Accept-Ranges: bytes
  Content-Length: 56
  Date: Tue, 30 Jun 2020 14:43:59 GMT
  Server: lighttpd/1.4.53

Content-Type seems to be wrong (should be image/gif) and it seems FreshRSS isn't served through nginx that FreshRSS installed, but through lighttpd that came with pihole which is running on the same machine.

That's very confusing to me being the amateur server admin.

**Comment by Frenzie** [comment]
Only one server socket can listen to a particular port. I don't know anything about pihole, but regardless if it's nginx or lighttps you'd expect image/gif to be the standard mimetype for `.gif` files so I'm somewhat confused either way.

If lighttpd is required for some webpage-based configuration, it shouldn't be too hard to run it on a different port? (Or vice versa, but I'd assume you wouldn't want to access the config on a daily basis like you might newsfeeds.)

**Comment by hanshafner** [comment]
Thank you for sending me on the right track.

Long story for the fix:
Yes, normally lighttpd does run on another port and whenever I upgrade pihole, I see that lighttpd resets to port 80 and then doesn't start, because nginx uses that one.
I had left off a ";" in nginx config that prevented nginx from starting and I never figured out why, because freshrss was still running (being served by lighttpd now...).
So after fixing the ";" I saw that I had to move lighttpd to its (on my setup) regular port.

Then both nginx and lighttpd worked again and the .gif download went away. 

Again, thank you for taking the time and pointing me in the right direction!

As to why lighttpd handled the .gif differently... I don't know and I'm not going to try to find out. Unless the problem returns...

**Comment by dmusican** [comment]
Thanks: the problem was due to mime type settings; I'm also using pihole and lighttpd. Problem was solved by adding gif to the mime types in /etc/lighttpd/lighttpd.conf.

**Comment by Alkarex** [comment]
@dmusican Is PNG correctly defined in `lighttpd.conf` ? If yes, we could upgrade that file to PNG

**Comment by Alkarex** [comment]
Ah, nevermind, we also have a few different `loader.gif` anyway
