### ISSUE TITLE
What does get cached? (Hosting company found virus in cache)

### ISSUE THREAD

**Issue by qx54** [FreshRSS/FreshRSS#3150]
What data does FreshRSS cache?

The virus scanner of my hosting company found a virus in the cache, file path:
/data/cache/50aadece0d17b6b340acec289acdddf0.spc

They auto-locked the file and also auto-changed my FTP credentials.

How can I prevent this from happen again?

Thanks

**Comment by SuperSandro2000** [comment]
First, you should use SFTP instead of FTP.

I took a very quick look and the files look like they contain cached feed content of some sort.

So you should probably unsubscribe from some dubio feed, change your credentials for everything on that machine and make sure you are the latest release of FreshRSS and php.

Also you might wanna change your hoster to one that does not snoob into your files.

**Comment by Alkarex** [comment]
Hello @qx54 
Do you have a copy of the problematic file?
Those cache files contain a copy of the downloaded RSS files. They do not contain any code.
Who changed your credentials? Your hosting company?
If they, the most likely explanation is a false positive.

**Comment by qx54** [comment]
Hi @Alkarex 

Thanks for the information. The feed in question is about IT security and contains posts where the code of exploits gets discussed. I guess this triggered the virus scanner.

Yes, the virus scanner of the hosting company  auto-changed my FTP credentials as a security measure.

Is there a way to exclude a feed from the cache?

**Comment by Alkarex** [comment]
So most likely a false positive indeed, which needs to be fixed on you hosting company side. No, it is not possible to disable caching completely at the moment. However, it might be possible for you to exclude some directories from virus scanning.
