### ISSUE TITLE
How do you COMPRESS the content and UNCOMPRESS it?

### ISSUE THREAD

**Issue by coolbq** [FreshRSS/FreshRSS#3234]
Hi Alkarex, could you please show me how you COMPRESS and UNCOMPRESS the content field to content_bin field in the Entry?
And how do you calculate the hash field in the Entry table?

I'm thinking of publishing feed items directly to FreshRSS entry table for my personal use, I checked your sources but still didn't get how do you do with the content_bin and hash fields. Hope you could show me some details about it.

Thanks in advance. and hope you a good day!

**Comment by Alkarex** [comment]
Hello,
Only the MySQL database has compressed content_bin (not SQLite nor PostgreSQL). I am actually planning for an option not to compress our MySQL.

See https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_uncompress

https://github.com/FreshRSS/FreshRSS/blob/e0b80e82e2d32d7e2827587df502360a2d4b9e14/app/Models/Entry.php#L133-L139

But consider making an extension using existing PHP model/controller functions if possible, instead of targetting the database directly, which might change structure.
