### ISSUE TITLE
Sharing to Pocket Assistance

### ISSUE THREAD

**Issue by quella** [FreshRSS/FreshRSS#3254]
I have been using FreshRSS for a few months now and thank you for all the work people have done to get it this far.  Enjoy seeing the continued innovation and work on the project.  

I searched and also read through many other issues but could not locate an answer the my issue with integrating Pocket into the sharing menu.  I am currently running the latest development build from Git using the "Update" option.  I see the below which says "Not Available" once I select "Pocket" and click on the + next to it.  Does this option require Pocket to be installed and operational on the hosting machine (Raspberry Pi) or should I be receiving an OAuth connection in the FreshRSS web interface?  I'm not given any options that I can see.  I did see others had some issues relating to AdBlockers being enabled. However, I have them disabled for this web access via the Chrome browser.

Any direction or assistance would be welcomed.  Not a rush, a nice to have.  

![Screen Shot 2020-11-12 at 9 02 36 PM](https://user-images.githubusercontent.com/823352/99019829-3b153880-252b-11eb-8b44-e6f3eab24ad7.png)

**Comment by Frenzie** [comment]
Not available is definitely awkward there. It's clear if you add something else next to it.

![Screenshot_2020-11-13_10-39-25](https://user-images.githubusercontent.com/202757/99057789-8d427200-259c-11eb-8c90-72b6defaa0ef.png)

It means configuring your own Pocket server URL isn't available since you can't run your own. There's a share option that'll open a URL like `https://getpocket.com/save?url=https%3A%2F%2Fwww.neerlandistiek.nl%2F2020%2F11%2Fregionale-voornamen-gelderland-en-utrecht%2F&title=Regionale%20voornamen%3A%20Gelderland%20en%20Utrecht%20%C2%B7%20Neerlandistiek`, where the `url=` part is the permalink to the article you're reading.

**Comment by quella** [comment]
OK, thanks for the direction and ideas.  It seems that Sharing does work when I added pocket and ignored the "Not Available" notice when I clicked on the +.  Once I saved the changes, I can now see the ability to share (Normal View) and when I select the option, a new browser window appears and I can see it is saved to pocket.  

One last question that I'm confused from a UI perspective.  The "Share" option only seems to appear when using the **Normal** view and not the **Reading** view (scrolling) which I have been using from the start.  Is there a reason this is only showing in a single view and not the others?  Additionally, it seems that I cannot put the Sharing option at the top of the article (no matter the view), the option in the display setting is greyed out and I have tried various combinations to get it on top; which seems to also be the case with tags.  

Am I missing something here?

**Comment by Frenzie** [comment]
That's probably more a question for @marienfressinaud or @Alkarex.

**Comment by marienfressinaud** [comment]
Indeed, the reading view was designed to offer less options in order to focus on reading. It was intended to not show the "share" option in this view. However, I agree it's a bit confusing. If I had to redesign the interface, the 3 different views would definitely be different!

A solution for you could be to use the "normal" view by default, and check the "Show articles unfolded by default" option (Configuration > Reading).

It's not possible to have the Sharing option at the top of the article, however you can use the shortcuts to share quickly. First you can open the Sharing popup hitting the `s` key, then `1` (or `2`, or `3`… depending on which option you want to use)

**Comment by quella** [comment]
@marienfressinaud Thank you for the great tool and follow-up.  I believe it was more how I was using the tool based on other readers and was a bit confused at first.  I now understand the reasoning and options.  Lately I have been using the Normal View and "J" for moving forward through my unread items.  I have a few feeds that contain images (cartoons, etc) and are not really something to be read, but I save them for later viewing.  However, there have been times I have been in the reading mode (previously) and wanted to share something I was seeing with a coworker via Pocket.  It did not seem normal to not have the same options in the reading view from the normal view.  Again, not a complaint as I really like what the team has done with the tool.  Again, thank you for the extra info as a follow-up.
