### ISSUE TITLE
Per feed proxy configuration

### ISSUE THREAD

**Issue by hharsunen** [FreshRSS/FreshRSS#3271]
I've seen #675
Is there a way to make just single feed to use proxy or two or more feeds to use separate proxy configuration each?

**Comment by printfuck** [comment]
Yes, you can. I am doing it with a small extension:
```
class WpGdprExtension extends Minz_Extension {
	public function init() {
		$this->registerHook('simplepie_before_init', array('WpGdprExtension', 'curlHook'));
	}

	public static function curlHook($simplePie, $feed) {
		
		if (preg_match('#^https?://[a-zA-Z]*.washingtonpost.com/#i', $feed->url())) {
			$simplePie->set_curl_options(array(CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5,CURLOPT_PROXY => "192.168.5.27:1081"));
		}
...
```

It works **just** for fetching the article, and **not** for fetching the content with css filters.

You can find the full examplary extension over [here](https://git.eris.cc/a3x/example-proxy). (It's just the Tumblr extension, slightly modified)

**Comment by hharsunen** [comment]
Thanks for that. I think I'll just do multiple instances instead as content would need to be proxied too.

**Comment by printfuck** [comment]
I've built something. On my [Branch](https://github.com/FreshRSS/FreshRSS/compare/master...printfuck:curl_params) I added an option, that will work for fetching the feed *and* the content via CSS filters. You can add the following options:

- CURLOPT_PROXYTYPE
- CURLOPT_COOKIE
- CURLOPT_PROXY

The list can easily be edited for adding or removing options for either content-fetching or feed-fetching. This is still WIP - I also have a version, where parsing is completely done in `subscriptionController.php`. For now it looks like this:

![Example](https://user-images.githubusercontent.com/36680203/104229993-fb7ba780-541a-11eb-9e43-a17732968931.PNG)

The proxy feature has an obvious purpose, since I'm fetching feeds from 200 different sites around the world and some have blacklisted my hoster's ip range. 

The cookie feature helps in fetching content (with CSS-filters) from sites like https://golem.de or https://spiegel.de, which set GDPR-cookie-consent-bullshit cookies, when you visit them the first time. 

You may test it at my instance https://rss.eris.cc

**Comment by Alkarex** [comment]
@printfuck That looks like a good start. I would welcome a PR if you can, but with one UI field per cURL option, otherwise I am afraid it will be too difficult to use for many users

**Comment by printfuck** [comment]
[It's](https://github.com/FreshRSS/FreshRSS/compare/master...printfuck:curl_params) updated now. Now the UI looks nice, but the code is bloated 😅
![proxy](https://user-images.githubusercontent.com/36680203/104507342-9491f600-55b4-11eb-9dae-d7bbf817a6c0.PNG)
It's using the i18n translations, but I could only give german and english translations.

**Comment by Alkarex** [comment]
@printfuck Looks good, please send a PR so we can iterate on the code
