### ISSUE TITLE
Google Reader API implementation for streaming content lacks canonical field and requires streamId

### ISSUE THREAD

**Issue by yang991178** [FreshRSS/FreshRSS#3389]
For example, the following is an excerpt from another unofficial Google Reader API documentation
``` js
{
    published: 1234567890,
    updated: 1234567890,
    // This field is returned by the FreshRSS API
    alternate: [{
        href: "http://item.url.here",
        type: "text/html"
    }],
    // but not this field
    canonical: [{
        href: "http://item.url.here"
    }],
    ...other
}
```

Another particularity about FreshRSS's implementation is that it requires the streamId of "reading-list" when streaming all articles. I think this is related to a recent PR (#3320) but is another edge case where "&s" is also not set.

For example: ``` /reader/api/0/stream/contents/reading-list?output=json&n=250 ``` would work. 
But ``` /reader/api/0/stream/contents?output=json&n=250 ``` would result in a HTTP 400 error.

*P.S.* Since there's no official Google Reader API documentation, all of the existing Reader API implementations in the market are more or less approximations. As such, I think this is really more of a feature request rather than a bug ticket.

**Comment by Alkarex** [comment]
Will do. For which client is that?

**Comment by yang991178** [comment]
> Will do. For which client is that?

https://github.com/yang991178/fluent-reader and https://github.com/yang991178/fluent-reader-lite

The second one is still work-in-progress though

**Comment by Alkarex** [comment]
@yang991178 Fixed in https://github.com/FreshRSS/FreshRSS/pull/3391 Please have a look

I am glad to hear that Fluent-reader is adding some Google Reader API support to interact with FreshRSS. Last time I tried it it was only through the more limited Fever API. Let us know the status, so I can try again and update our table of clients:

https://github.com/FreshRSS/FreshRSS/blob/master/README.md#apis--native-apps
