### ISSUE TITLE
Cannot login with Readrops client (404 Bad request)

### ISSUE THREAD

**Issue by 360fun** [FreshRSS/FreshRSS#3396]
Hi, I love FreshRSS but I cannot login with the Readrops client. 😰

I'm waiting the reply from the dev but maybe you also have some clues on how to solve the problem:
https://github.com/readrops/Readrops/issues/98

Thanks 🙏

**Comment by Alkarex** [comment]
Hello,
Which address are you typing in Readrops?

For that app, try to type just the root URL of your FreshRSS instance, like `https://freshrss.example.net` or `https://example.net/FreshRSS/` without the API path.

Did you check the automatic test of your API? `https://freshrss.example.net/api/`

**Comment by 360fun** [comment]
It works!!! 🥳 super super thank you! 🙏 
somebody should write this somewhere because it's not obvious...in most clients you must put the gReader url 🙄

**Comment by aledeg** [comment]
@360fun Documentation PR welcomed!

**Comment by aledeg** [comment]
Or at least, could you describe the step by step process you've followed. Thank you

**Comment by 360fun** [comment]
After @Alkarex suggestion is very easy:

**ADD A FRESHRSS ACCOUNT ON READROPS**
Account name: _Whaterver You Like_ (default is "FreshRSS")
Account url: _root URL of your FreshRSS instance_ (ex. https://freshrss.example.net or https://example.net/FreshRSS/ without the API path)
Login: _username_
Password: _API password_ (not the account password!)

Hope this is enough! 🙏

**Comment by 360fun** [comment]
PS
If I can make a suggestion, allow both ways: with and without the full API path. So the user cannot make mistakes! ;)

**Comment by zolointo** [comment]
Thank you! I used part of this to solve my authentication issue, but wanted to make a documentation addition:

For this to work, you need to 1) set an API password for the account and 2) Allow API access

Quick instructions
**1. Set an API Password**
- login to FreshRSS on your browser
- navigate to your Profile page: Gear icon in upper-right -> **Profile**
- navigate to the bottom of this screen to the **API management** section
- type in your desired API password into the **API password** box
- click Submit

Once you do this, the API password will be recorded to your profile. **However**, the API password box will always be blank. This is what threw me, as I thought there was a FreshRSS error which was losing my password every time I clicked Submit. 

It is just a way to type in and submit a password. Just because it is blank doesn't mean there isn't an API password present.

2. Allow API Access
- login to FreshRSS on your browser
- navigate to the Authentication page: Gear icon in upper-right -> **Authentication**
- click the box next to **Allow API Access**
- click Submit
