### ISSUE TITLE
how do I create myself theme

### ISSUE THREAD

**Issue by zimocode** [FreshRSS/FreshRSS#3406]
The default theme is nice, but I want to create myself thems. 
Is there any way to get?

**Comment by aledeg** [comment]
At the moment, you will have to copy one existing and modify it. There is no documentation for that right now. It will probably be overridden by updates so you need to have a proper way to back up it.

I don't know how impatient you are because I am currently working on improving that process. You can check the discussion #3345 and the PRs #3383, #3397, and ##3399 (and probably more to come).

**Comment by math-GH** [comment]
Here is a documentation how to create an own theme: https://freshrss.github.io/FreshRSS/en/developers/04_Frontend/02_Design.html
