### ISSUE TITLE
How to deal w/ redirects in feed?

### ISSUE THREAD

**Issue by dumprop** [FreshRSS/FreshRSS#3435]
Feed: https://blog.path.net/rss/

From browser all are ok, but when I do curl:
```
<html>
<head><title>307 Temporary Redirect</title></head>
<body>
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

RSS logs:
```
2021-02-10 10:06:42
Unknown error for feed [https://blog.path.net/rss/]
2021-02-10 10:06:28
Invalid action name for controller FreshRSS_index_Controller
```

**Comment by Alkarex** [comment]
As visible with the following command, there is an infinite redirection loop due to a badly configured feed.

```sh
curl -v -L 'https://blog.path.net/rss/'
```

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.path.net%2Frss%2F

The best is to contact the Web site owner, but you might be able to find a solution using some manual curl settings (see https://github.com/FreshRSS/FreshRSS/pull/3367 ) or by making an extension, or going through an RSS Bridge module.

Not much we can do apparently at FreshRSS level.
