### ISSUE TITLE
add focusreader to list

### ISSUE THREAD

**Issue by allentown521** [FreshRSS/FreshRSS#3478]
FocusReader support fever and freshrss,
https://play.google.com/store/apps/details?id=allen.town.focus.reader
you can add it to readme applist

**Comment by Alkarex** [comment]
Hello @allentown521 
Thanks for reaching out. Please tell if you already know what are FocusReader characteristics for the different columns
https://github.com/FreshRSS/FreshRSS#apis--native-apps
I will give it a try

**Comment by Alkarex** [comment]
@allentown521 Please see https://github.com/FreshRSS/FreshRSS/pull/3514

Your app looks very nice, congrats 👍🏻 

The main lacks I see (please correct if this is wrong):
* No labels (tagging articles with custom labels, and synchronised with the server)
* The app cannot download articles, which were first read on the sever
* Podcasts are supported but cannot be queued / added to a playlist
* No possibility to download more articles for a given feed or category

The whole app seems to work very fine, with good synchronisation, also offline.

The main negative point I observed on my Samsung Galaxy S8 is that opening an article, or moving from one article to the next is  quite slow (maybe especially if there is an image), taking ~1s+ before the rendering is finished.

**Comment by allentown521** [comment]
Thank you for your experience and feedback. Some of them have been added to
the development list and will support tag soon

Alexandre Alapetite <notifications@github.com> 于2021年3月11日周四 上午3:29写道：

**Comment by wolfpld** [comment]
> The main negative point I observed on my Samsung Galaxy S8 is that opening an article, or moving from one article to the next is quite slow (maybe especially if there is an image), taking ~1s+ before the rendering is finished.

On my phone (Mi Mix 2) the initial page render when going from the list of articles to the article view is also relatively slow (which is understandable, as the application can't predict which article will be selected by the user), but when swiping to the next or previous article, the page contents are already preloaded and waiting to be used. This includes feeds with large pictures, such as APOD provided by https://github.com/wolfpld/rssfix.

> Thank you for your experience and feedback.

One minor nuisance is that some feed icons are replaced by the default icon for a brief moment, during article refresh. I would propose to keep the previously available icon in some local cache, so that doesn't happen.
