### ISSUE TITLE
How to install on Linux Server?

### ISSUE THREAD

**Issue by littabird** [FreshRSS/FreshRSS#3685]
I used to have sharedhosting with Softaculous. SO install FreshRSS was just one click. Now that I got a lil VPS, there is no Softaculous, I wonder how do you install this script?
 
I have no idea how to use Docker or any other hosting you mentioned. I don't even understand the below:-

> Put the application somewhere on your server (expose only the ./p/ folder to the Web)
You mean upload to the server using FTP?
So, how do you ONLY expose ./p/ folder?

> Add write access to the ./data/ folder for the webserver user
You mean CHMOD 777 or what?

However, I have installed some scripts before... Usually, you upload to folder (domain/Subdomain), then hit the install.php using browser, and follow the instruction. Some poorly coded script will need you to go create a datebase first. 

In your case, there is no install.php... What do I do? 
Appreciated your help.

**Comment by Frenzie** [comment]
It sounds like you're just looking at the summary? Please see https://freshrss.github.io/FreshRSS/en/admins/01_Index.html for the in-depth docs.

**Comment by littabird** [comment]
Do you mind telling me where exactly in the article I can find step-by-step
instructions to *install FreshRSS on a Linux sharedhosting*?
All I can see is the same old "hitech" install using Docker or Debian
9/Ubuntu 16.04
<https://freshrss.github.io/FreshRSS/en/admins/06_LinuxInstall.html>??
I need instructions on cheap no frill Linux/cPanel installation.
Thanks.

**Comment by Frenzie** [comment]
I think your own instructions pretty much say all there is to it? :-) If you just extract it and open it in your browser, the installation should commence.

**Comment by littabird** [comment]
You mean open the index.php on a browser and it will auto install mysql
etc? Can't imagine this can work?? Let me know if this is not what you
mean...

**Comment by Frenzie** [comment]
You can just use SQLite, in which case there's indeed nothing more to it. (Provided the relevant module is installed on the server.)

Of course if you want to use MySQL instead you'll have to create a database first, but that's no different for anything else. Instructions for that can't be given because the process depends on the shared hosting control panel, but there shouldn't be much to it. For example see https://docs.hetzner.com/konsoleh/account-management/databases/mysql/

**Comment by littabird** [comment]
>
> You can just use SQLite


You mean the script comes with SQLite built in ie. I don't have install any
DB?

TBH, I don't know what am I looking at, I will upload just like that and
see if it works? I'd be surprised it will work by simply uploading ...?

**Comment by Frenzie** [comment]
There is the database software (e.g., SQLite, MySQL/MariaDB or PostgreSQL) that's installed by the administrator of the shared server. Which one you choose is up to a combination of your preferences and what's available to you. In MySQL and PostgreSQL you have to create a database for the program to access first, while in SQLite the program can do it all by itself provided the access rights to the data directory are set up correctly.

SQLite is typically the easiest option for a small-scale installation because the database is just a file on the disk. (Of course, ultimately so are MySQL databases, but they're not quite as portable.) That means you can just copy over the folder wholesale to transfer the entire thing somewhere else or to back it up. For just one or a few users it's unlikely that you'd you'd gain much from MySQL/MariaDB or PostgreSQL.

**Comment by littabird** [comment]
I just loaded the zipped files.

You're right, It does go to the install page but now I am stuck....

*May I know what am I supposed to fill in for "Host"? Is this the IP
address of my server *(on top of the database input columns)

Secondly, I do have a choice for SQLite, MySQL, or PostgreSQL.

Now I won't use SQLite, I think Softaculos auto install will automatically
go for mySQL becos I say there are a few tables in mySQL (for existing
installations).

My question is *what is the advantage of using PostgreSQL, if any?*

NB: I didn't finish installing ... but guess it should be a
straightforward thing.

**Comment by Frenzie** [comment]
For (small-scale) FreshRSS I doubt it makes a difference, except SQLite is the easiest to use.

**Comment by littabird** [comment]
One of the question is **"Host"** (together with DB name & password etc).
May I know what am I supposed to fill in for **"Host"** tio move the installation forward?

**Comment by Frenzie** [comment]
That would depend on your setup. For you it's presumably `localhost`.
