### ISSUE TITLE
[BUG] cannot add feed "XML or PCRE extensions not loaded!"

### ISSUE THREAD

**Issue by antvet** [FreshRSS/FreshRSS#3772]
I tried to add a feed to my self-hosted FreshRSS (i.e. [https://www.cnil.fr/fr/rss.xml](https://www.cnil.fr/fr/rss.xml)) but the error ``The feed cannot be added`` shows up. Same with the #force_feed option. I went to the log view from the web interface and I can see the line ``XML or PCRE extensions not loaded! [https://www.cnil.fr/fr/rss.xml]``. I then went to the "Installation checking" tab, in the "Administration" section and two errors were there: ``Cannot find curl lib (php-curl package)`` and ``Cannot find a lib for browsing the DOM (php-xml package)``. The problem is that I already have these two packages on my server:
```
$ apt list --installed | grep curl

php-curl/stable,now 2:7.3+69 all  [installed]
php7.3-curl/stable,now 7.3.29-1~deb10u1 armhf  [installed]
```
and
```
$ apt list --installed | grep xml

php-xml/stable,now 2:7.3+69 all  [installed]
php7.3-xml/stable,now 7.3.29-1~deb10u1 armhf  [installed]
```
Of course I tried to restart the nginx service but it didn't work. FreshRSS is also up to date.

Here are my specs:
- **OS** : Raspbian GNU/Linux 10
- **Webserver** : NGINX 1.14.2
- **PHP** : 7.3.29
- **DB** : MariaDB 10.3.29
- **FreshRSS** : 1.19.0-dev
- **Browser** : Firefox 91

**Comment by Alkarex** [comment]
Hello,
That might be due to multiple PHP versions installed and/or misconfiguration.

## For the Web

You can try to create a file `./FreshRSS/p/phpinfo.php` with the following content:

```php
<?php
phpinfo();
```

and then access it from your browser https://freshrss.example.net/phpinfo.php

## For the command line

```sh
php -i | grep -i curl
```


Alternatively, we are providing a Docker image for Raspberry Pi: `freshrss/freshrss:arm`

**Comment by math-GH** [comment]
@antvet any news here? Is your issue already solved?
