### ISSUE TITLE
SQL error deleteFeed: database disk image is malformed (Ubuntu)

### ISSUE THREAD

**Issue by lee-costa** [FreshRSS/FreshRSS#3839]
My install recently stopped updating and now I see the malformed error in the logs. I don't mind loosing my feeds since I can easily recreate them so what would be the easiest way to recover from this error? Right now I can't add or delete feeds.

**Comment by Alkarex** [comment]
Hello,
What database are you using?

**Comment by lee-costa** [comment]
I am using mysql. My database configuration section looks like this:

        `  'db' => 
          array (
            'type' => 'sqlite',
            'host' => '',
            'user' => '',
            'password' => '',
            'base' => 'REDACTED',
            'prefix' => '',
            'pdo_options' => 
            array (
            ),
          ),`

Not sure why it doesn't point to a specific database but it has always worked before. I noticed after "marking as read" a ton or articles is when the malformed message popped up.

**Comment by Alkarex** [comment]
It looks like you are using SQLite, not MySQL.
Such an error might be due to a disk / IO problem, e.g. lack of space, failing hard-disk, failing SD Card (e.g. on Raspberry Pi)...

If you were interested in recovering your data, you could try an export from command line, like:

```sh
cd ./FreshRSS/
cli/export-sqlite-for-user.php --user alice --filename /tmp/alice.bak.sqlite'
```

And then use the exported file instead of your `./FreshRSS/data/users/alice/db.sqlite` file.

If you want a full reset, delete `./data/applied_migrations.txt`, `./data/config.php`, `./data/users/alice/`

If you installed FreshRSS using git, you can make sure that your setup is correct using something like:

```
cd ./FreshRSS/
git fetch --all --prune
git reset --hard FETCH_HEAD
```

**Comment by lee-costa** [comment]
@Alkarex Deleting the files mentioned allowed me to start from scratch. Not that I care but what happens to the malformed database? Should I bother deleting it?

Thanks for your help.

**Comment by Alkarex** [comment]
If you indeed were using SQLite, there is nothing more to do because the database was located in `./FreshRSS/data/users/alice/db.sqlite` and you have probably deleted its parent directory. If it were MySQL, then you would have to drop that database.

**Comment by lee-costa** [comment]
Makes sense. Again, thanks for your prompt assistance!
