### ISSUE TITLE
[BUG] Shortcuts: open RSS view in a new tab

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3894]
The shortcut "Open RSS view in a new tab"
![grafik](https://user-images.githubusercontent.com/1645099/137583689-16fe01b9-e792-413a-ab5b-df4168ccad8d.png)

works for me like clicking on the RSS feed "export"
![grafik](https://user-images.githubusercontent.com/1645099/137583706-8fa521a9-e9d2-423b-9454-4fbabfaaf496.png)

I did expect something different (I tried it, because I had no clue what it means).

**Environment information (please complete the following information):**
 - FreshRSS version: 1.18.1

**Comment by math-GH** [comment]
Is it fine for you to rename the text to "Open as RSS feed"?

**Comment by Frenzie** [comment]
I suspect the "view" phrasing may have been related to how some/more browsers used to have dedicated styling if you went straight to a feed. For example, here's what that currently looks like in Vivaldi.

![Screenshot_2021-10-16_12-31-12](https://user-images.githubusercontent.com/202757/137584022-2b5626e0-92c9-43c7-8a20-9e0553f0f210.png)

> Is it fine for you to rename the text to "Open as RSS feed"?

You might potentially want to keep the new tab since it's distinct in behavior from the others. In any case I agree it's clearer.
