### ISSUE TITLE
[BUG] "Error during context user init!" when accessing my freshrss

### ISSUE THREAD

**Issue by SamuelB-ACA** [FreshRSS/FreshRSS#4208]
**the bug**
I have the message "Error during context user init!" when accessing my freshrss. Everything was working nice until few days ago. Same problem on 2 different computers. Tried emptying cookies, not better.

**Environment information:**
- OS: Debian 11 on server
- Browser: Chromium & Firefox
- FreshRSS version: [1.19.2]
- Database version: [Mariadb 10.5.12]
- PHP version: [PHP 8]
- Installation type: ispconfig

**Additional context**

**Comment by Alkarex** [comment]
Hello,
So your system was working with FreshRSS 1.19.1 but not with FreshRSS 1.19.2, right?
And the bug is during the login using the Web form?
Could you please try to check your Web browser logs and also FreshRSS logs `./FreshRSS/data/users/*/log*.txt` for additional information?

Additional logs can be generated by setting the following value in `./FreshRSS/data/config.php` :

```php
'environment' => 'development',
```

What did you do more precisely with ispconfig? Deploy FreshRSS using git, ZIP, Docker, ...?

**Comment by SamuelB-ACA** [comment]
Ok, my bad, I'm stupid today. The problem was with rights access on the tmp dir. Shame on me

**Comment by filisko** [comment]
@SamuelB-ACA I don`t think its a shame on you :) the error should be much more clearer
