### ISSUE TITLE
[BUG] Can't feed this url 'https://www.oschina.net/news/rss'

### ISSUE THREAD

**Issue by yswtrue** [FreshRSS/FreshRSS#4211]
```
2022-02-08 11:50:22
cURL error 22: The requested URL returned error: 403 [https://www.oschina.net/news/rss#force_feed]

```
this is the log

**Comment by Frenzie** [comment]
403 means forbidden.

**Comment by yswtrue** [comment]
but I can curl directly and return the correct content.

**Comment by Alkarex** [comment]
This is a case when the client is banned by user-agent, maybe due to recent abuse (people downloading the RSS feed at a too high frequency).

Wait 30min and try again by using another "user-agent" string:

![image](https://user-images.githubusercontent.com/1008324/152998061-ec7cfd93-553d-4869-a86f-7e990ec86e82.png)

I suggest putting the same user agent string than your own browser, e.g.

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

**Comment by Frenzie** [comment]
@Alkarex Shouldn't `curl -i https://www.oschina.net/news -H "User-Agent: FreshRSS/1.19.2"` simulate what we send or do I recall incorrectly?

In any case, it does look like default FreshRSS is rejected and setting a custom user agent works around that.
