### ISSUE TITLE
Adding FreshRSS as a feed reader to Firefox

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#425]
See https://developer.mozilla.org/en-US/docs/Adding_feed_readers_to_Firefox
It seems easy to implement

**Comment by subic** [comment]
Sorry to comment on this old issue but it is the first google result for "FreshRSS firefox subscribe" so this would have helped me and perhaps will help someone else. If you prefer to add your installation to Firefox subscription service instead of using the bookmarklet there is a way to add it manually. 

It is described [here](https://developer.mozilla.org/en-US/Firefox/Releases/2/Adding_feed_readers_to_Firefox) but basically:
1. open about:config
2. search for "browser.contentHandlers.types." and note the highest number following the returned strings (ie if yuo see browser.contentHandlers.types.1.something up to browser.contentHandlers.types.5.somethingelse etc. the highest number is 5). Your contentHandler will have to have a free number so just pick one higher than currently registered (you would chose six in above example).
3. You will have to add three new strings to your about config (replace %NUMBER% with the number from previous step and FRESHRSS.URL with your installation address):

```
Preference name:
browser.contentHandlers.types.%NUMBER%.title
Value: 
FreshRSS
(or any other name you would like to use ("My feeds" or anything really))

Preference name:
browser.contentHandlers.types.%NUMBER%.type
Value: 
application/vnd.mozilla.maybe.feed
(do not change this value)

Preference name:
browser.contentHandlers.types.%NUMBER%.uri
Value: 
http://FRESHRSS.URL/i/?c=feed&a=add&url_rss=%s
(replace FRESHRSS.URL with your domain and change to https if you use it)
```

Restart Firefox and you should be able to subscribe to sites which provide a feed link using the Firefox built in "Subscribe" button. Just select the name you set under the first Preference name from the drop-down (you can also make it default with the checkbox) and you will be redirected to FreshRSS subscription settings (you must be logged in).

Hope this is clear enough, otherwise consult https://developer.mozilla.org/en-US/Firefox/Releases/2/Adding_feed_readers_to_Firefox for a more in depth reference. It might also be helpful to include this somewhere in the docs if the maintainers find it useful.

**Comment by Alkarex** [comment]
Thanks @subic , this is some interesting documentation to have. It is already good there, but if you have a bit more motivation, it would be great with a pull request to https://github.com/FreshRSS/documentation , which is used to build http://doc.freshrss.org/ (there is not much yet, especially in English, but it is slowly getting richer) :-)

**Comment by subic** [comment]
Hi, I've opened an issue (Issue #1354 ) regarding some bookmarklet improvements that includes a suggestion for adding the info to the FreshRSS iteslf. I'll also submit the pull for documentation in the following week.

**Comment by mdemoss** [comment]
Before I saw this thread, I made this commit: https://github.com/mdemoss/FreshRSS/commit/3e4bc30a9c444e1a6731db39147d02b5806ea516 for a "Click to add to Firefox as a reader" link.

@marienfressinaud Do the concerns about CSRF still hold true in the current version? Maybe there wasn't any user interaction before adding a feed in the previous version?

**Comment by primaeval** [comment]
The uri in @subic 's very useful post should be
`http://FRESHRSS.URL/i/?c=feed&a=add&url_rss=%s`

I really wish this could be automated. FreshRSS is superb apart from easily adding new feeds.

**Comment by subic** [comment]
You're absolutely right, I have edited my previous post. The /f/ was an artifact of copy pasting...
