### ISSUE TITLE
Add a force feed option in feed configuration

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#456]
It would be nice to have that parameter available because it is one of the solution recommended to add a feed which does not work. For example:
<code>
2014-03-12 07:37:24A feed could not be found at http://foulab.org/fr/rss/Foulab_News. A feed with an invalid mime type may fall victim to this error, or SimplePie was unable to auto-discover it.. Use force_feed() if you are certain this URL is a real feed. [http://foulab.org/fr/rss/Foulab_News]
</code>

As it is an advanced parameter, it probably needs a warning.

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/402

**Comment by ellypsis** [comment]
Hi,
I know that this bug is closed, but I couldn't manage to have the #force_feed working.
I want to add this feed : http://www.kuntaljoisher.com/feed/ which is valid  : https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.kuntaljoisher.com%2Ffeed%2F
Also, I didn't see any mention of the #force_feed option in the doc.
I tried : `http://www.kuntaljoisher.com/feed#force_feed` but it doesn't help, I get a 403 forbidden.
And when I tried to add the feed without the force tag, I get `Unknown error for feed [http://www.kuntaljoisher.com/feed/]`
Any idea?

**Comment by Frenzie** [comment]
It works for me without issue (no `#force`).

![screenshot_2018-11-26_18-17-40](https://user-images.githubusercontent.com/202757/49030440-9a93a580-f1a7-11e8-9d7a-945de2887f42.png)

**Comment by Alkarex** [comment]
@ellypsis This feed works for me as well. Maybe a temporary issue? Please open another ticket if the problem persists.

**Comment by ellypsis** [comment]
Hi guys, sorry I didn't activate notification.
I tried again today and yes, I was able to add the feed.
Thanks!
