### ISSUE TITLE
[Feature] enable/allow ImageProxy plugin to be invoked by FeverAPI endpoint

### ISSUE THREAD

**Issue by nexus-uw** [FreshRSS/FreshRSS#4785]
**Is your feature request related to a problem? Please describe.**
I would like to ensure that my feed's images are proxied through my freshrss server when i am accessing them through the FeverAPI

**Describe the solution you’d like**
I would like the [ImageProxy extension](https://github.com/FreshRSS/Extensions/tree/master/xExtension-ImageProxy) to be invoked by the FeverApi endpoint

**Describe alternatives you’ve considered**
I was able to hack a solution together by adding
```php
Minz_ExtensionManager::enable("Image Proxy");
```
after [this line in fever.php](https://github.com/FreshRSS/FreshRSS/blob/1fe66ad020ca8f0560bb9c6e311852ed77228f78/p/api/fever.php#L486)

this is obviously not an ideal solution

**Comment by Frenzie** [comment]
Assuming the comment there is accurate the cause is clear, since it's a `user` extension, not `system`. In which case either the behavior or our docs are a bit strange because the advertised difference is just if it's for all users or individually toggled.
https://github.com/FreshRSS/FreshRSS/blob/1fe66ad020ca8f0560bb9c6e311852ed77228f78/p/api/fever.php#L485-L486

**Comment by nexus-uw** [comment]
@Frenzie  :+1:

so i was able to configure it properly by doing the following:
1. changed `type` from `user` to `system` here https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/metadata.json#L7
2. added `"Image Proxy"=>true` to the `extensions_enabled` in my *config.php* (extension name pulled from https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/metadata.json#L2)
