### ISSUE TITLE
[BUG] Error during context user init!

### ISSUE THREAD

**Issue by amusicsite** [FreshRSS/FreshRSS#4795]
Every page displays the error message Error during context user init! on desktop Ubuntu while on my Android phone I can get into the setting but feeds not updating. 

Before been using it for a few years without problem 

Current version 1.20.0

**Comment by Alkarex** [comment]
Please provide more information, in particular your platform (Web server...) and how you install and update FreshRSS:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment information (please complete the following information):**
- Device: [e.g. iPhone6]
- OS: [e.g. Ubuntu 20.04]
- Browser: [e.g. Firefox 86]
- FreshRSS version: [e.g. 1.17.1]
- Database version: [e.g. Mysql 5.7]
- PHP version: [e.g. PHP 7.4]
- Installation type: [e.g. Yunohost]

**Additional context**
Add any other context about the problem here.

**Comment by Alkarex** [comment]
Try to re-apply the access rights. E.g.:

```sh
cd ./FreshRSS/
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by amusicsite** [comment]
Please provide more information, in particular your platform (Web server...) and how you install and update FreshRSS:

cPanel Version | 106.0 (build 9)
Apache Version | 2.4.54
PHP Version | 8.0.24
MySQL Version | 8.0.31
Architecture | x86_64
Operating System | linux

Ran the command: 
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/

Not seemed to have changed anything.

**Comment by Alkarex** [comment]
It does not look like the same symptoms, but please check your `base_url` in `data/config.php`

Potentially related cPanel issue https://github.com/FreshRSS/FreshRSS/issues/4611#issuecomment-1245912337

And please check your Web server logs, and FreshRSS logs in `./data/users/*/log*.txt`

**Comment by amusicsite** [comment]
It was http rather than https but otherwise base url was ok and changing to https seems to have done nothing. 
FreshRSS logs since issue:
[Mon, 31 Oct 2022 08:49:48 +0000] [warning] --- FreshRSS_CategoryDAO::addColumn: kind
[Mon, 31 Oct 2022 08:49:48 +0000] [warning] --- FreshRSS_CategoryDAO::addColumn: lastUpdate
[Mon, 31 Oct 2022 08:49:48 +0000] [warning] --- FreshRSS_CategoryDAO::addColumn: error
[Mon, 31 Oct 2022 08:49:48 +0000] [warning] --- FreshRSS_EntryDAO::addColumn: attributes
[Mon, 31 Oct 2022 08:49:52 +0000] [warning] --- FreshRSS_FeedDAO::addColumn: kind

Nothing of note in the server logs

**Comment by amusicsite** [comment]
Got it working after Restarting PHP-FPM service for Apache

Thanks for the help
