### ISSUE TITLE
[BUG] Bookmarklet failing

### ISSUE THREAD

**Issue by Aasemoon** [FreshRSS/FreshRSS#4847]
**Describe the bug**
I recently tried the bookmarklet for the first time. So I dragged the button to my bookmarks toolbar, went to various pages with feeds, clicked on the button and have been getting this error:

_"Not Acceptable!
An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security."_

Should also mention that I recently updated FreshRSS, but the problem remains the same.

**Environment information (please complete the following information):**
- Device: Various
- OS: Various
- Browser: Various
- FreshRSS version: 1.20.1-dev
- Database version: mysqlnd 7.4.30
- PHP version: 7.4.30
- Installation type: Shared host

Error log is telling me nothing useful. Does something need to be whitelisted on mod security? I'd appreciate any suggestions anyone might have.

**Comment by Alkarex** [comment]
Mod_Security seems to be abandoned? https://www.modsecurity.org/

Anyway, Mod_Security might detect that a URL is passed as parameter.
As far as I can see, the URL is properly encoded, so there should be no problem and most likely a sign of overzealous configuration, so that might require telling Mod-Security to accept it.
Can you show the URL generated by the bookmarklet and also try to paste it manually in your Web browser?

No a FreshRSS issue as far as I can see.

**Comment by Aasemoon** [comment]
@Alkarex That's right, I'm also not sure why my host is still using mod_security.

Here's an instance of the generated URL:
http://freshrss.example.net/p/i/?c=feed&a=add&url_rss=https%3A%2F%2Fwritings.stephenwolfram.com%2F

Manually pasting doesn't seem to make any difference. Thanks for getting back to me at any rate.

**Comment by Alkarex** [comment]
Not related to this issue, but your configuration would be better by putting the Web root inside the `./p/` directory, so that your public URL looks like `https://freshrss.example.net/i/` and not like ~~`https://freshrss.example.net/p/i/`~~
If you make that change, remember to update your `base_url` accordingly in `./data/config.php`

**Comment by Aasemoon** [comment]
@Alkarex Ah sure, thanks for the suggestion! =)

**Comment by Aasemoon** [comment]
Just a quick update, the issue was indeed to do with mod_security going haywire. Whitelisting the application solved the issue.

**Comment by aledeg** [comment]
Thank you for your feedback!
