### ISSUE TITLE
[BUG] [Android] FreshRSS failed to retrieve content from your FresRSS server

### ISSUE THREAD

**Issue by janaxhell** [FreshRSS/FreshRSS#4862]
**Describe the bug**
Android app (installed from F-droid) connects to my server and shows feeds, but as soon as it checks for new ones gives that error. This happens in both my OneplusOne phone with LineageOS 17.1 and Lenovo P11 tablet with latest Android.

**To Reproduce**
1. Open app
2. Wait a few seconds
3. Error message appears

**Expected behavior**
App should download new feeds and show them

**Screenshots**
See below

**Environment information (please complete the following information):**
- Device: Fujitsu Esprimo q556 x64
- OS: OMV/Docker/Portainer
- Browser: Vivaldi and LibreWolf
- FreshRSS version: 1.20.1
- PHP version: PHP 7.4.33
- Installation type: linuxserver/freshrss:latest

**Additional context**
My server goes through Nginx Proxy Manager to Cloudflare, where I have my domain name. Both WebUI and Android apps point to that domain. For the apps I have configures the API password and logged in with that. 
FreshRSS on its own works, I have imported my whole Inoreader OPML and it populated all feeds/channels. I have added and enabled extensions to see embedded Youtube videos which BTW refuse to show, looping infinite anti-robot captcha. Don't know if it's related.

![Screenshot_20221116-202217_FreshRSS](https://user-images.githubusercontent.com/55061479/202274975-01108e78-8e25-4052-946b-ab26a90555dd.png)

![freshrss](https://user-images.githubusercontent.com/55061479/202275650-e76ad596-7baf-41ec-8f9f-810b5856f059.jpg)

**Comment by Alkarex** [comment]
Hello,
If there is a bug with an app, it should be reported to the developer of that app, in this case https://gitlab.com/christophehenry/freshrss-android

However, before doing that, it is a good idea to check that your system operates as intended, especially if you are having layers such as Cloudflare, which have a tendency to break the Web in multiple manners.

1) Use the self-assessment tests from your instance https://freshrss.example.net/api/
2) Try some basic queries manually https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html#google-reader-compatible-api
3) Try with another client to check whether the problem is specific to one client or more general https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps
4) If you still believe the bug in the app, then contact that app's developer

**Comment by janaxhell** [comment]
Ha, I didn't notice there were so many compatible apps. I have tried Raindrops for Android and it works fine. 
About the captcha: it was definitely the extension to watch Youtube videos embedded. As soon as I disabled it, it stopped asking. This captcha thing was extended to all my system, I was asked even when I visited Youtube page from any browser "because something was violating Google rules".

**Comment by Alkarex** [comment]
Ok. Could you please report your initial problem to https://gitlab.com/christophehenry/freshrss-android ?

**Comment by janaxhell** [comment]
How do I do that? Copy the link of this issue or replicate a full copy of my post? I'm not a dev and I see some people just post links, not sure what to do.

**Comment by Frenzie** [comment]
It's a completely different place with no relation to here, so I would simply copy the OP (plus other relevant info if it came up) with a backlink to this issue as background information.

**Comment by janaxhell** [comment]
I see there is an issue very similar to mine there https://gitlab.com/christophehenry/freshrss-android/-/issues/123
Shall I just replay with the backlink to this?

**Comment by Frenzie** [comment]
You mean you see the timeout and oom stuff if you scroll down in your error message? If so then yes.

**Comment by janaxhell** [comment]
No, I only see the FAILED part. I'll copy the entire OP.
