### ISSUE TITLE
[Feature] Keyword filter

### ISSUE THREAD

**Issue by ron159** [FreshRSS/FreshRSS#4907]
**Is your feature request related to a problem? Please describe.**

Some feeds push ads or other unwanted content

**Describe the solution you’d like**

Support keyword filtering function to hide hit entries

**Comment by cskwrd** [comment]
I was looking for similar functionality. I think it is already there. The [filter docs](https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#filtering-articles) seem to support several different scopes. I was able to apply these to individual feeds. I haven't found a way to automatically delete content, but you can use them to automatically mark messages as read. I hide read messages by default so this is good enough for me, because I use the purge policy feature to clean up read messages.

**Comment by ron159** [comment]
Please tell me how to automatically mark the article as read. I can't find it. Thank you.

**Comment by cskwrd** [comment]
1. Click the cog next to the feed you wish to apply the filter to.
2.  Click _Manage_.
3. Scroll to _Filter actions_.
4. Configure as needed.
5. Click _Submit_.

**Comment by ron159** [comment]
> 1. Click the cog next to the feed you wish to apply the filter to.
> 
> 2.  Click _Manage_.
> 
> 3. Scroll to _Filter actions_.
> 
> 4. Configure as needed.
> 
> 5. Click _Submit_.

OK got it.Thank you again,I'll try it

**Comment by aledeg** [comment]
@ron159 If this is solved by the solution provided by @cskwrd , please consider closing this issue. Thank you.
