### ISSUE TITLE
OpenSSL issue "error:0A000152:SSL routines::unsafe legacy renegotiation disabled" [BUG]

### ISSUE THREAD

**Issue by nexbelgium** [FreshRSS/FreshRSS#5035]
The docker container seems to have issues to connect to some websites using OpenSSL:
 
When running 
```
sudo docker exec freshrss php -r "readfile('https://myexperts.bnpparibasfortis.be/nl/contributors/philippe-gijsels/');"
```

I get following error: 
```
PHP Warning:  readfile(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000152:SSL routines::unsafe legacy renegotiation disabled in Command line code on line 1
```
When trying to reach that site from outside the container, it works well. 

I have also checked with other websites running the command above, and they work correctly, but not the one in my example.

**Environment information:**
- Device: VPS
- OS:  Ubuntu 20.04
- FreshRSS version: latest

**Comment by Alkarex** [comment]
Hello,
What Docker image are you using, more precisely?

Our Debian version (e.g. `freshrss/freshrss:edge`) seems to work fine with that site.

```console
$ docker run --rm freshrss/freshrss:edge php -r "readfile('https://myexperts.bnpparibasfortis.be/nl/contributors/philippe-gijsels/');"
Works...

$ docker run --rm freshrss/freshrss:edge-alpine php -r "readfile('https://myexperts.bnpparibasfortis.be/nl/contributors/philippe-gijsels/');"
PHP Warning:  readfile(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000152:SSL routines::unsafe legacy renegotiation disabled in Command line code on line 1
PHP Warning:  readfile(): Failed to enable crypto in Command line code on line 1
PHP Warning:  readfile(https://myexperts.bnpparibasfortis.be/nl/contributors/philippe-gijsels/): Failed to open stream: operation failed in Command line code on line 1
```

But it seems like the issue is with our Alpine version, which ships OpenSSL 3.0:

`cURL error 35: OpenSSL/3.0.7: error:0A000152:SSL routines::unsafe legacy renegotiation disabled`

From the point of view of OpenSSL, this Web site is "unpatched" and potentially unsecure (probably not unsecure in practice as it only supports TLS 1.2 but [that is still not good](https://blog.qualys.com/product-tech/2010/10/06/disabling-ssl-renegotiation-is-a-crutch-not-a-fix-2)):

![image](https://user-images.githubusercontent.com/1008324/213943245-5b39560c-afa6-4390-afb8-42218f8a05a4.png)

* https://www.ssllabs.com/ssltest/analyze.html?d=myexperts.bnpparibasfortis.be
* https://www.openssl.org/docs/man3.0/man3/SSL_clear_options.html

As I would rather not decrease the global default security of OpenSSL (by allowing `UnsafeLegacyRenegotiation`), what we could do is add a cURL flag to our unsafe option, but the SSL option `SSL_OP_LEGACY_SERVER_CONNECT` does not seem to be exposed through cURL (yet?) and therefore not through PHP either:

* https://github.com/curl/curl/issues/8943
* https://php.net/function.curl-setopt

Additional input & follow-up welcome.

**Comment by nexbelgium** [comment]
Thanks for your reply.

The docker image I am using: **lscr.io/linuxserver/freshrss:latest**

I understand you don't want to lower the security, so I'll wait that this website patches their security. 
Or maybe I can run the latest version of the Docker image that was not yet on OpenSSL 3.0. Do you have an idea how I can find that out ?

**Comment by Alkarex** [comment]
You can try our `freshrss/freshrss` , which is based on Debian and works

**Comment by nexbelgium** [comment]
Ok, I'll try that, many thanks!
