### ISSUE TITLE
[BUG] Feed entry thumbnail always shows black/white stripes, no matter the selected format

### ISSUE THREAD

**Issue by k5123** [FreshRSS/FreshRSS#5048]
When showing thumbnails, the images always show with black and white stripes, no matter their actual format and the configured display option.

**To Reproduce**
1. Go to Display
2. Select any format except 'none' for Thumbnail
3. Go back to feed
4. Thumbnails now have black and white stripes visible, irregardless of the format selected in 2

**Expected behavior**
No black and white stripes

**Screenshots**
![image](https://user-images.githubusercontent.com/9386722/215217192-d35ea7dc-054b-46b0-ba17-82544e31bb0e.png)

**Environment information (please complete the following information):**
Browser: Firefox 108.2
FreshRSS: 1.20.2

**Comment by Frenzie** [comment]
It seems to come from the standard padding on .item-element.

**Comment by k5123** [comment]
I was digging a little bit too, and if you remove the background: line from the `.flux .item.thumbnail img` block, it seems to be fine - layout and otherwise.

**Comment by Alkarex** [comment]
> I was digging a little bit too, and if you remove the background: line from the `.flux .item.thumbnail img` block, it seems to be fine - layout and otherwise.

@k5123 PR welcome

**Comment by math-GH** [comment]
@k5123 Please check the fix #5058

**Comment by ltschk** [comment]
First of all: I pretty much enjoy using FreshRSS! Using it probably since 2 years now. Great tool, great work!! Thanks for that!!

I switched from the Origine theme to **Origine-compact** today and got those black/white stripes from the background as mentioned [above](https://github.com/FreshRSS/FreshRSS/issues/5048#issue-1560505594).
![grafik](https://github.com/FreshRSS/FreshRSS/assets/150657587/469457eb-6a5d-4da6-a164-5da882f830f3)

I could fix this by adjusting line [128](https://github.com/FreshRSS/FreshRSS/blob/354a5e83888cebe89843b754d0936f3633323cef/p/themes/Origine-compact/origine-compact.css#L128) of p/themes/Origine-compact/origine-compact.css from `padding: 0.25rem 0;` to `padding: 0 0;` and in line [128](https://github.com/FreshRSS/FreshRSS/blob/354a5e83888cebe89843b754d0936f3633323cef/p/themes/Origine-compact/origine-compact.rtl.css#L128) of p/themes/Origine-compact/origine-compact.rtl.css respectively.

**Comment by math-GH** [comment]
Thanks for that finding.
If possible please have a look into the fix: #6197
