### ISSUE TITLE
Support for more path segments in the `finding news items` section of "HTML + XPath"

### ISSUE THREAD

**Issue by SailReal** [FreshRSS/FreshRSS#5067]
First of all, thank you for this awesome piece of software!

It would be amazing if more than one path segment could be supported in the XPath `finding news items` section. Something like `//foo` works like a charm and I'm using it a lot but if you need select a path like e.g. `//foo/bar/bas` it doesn't work. The same applies for providing the full path like `/foo/bar/bas` or `/html/body/foo/bar/bas`.

The reason behind is that sometimes a website has multiple sections where not want all `bas` items in the rss, so I can not simply use something like `//bas`, only those under the `//foo/bar/bas` should be selected but not `//foo/baz/bas`.

Example data:
`/html/body/foo/bar/bas/1`
`/html/body/foo/bar/bas/2`
`/html/body/foo/bar/bas/...`
`/html/body/foo/baz/bas/1`
`/html/body/foo/baz/bas/2`
`/html/body/foo/baz/bas/...`

Now as mentioned, I want only `//foo/bar/bas` in the output.

Currently I think it is only possible to provide one path segment including a child in the `finding news items` section, right? I mean something like `//foo` works but `//foo/bar/bas` not, right?

To provide an real world scenario: I want to add an RSS for https://www.ebay-kleinanzeigen.de/s-giessen/kettcar-daytona/k0l4710r50 where I only want those results above the `Alternative Anzeigen in der Umgebung` section where the solution would be `//div[@class="position-relative"]/ul/li/article` because the result needs to be relative to the `position-relative`-div, otherwise I have all `article`s in the result.

**Comment by Alkarex** [comment]
Hello,
With our current XPath feature, you can already have precise deep paths, combine expressions, exclude elements, etc. So no need to add anything there. So your `//foo/bar/bas` is supposed to work.

To test such things, I suggest you make a clean HTML document that you control.

First problem: If you only test on the example of scenario you have given, there is no `<div class="position-relative">` so anything based on that will obviously not work.

```console
$ curl -sL 'https://www.ebay-kleinanzeigen.de/s-giessen/kettcar-daytona/k0l4710r50' | grep -i 'position-relative'

```

I believe this is due to a cookie-portal, so you need to include custom cookies in the FreshRSS advanced settings for this feed. But based on what you write, you seem to have passed this problem.

Second problem: The HTML of that page is severely broken, with more or less random opening and closing tags: https://validator.w3.org/nu/?doc=https%3A%2F%2Ftest.alapetite.fr%2Febayde.html
In particular, many unclosed article, div, ul, li.

Which means that our HTML parser might not necessarily produce a DOM identical to what you can see in your browser.

So you need to go with some safer expressions, or use an extension that can clean the source prior to processing. Quick, not perfect, example:

E.g. `//h2[contains(.,'Alternative Anzeigen in der Umgebung')]/preceding::h2[@class="text-module-begin"]/ancestor::div`

![image](https://user-images.githubusercontent.com/1008324/216824657-7c7b03c6-079a-4656-a933-c97df5e539d2.png)

![image](https://user-images.githubusercontent.com/1008324/216824802-d5a29b11-ddc3-40c1-b6f8-d8b5e57a7c02.png)

P.S. Tested with an offline copy of the page, as I did not bother fixing the cookie thing.
