### ISSUE TITLE
Can we develop the official Freshrss ios app

### ISSUE THREAD

**Issue by Whichbfj28** [FreshRSS/FreshRSS#5110]
Can we develop the official Freshrss ios app

**Comment by math-GH** [comment]
Who is "we"? Could you please explain a bit more your thoughts?

**Comment by macram** [comment]
Meanwhile you can use NetNewsWire if you want a native iOS client for FreshRSS.

**Comment by Alkarex** [comment]
Here is a list of known mobile apps that are compatible with FreshRSS:
https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps

One of the problems is that too many have tried to restart from scratch instead of building on an existing codebase, under-estimating the amounts of efforts to reach a good and usable state, and diluting the community efforts.

So I would strongly recommend picking one of the open source applications and contribute to it.

@macram if you are able to give an update regarding NetNewsWire  for the [missing columns in our table](https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps), PR welcome :-)
