### ISSUE TITLE
[BUG] Mishandling of X-Forwarded-For ?

### ISSUE THREAD

**Issue by chris42** [FreshRSS/FreshRSS#5502]
**Describe the bug**
Using nginx as proxy: When setting X-Forwarded-For as described in the docker readme, the REMOTE_ADDR in PHP gets set to the value being delivered by the forwarded for.
This renders the `trusted_sources` config unusable, as not the IP of the proxy server is checked, but of the client.
You'll then get a 403 Error when trying to connect.

**To Reproduce**

1. Using the current freshrss/freshrss:latest and nginx:lates docker image using the recommended config from the freshrss readme on docker.
2. Put `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;` in your nginx config
3. Get a phpinfo and check the REMOTE_ADDR

**Expected behavior**
Real REMOTE_ADDR  (i.e. container IP) should always be preferred to X-Forwarded-For ones.

**Additional context**
Might this be an issue like described here?
https://blog.ircmaxell.com/2012/11/anatomy-of-attack-how-i-hacked.html

**Comment by Alkarex** [comment]
Hello,
Do you say that the `REMOTE_ADDR` seen in your phpinfo contains the forwarded IP and not the proxy's IP?
If so, that looks like a wrong nginx configuration - we might have a bug in our documentation, in which nginx is proposed as an alternative (configuration fixes welcome).
`REMOTE_ADDR` is what we are using, and is also supposed to contain the proxy's IP:

https://github.com/FreshRSS/FreshRSS/blob/fc579bd2bc5406abcaa9f8dfffe4232a2e256116/lib/lib_rss.php#L654-L673

As a note, I personally avoid nginx because of the very frequent misconfiguration and surprising defaults.
For a reverse proxy, I recommend a dedicated piece of software such as Traefik, which handles all that correctly out of the box.

**Comment by chris42** [comment]
Not entirely, it depends on the configuration. It seems that setting the `X-Forwarded-For` also overwrites the `REMOTE_ADDR`. That should not happen and would be a security risk as explained in the link I attached.

This is my config. With this the proxying works as intended and the REMOTE_ADDR is the address of the proxy (For me 192.168.4.2, another docker container).

```
	    location /rss-reader/ {
		proxy_pass http://freshrss/;
	    	add_header X-Frame-Options SAMEORIGIN;
    		add_header X-XSS-Protection "1; mode=block";
	    	proxy_redirect off;
    		proxy_buffering off;
    		proxy_set_header Host $host;
    		proxy_set_header X-Real-IP $remote_addr;
    		proxy_set_header X-Forwarded-Prefix /rss-reader/;
    		proxy_set_header X-Forwarded-Proto $scheme;
    		proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header Remote-User $remote_user;
    		proxy_read_timeout 90;

                # Do Authorization
                auth_basic "Password Required";
                auth_basic_user_file /etc/freshrss/users;

    		# Forward the Authorization header for the Google Reader API.
    		proxy_set_header Authorization $http_authorization;
    		proxy_pass_header Authorization;
    	}
```

It is always good to have the client originating IP address, e.g. for logging reasons. Logs on nginx will show the originating IP, freshrss ones will only show the proxy's one.
However adding the `X-Forwarded-For` to the config like below, will overwrite the `REMOTE_ADDR`:

```
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

It is probably worthwhile to check this with another proxy, to see if nginx messes this up, or if the server config of freshrss does this. If the server config does this, I understood you are in the scenario that the link described, with a security issue.

Updating the documentation and removing the `X-Forwarded-For` will probably help on support requests, as the resulting error is quite misleading (401 instead of "non trusted ip").

**Comment by Alkarex** [comment]
Right, we need to investigate some more with various configurations.
It might be due to
https://github.com/FreshRSS/FreshRSS/blob/fc579bd2bc5406abcaa9f8dfffe4232a2e256116/Docker/FreshRSS.Apache.conf#L4

https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html#remoteipheader

Ref: https://github.com/FreshRSS/FreshRSS/pull/3226 , https://github.com/FreshRSS/FreshRSS/issues/3224 , https://github.com/FreshRSS/FreshRSS/pull/4063

**Comment by chris42** [comment]
Yes, looks like the culprit. Seems to have been introduced with #3226 to get the remote IP being logged. Instead of logging the X-Forwarded-For, the value was just channelled through `REMOTE_ADDR`?

This might be a better setup for logging: https://www.techstacks.com/howto/log-client-ip-and-xforwardedfor-ip-in-apache.html

**Comment by d-k-bo** [comment]
This is also a problem when using [Caddy](https://caddyserver.com) as a reverse_proxy.

```
@not_api not path /api/*
forward_auth @not_api localhost:9091 {
    uri /api/verify?rd=https://auth.dkbo.de/

    copy_headers Remote-User
}

reverse_proxy {
	to localhost:65261
	# FreshRSS handles X-Forwarded-For wrong
	# https://github.com/FreshRSS/FreshRSS/issues/5502
	header_up -X-Forwarded-For
}
```

**Comment by d-k-bo** [comment]
This is also a problem when using [Caddy](https://caddyserver.com) as a reverse proxy. 

```
feeds.example.com {
    // do authentication here

    reverse_proxy localhost:8080
}
```

Caddy sets `X-Forwarded-For` by default which results in the same error. It can be bypassed by removing the header.

```
reverse_proxy {
    to localhost:8080
    header_up -X-Forwarded-For
}
```

**Comment by Alkarex** [comment]
Reworked in https://github.com/FreshRSS/FreshRSS/pull/5549
Tests and feedback welcome
To ease testing, I have pushed a Docker image `freshrss/freshrss:pr5549`
