### ISSUE TITLE
UI: Thumbnail mode

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#561]
In addition to the one-line mode and the fully-expanded mode, it would be nice to have a display mode showing a thumbnail and a bit of text.
See https://diaspora-fr.org/posts/524158

**Comment by Alkarex** [comment]
Related information http://blog.feedly.com/2015/07/31/10-ways-to-optimize-your-feed-for-feedly/

**Comment by Alkarex** [comment]
@tl-pierre Désolé pour la réponse tardive. Cela requiert de faire un nouveau thème (ou en modifier un existant). Il faut un certain travail CSS. Côté serveur, FreshRSS pourrait aider en fournissant l'URL de l'image à afficher.

**Comment by ORelio** [comment]
Hi,

I recently installed FreshRSS, which works great, but I'm also missing that feature compared to my previous feed reader ([Feedly](https://feedly.com/)'s "Magazine" view), so I worked a bit on it today. Here is a proof-of-concept of how the thumbnail mode could look:

![image](https://user-images.githubusercontent.com/1128206/130358331-bf4ac410-536a-4685-83ab-7fcd145029c3.png)

Starting from the latest stable release ([1.18.1](https://github.com/FreshRSS/FreshRSS/releases/tag/1.18.1) currently), I modified [`entry_header.phtml`](https://github.com/FreshRSS/FreshRSS/blob/edge/app/views/helpers/index/normal/entry_header.phtml) to add the thumbnail and summary inside each item. I'm still not very familiar with the codebase so this is more a quick-and-dirty PoC rather than a proper feature or plugin:

```diff
diff --git a/app/views/helpers/index/normal/entry_header.phtml b/app/views/helpers/index/normal/entry_header.phtml
--- a/app/views/helpers/index/normal/entry_header.phtml
+++ b/app/views/helpers/index/normal/entry_header.phtml
@@ -30,7 +30,17 @@
        ?><li class="item website"><a href="<?= _url('index', 'index', 'get', 'f_' . $this->feed->id()) ?>" title="<?= _t('gen.action.filter') ?>">
                <?php if (FreshRSS_Context::$user_conf->show_favicons): ?><img class="favicon" src="<?= $this->feed->favicon() ?>" alt="<E2><9C><87>" loading="lazy" /><?php endif; ?>
                <span><?= $this->feed->name() ?></span></a></li>
-       <li class="item title" dir="auto"><a target="_blank" rel="noreferrer" href="<?= $this->entry->link() ?>"><?= $this->entry->title() ?><?php
+       <li class="item title" dir="auto"><a target="_blank" rel="noreferrer" href="<?= $this->entry->link() ?>"><?php
+               $enclosures = $this->entry->enclosures();
+               ?><div class="enclosure"><?php
+               foreach ($enclosures as $enclosure):
+                       if (!empty($enclosure) && !empty($enclosure['url'])):
+                               ?><img src="<?= $enclosure['url'] ?>"><?php
+                               break;
+                       endif;
+               endforeach;
+               ?></div>
+               <?= $this->entry->title() ?><?php
                if ($topline_display_authors):
                        ?><span class="author"><?php
                        $authors = $this->entry->authors();
@@ -42,7 +52,10 @@
                                }
                        }
                        ?></span><?php
-               endif;
+               endif; ?>
+               <div class="summary">
+                       <?= substr(strip_tags($this->entry->content()), 0, 500) ?>
+               </div><?php
        ?></a></li>
        <?php if ($topline_date) { ?><li class="item date"><time datetime="<?= $this->entry->machineReadableDate() ?>"><?= $this->entry->date() ?></time>&nbsp;</li><?php } ?>
        <?php if ($topline_link) { ?><li class="item link"><a target="_blank" rel="noreferrer" href="<?= $this->entry->link() ?>" title="<?=
```

The corresponding CSS is inserted using [CustomCSS](https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS) on top of the default [Origine](https://github.com/FreshRSS/FreshRSS/tree/edge/p/themes/Origine) theme:
```css
div.enclosure {
	float: left;
	margin: 10px;
	width: 128px;
	height: 80px;
}

div.enclosure > img {
	width: 100%;
	height: 100%;
	object-fit: cover;
}

div.summary {
	color: #666;
	font-size: 0.9em;
	line-height: 1.5em;
	font-weight: normal;
	white-space: initial;
	max-height: 40px;
	overflow: hidden;
	text-overflow: ellipsis;
}

.flux:not(.current):hover .item.title {
	position: static;
}
```
I think this display mode could be added as a separate view in addition to the existing "normal", "reader", "global" views.

Any thought about this?

**Comment by Frenzie** [comment]
It strikes me as more of an alternative style for the same view, comparable to content width narrow/medium/wide/etc. in Settings → Display. Or do you envision users/yourself toggling between them frequently?

**Comment by ORelio** [comment]
> do you envision users/yourself toggling between them frequently?

No. A setting like those in Settings/Display would also work for me 👍
I'll investigate this when I've got more time to work on it.

**Comment by Alkarex** [comment]
That looks good @ORelio 👍🏻 
Maybe as an option as @Frenzie says:
![image](https://user-images.githubusercontent.com/1008324/130362394-aaedc3b4-952b-40e9-b4ec-08fc4bfa70bb.png)

**Comment by ORelio** [comment]
I've submitted the feature as a pull request. The toggles are located in the Article icons section as requested 🙂
