### ISSUE TITLE
[BUG] OIDC_X_FORWARDED_HEADERS is not actually optional per docs?

### ISSUE THREAD

**Issue by yaleman** [FreshRSS/FreshRSS#5775]
**Describe the bug**
When configuring OIDC per the documentation it mentions that `OIDC_X_FORWARDED_HEADERS` is optional - but the container crashes on startup with the following:

> [Sun Oct 29 22:12:49.036206 2023] [core:warn] [pid 1] AH00111: Config variable ${OIDC_X_FORWARDED_HEADERS} is not defined

**To Reproduce**

1. configure OIDC, but don't specify a value for `OIDC_X_FORWARDED_HEADERS`
2. start the container

**Expected behavior**

The container to start

**Screenshots**
n/a

**Environment information (please complete the following information):**
- Device: n/a
- OS: n/a
- Browser: n/a
- FreshRSS version:  freshrss/freshrss:edge-arm     (docker.io/freshrss/freshrss@sha256:909496d8475d3e02e84d2af05c37cb7f75b334973b8275d8238a66cadbda5057)
- Installation type: Docker

**Additional context**

Setting it to an empty value gets this:

```
AH00526: Syntax error on line 53 of /etc/apache2/sites-enabled/FreshRSS.Apache.conf:
OIDCXForwardedHeaders requires at least one argument, Sets the value of the interpreted X-Forwarded-* headers.
```

**Comment by yaleman** [comment]
... just found #5722 which is crashing it anyway, but I'm guessing this is an issue either way?

**Comment by Alkarex** [comment]
The warning is expected if the value is not provided, but there should be no crash on `x86_64`. The crash with or without this variable is also known on ARM https://github.com/FreshRSS/FreshRSS/issues/5722
I believe this is what you are experiencing. So nothing new besides the existing https://github.com/FreshRSS/FreshRSS/issues/5722

On ARM, it would be interesting the test the experimental support in Alpine https://github.com/FreshRSS/FreshRSS/pull/5764
* Use https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/Dockerfile-Newest
* Comment-out the IfModule section in https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/FreshRSS.Apache.conf , because the test does not seem to work on Alpine at the moment:

https://github.com/FreshRSS/FreshRSS/blob/58179a33a50e35b6f3eeb7af2ac1930e8a615c78/Docker/FreshRSS.Apache.conf#L21-L23

**Comment by yaleman** [comment]
Ah, you're right, thanks!
