### ISSUE TITLE
[BUG] Regression with 1.22.1: feeds are not updated any more (probably related to TRUSTED_PROXY env var with space)

### ISSUE THREAD

**Issue by mossroy** [FreshRSS/FreshRSS#5792]
**Describe the bug**
Since the upgrade of my FreshRSS instance to 1.22.1, the feeds are not updated any more.
It was working fine with docker image 1.22.0, and even with this one: https://hub.docker.com/layers/freshrss/freshrss/edge-arm/images/sha256-c62c0655f28d6e87f0433aeca0ad5fd51e14d3d2e2bf80f4e9360de35ed0909f (between 1.22.0 and 1.22.1)

**To Reproduce**
1. Use docker image of FreshRSS 1.22.1 (I did under kubernetes, but it probably does not matter)
2. Pass these environment variables: 

- TZ: Europe/Paris
- CRON_MIN: 1,6,11,16,21,26,31,36,41,46,51,56
- TRUSTED_PROXY: 10.0.0.0/8 192.168.0.0/24

3. Start the container (and configure at least a feed if there isn't any)
4. Wait 5 minutes to check if feeds are updated (it can be seen in stdout logs of the container, looking for string "SimplePie")

**Expected behavior**
Feeds should be updated

**Environment information (please complete the following information):**

- Device: Desktop
- OS: Ubuntu 22.04
- Browser: Firefox 119.0
- FreshRSS version: 1.22.1
- Database version: PostgreSQL 14.9
- PHP version: 8.2.7
- Installation type: docker image 1.22.1-arm (but should be the same with amd), running on kubernetes (k3s)

**Additional context**
A workaround is to not pass TRUSTED_PROXY env var.
I suspect it's because its value contains a space, which would not be properly handled by the changes of this commit: https://github.com/FreshRSS/FreshRSS/commit/de51f6e7a042788532aca5e437634da8cdbbbac0 : some quotes might be needed around the value of each "export" line. But I'm not 100% sure it's the reason

Using 1.22.0 docker image is also a workaround

**Comment by tyrossel** [comment]
I also have this problem, but my TRUSTED_PROXY doesn't contain any space in it.

Manual update of feeds works correctly.

Note: I also have some error `oidc_check_x_forwarded_hdr: header X-Forwarded-Port received but OIDCXForwardedHeaders not configured for it`, but I'm not sure it's related.

I'm currently testing with 1.22.0 to verify it was working fine before.

**Comment by Dominion0815** [comment]
Same Problem here with Docker and 1.22.1. Version 1.22.0 working fine!

CRON_MIN: '2,12,22,32,42,52'
TZ: Europe/Berlin
TRUSTED_PROXY: 172.16.0.0/20

same without TRUSTED_PROXY !

**Comment by Alkarex** [comment]
Might be due to https://github.com/FreshRSS/FreshRSS/pull/5733

**Comment by snailium** [comment]
Same here. I don't think this is related to TRUSTED_PROXY.

For my setup,
```
CRON_MIN: "*/20"
TZ: "America/Toronto"
```

TRUSTED_PROXY is not set. So it should be empty.

Feeds don't update.

I cannot connect to the terminal. Everytime I tried terminal, the container crashes and restarts.

--------------------

Edit: I know where the problem is, after I managed to get into container terminal.

The crontab entry as following.
```
*/20 * * * * . /var/www/FreshRSS/Docker/env.txt;                su www-data -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php'              2>> /proc/1/fd/2 > /tmp/FreshRSS.log
```

So I manually run the command from container terminal. And I got the following error.
```
bash: /var/www/FreshRSS/Docker/env.txt: line 11: unexpected EOF while looking for matching `''
```

On Line 11 of env.txt, it is my MariaDB password, which has a single quote in it.

@mossroy @tyrossel @Dominion0815 , please check your config for single or double quote, especially in any password.

------------------------

Edit 2:

I'm using container linking to MariaDB 10. It seems docker automatically passes all MariaDB's container environment variables to FreshRSS's container. The problematic one is `MARIADB_10_ENV_MARIADB_ROOT_PASSWORD`.

My solution is to user `MARIADB_10_ENV_MARIADB_ROOT_PASSWORD_HASH` instead of password in plain text. And it seems cron starts working again.

**Comment by Alkarex** [comment]
OK, might be due to https://github.com/FreshRSS/FreshRSS/pull/5772 then

**Comment by snailium** [comment]
Yes, confirm cron is working after changing plain mariadb password to password hash.

**Comment by Alkarex** [comment]
Fix in https://github.com/FreshRSS/FreshRSS/pull/5795

**Comment by Alkarex** [comment]
If you want to test, I have made an image available `freshrss/freshrss:pr5795`
