### ISSUE TITLE
Problem with filtering by date

### ISSUE THREAD

**Issue by giampieropace** [FreshRSS/FreshRSS#5864]
I installed today freshRSS and added my feeds, but I'm facing this problem: the feeds are first grouped and then sorted by date.

E.g.:

> feed 1 - title - 11 nov 2023
> feed 1 - title - 10 nov 2023
> feed 1 - title - 09 nov 2023
> feed 1 - title - 08 nov 2023
> feed 2 - title - 11 nov 2023
> feed 2 - title - 10 nov 2023
> feed 2 - title - 09 nov 2023
> feed 2 - title - 08 nov 2023
> and so on...

What I want is to have all in cronological order:

> feed 1 - title - 11 nov 2023
> feed 2 - title - 11 nov 2023
> feed 1 - title - 10 nov 2023
> feed 2 - title - 10 nov 2023
> feed 1 - title - 09 nov 2023
> feed 2 - title - 09 nov 2023
> feed 1 - title - 08 nov 2023
> feed 2 - title - 08 nov 2023

If I click the "older/newest first" button the situation doesn't change, feeds are inverted, but always grouped.

[Here is a short video recording of the issue](https://screenrec.com/share/HGYvbo5hys).

Am I missing something?

**Comment by Alkarex** [comment]
Hello,
This behaviour occurs when adding new feeds one at a time (importing several feeds by OPML mitigates the issue).
This is by design at the moment, and the apparent problem becomes reduced when feeds gets regularly refreshed.

The order you see **is** chronological, just the chronology of when articles have been discovered/received (just like e.g. by e-mail clients), not the date the articles advertise (the advertised date is not a robust sorting criteria as dates might very well a long time in the past or in the future, as in usual in the case of academic articles, book publications, chapters of science fiction, etc.)

A longer explanation of the rationale for the current behaviour can be see on e.g.

- https://github.com/FreshRSS/FreshRSS/issues/1771#issuecomment-359195655
- https://github.com/FreshRSS/FreshRSS/issues/2083#issuecomment-433622668

And there is a plan to customise sorting (on different criteria including advertised date):

- https://github.com/FreshRSS/FreshRSS/issues/2596#issuecomment-1541934281
