### ISSUE TITLE
[BUG] Sidebar not showing favicons + Database optimization / recommended database

### ISSUE THREAD

**Issue by katekyonni** [FreshRSS/FreshRSS#6096]
Hi, thanks for this great project!
I just installed FreshRSS and imported all my feeds from a different reader and have the following problem:

**Describe the bug**
The Sidebar is not showing favicons except for the currently selected feed.

Please see the following videos:

This one is from my instance
[Screencast from 2024-02-12 19-54-56.webm](https://github.com/FreshRSS/FreshRSS/assets/12618582/c2076447-22bc-4638-95e9-7b00272b9654)

this one is from the demo at https://demo.freshrss.org/ (how it should be)
[Screencast from 2024-02-12 19-56-37.webm](https://github.com/FreshRSS/FreshRSS/assets/12618582/9841a17f-1d43-442d-8b41-208a9f498d37)

You can also see, that when clicking on a feed, the site refreshes a little bit slow, but that might be because of the number of unread articles (32k 😅)

**Environment information (please complete the following information):**
- Device: Desktop PC
- OS: Fedora 39
- Browser: Brave 1.62.162 (tried multiple browsers, also mobile)
- FreshRSS version: 1.23.1
- Database version: MariaDB
- PHP version: 8.2.7
- Installation type: Official Docker image (freshrss/freshrss:latest)

**Comment by Alkarex** [comment]
Could you please try to click *Optimize database*?
![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/71da00d7-52fb-4945-8aec-e97e6a22f68c)

**Comment by Alkarex** [comment]
And do you have anything in your FreshRSS or MariaDB logs?

**Comment by Alkarex** [comment]
For the record, I have observed performance problems with MariaDB / MySQL for larger amounts of articles.
If you can, you could compare with PostgreSQL or even SQLite.

**Comment by katekyonni** [comment]
It feels like optimizing the database helped with the speed a bit, thank you!

I was actually using SQLite at first and switched to MariaDB because of your comment, where you said it's better for a single user with a lot of feeds: https://github.com/FreshRSS/FreshRSS/issues/2289#issuecomment-477657944
Would you not recommend it anymore?

I did not observe any errors in the FreshRSS or MariaDB logs

Do you have an idea, why the favicons are not showing in the sidebar?

**Comment by Alkarex** [comment]
> Would you not recommend it anymore?

Indeed, there are visibly some performance issues with MySQL / MariaDB when working with 10k unread articles. The performance problems are reproducible when running a basic SQL request manually, so this is not due to e.g. many FreshRSS calls.
It seems to be some poorly performing indexes, but would require more investigation (help welcome)
With my own tests (might vary due to a number of factors): 🐇 PostgreSQL > SQLite >> MySQL > MariaDB 🐢
See https://github.com/FreshRSS/FreshRSS/pull/5648#issuecomment-1715843198

> Do you have an idea, why the favicons are not showing in the sidebar?

Favicons not showing is another issue. If you have many (1k+) feeds, they are automatically simplified, but this can be tuned:
https://github.com/FreshRSS/FreshRSS/blob/06570b30f0af1b4e4b4f1723bbb2ad0a4b83db6c/config-user.default.php#L97-L101

**Comment by katekyonni** [comment]
That explains why the favicons are not displayed, thank you for clearing that up. I tried enabling them, but I definitely felt the performance worsening, so I disabled them again. 😄

I also switched to PostgreSQL according to this [example](https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose-db.yml) with the helpful [cli import/export-sqlite tools](https://github.com/FreshRSS/FreshRSS/blob/edge/cli/README.md#user) you provide.
Thank you so much for helping me optimize my setup! 😊
