### ISSUE TITLE
Warning icons for disabled feeds

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#6113]
> I am myself running several instances, each with multiple broken feeds, and without problem.

I keep around a number of feeds that once were for various reasons, as a random example `http://feeds.feedburner.com/carbonbrief`. (Once in a while one returns after a hiatus of years!) That shows up as a lot of warnings that I'm not particularly interested in from the main interface.

<img src=https://github.com/FreshRSS/FreshRSS/assets/202757/acb75c4f-9e28-407f-bdce-910d30373699 width=200>

_Originally posted by @Frenzie in https://github.com/FreshRSS/FreshRSS/issues/6089#issuecomment-1951379351_

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6114

**Comment by math-GH** [comment]
@Frenzie  What are the reasons for the warnings?

**Comment by Frenzie** [comment]
@math-GH The reason can be anything from 404 to 301 to a place without a valid feed. It doesn't matter what the reason is. The problem is simply that there are all these warnings visible in the main UI that I don't care to see.

@Alkarex I'm not really satisfied by your proposed solution either; that's merely one particular edge case. ^_^ There are also feeds where the only thing I don't want is the warning but I still want it to try once a week or some such. (Perhaps the warning could return again at that point.)

**Comment by Alkarex** [comment]
Muted feeds are not fetched again, so their error status will not change. Furthermore, you can still see feeds with errors in the feeds management and also filter to see only the feeds with errors.

**Comment by Frenzie** [comment]
Yes, but "muting" (I think I once planned to change this misleading word and forgot about it) is something I only want to do in some very particular circumstances. I don't want to <del>mute</del><ins>disable it from doing anything</ins> something just because it has a warning.

**Comment by Alkarex** [comment]
My PR is only affecting muted feeds, not the others.

**Comment by Frenzie** [comment]
Right, but I didn't think anyone was talking about those considering the context. Muted feeds don't time out etc. ;-)

**Comment by Alkarex** [comment]
Then in your case, my PR will not change anything. In my case, I have muted (disabled) most of my broken feeds, so it does help reducing the numbers of warning icons :-)

**Comment by Frenzie** [comment]
My point exactly. :-P (Keep in mind it says "fix #6113" ^_^)

**Comment by Frenzie** [comment]
I hasten to add I haven't done anything about this myself for many years so it's far from bothersome, though I did now realize the warning signs are completely meaningless visual noise to me with no actual informational value.

**Comment by Alkarex** [comment]
Ok. This issue is specifically about muted (disabled) feeds. I thought your case was also related to that, but it is not, so it can be another issue :-)

**Comment by Frenzie** [comment]
It's not *not* about it, but it's only a subcategory of warning icons I don't care to see. For many I think I'd like to acknowledge it with something like a "don't mute but don't bother me about it for x time".

For example due to me completely ignoring these warnings I only just noticed `https://drewdevault.com/feed.xml` (404) has apparently moved to `https://drewdevault.com/blog/index.xml` (without a 301).
