### ISSUE TITLE
Blast! Verify your database configuration. : Access to database is denied for `freshrss_rw`: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mariadb failed: No such host is known. 

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#6116]
I've almost installed FreshRSS for the first time (thanks). 

But I get this error when I click Submit in Database configuration:

- Blast! Verify your database configuration. : Access to database is denied for `freshrss_rw`: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mariadb failed: No such host is known. 
 
I have been following this guide: https://i12bretro.github.io/tutorials/0234.html (video here: https://www.youtube.com/watch?v=u_iQufgPkMo&t=6s ).
 
So the problem happens at the end of step 19.

- Windows 11 Home - Version 23H2
- Firefox 122.0.1
- FreshRSS 1.23.1
- Database version: [e.g. Mysql 5.7]
   I don't know how to check this.
   In C:\xampp\mysql\mysql_error.log it says:

   2024-02-19 21:55:07 0 [Note] Starting MariaDB 10.4.32-MariaDB source revision c4143f909528e3fab0677a28631d10389354c491 as process 11908
   2024-02-19 21:55:07 0 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
   2024-02-19 21:55:07 0 [Note] InnoDB: Uses event mutexes
   2024-02-19 21:55:07 0 [Note] InnoDB: Compressed tables use zlib 1.3
   2024-02-19 21:55:07 0 [Note] InnoDB: Number of pools: 1
   2024-02-19 21:55:07 0 [Note] InnoDB: Using SSE2 crc32 instructions
   2024-02-19 21:55:07 0 [Note] InnoDB: Initializing buffer pool, total size = 16M, instances = 1, chunk size = 16M
   2024-02-19 21:55:07 0 [Note] InnoDB: Completed initialization of buffer pool
   2024-02-19 21:55:07 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=300288
   2024-02-19 21:55:07 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
   2024-02-19 21:55:07 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
   2024-02-19 21:55:07 0 [Note] InnoDB: Creating shared tablespace for temporary tables
   2024-02-19 21:55:07 0 [Note] InnoDB: Setting file '\xampp\mysql\data\ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
   2024-02-19 21:55:07 0 [Note] InnoDB: File '\xampp\mysql\data\ibtmp1' size is now 12 MB.
   2024-02-19 21:55:07 0 [Note] InnoDB: Waiting for purge to start
   2024-02-19 21:55:07 0 [Note] InnoDB: 10.4.32 started; log sequence number 300297; transaction id 170
   2024-02-19 21:55:07 0 [Note] InnoDB: Loading buffer pool(s) from C:\xampp\mysql\data\ib_buffer_pool
   2024-02-19 21:55:07 0 [Note] Plugin 'FEEDBACK' is disabled.
   2024-02-19 21:55:07 0 [Note] InnoDB: Buffer pool(s) load completed at 240219 21:55:07
   2024-02-19 21:55:07 0 [Note] Server socket created on IP: '::'.

- PHP version: [e.g. PHP 7.4]
   Again, not sure how to check.
   C:\xampp\php\php-win.exe has a modification date of 25 ‎October ‎2023, ‏‎04:56:48

- Installation type: [e.g. Yunohost]
   Don't know

- I used this: **xampp-portable-windows-x64-8.2.12-0-VS16.zip**

I'll be very grateful for any help.

**Comment by Frenzie** [comment]
It's generally the easiest to use SQLite btw.

**Comment by rusegithub** [comment]
@Frenzie Thanks for replying.

I could do that (although I've no idea how?) but, in trying to find out how, I found this: https://github.com/FreshRSS/FreshRSS/issues/961 where the person wants to migrate from SQLite to Mysql. 

So I wonder if I'm better sticking with Mysql?

Anyway, in FreshRSS, in my browser, I went back and changed to SQLite and pressed Submit. Now I'm ashed for a username and password. I don't know what to put in there.

Then I tried to remember what it said after Mysql, to write it in here so I went to http://localhost/freshrss/ and chose English but the next page had this at the bottom:

Fatal error: Uncaught Minz_FileNotExistException: File not found: `C:\xampp\htdocs\freshrss/data/users/_/config.php` in C:\xampp\htdocs\freshrss\lib\Minz\Configuration.php:50 Stack trace: #0 C:\xampp\htdocs\freshrss\lib\Minz\Configuration.php(120): Minz_Configuration::load('C:\\xampp\\htdocs...') #1 C:\xampp\htdocs\freshrss\lib\Minz\Configuration.php(33): Minz_Configuration->__construct('user', 'C:\\xampp\\htdocs...', NULL, NULL) #2 C:\xampp\htdocs\freshrss\app\Models\UserConfiguration.php(80): Minz_Configuration::register('user', 'C:\\xampp\\htdocs...', NULL) #3 C:\xampp\htdocs\freshrss\app\install.php(303): FreshRSS_UserConfiguration::init('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\freshrss\app\install.php(478): freshrss_already_installed() #5 C:\xampp\htdocs\freshrss\app\install.php(815): printStep1() #6 C:\xampp\htdocs\freshrss\p\i\index.php(32): require('C:\\xampp\\htdocs...') #7 {main} thrown in C:\xampp\htdocs\freshrss\lib\Minz\Configuration.php on line 50

I didn't have that before.

Then I realised that I had two browser windows open and thought maybe it was because of that.

So I closed them both and went to http://localhost/freshrss again which, after selecting English, automatically takes me to this page http://localhost/freshrss/p/i/index.php?step=1 and it still says this at the bottom:

 Fatal error: Uncaught Minz_FileNotExistException: File not found: `C:\xampp\htdocs\freshrss/data/users/_/config.php` in C:\xampp\htdocs\freshrss\lib\Minz\Configuration.php:50 Stack trace: #0 C:\xampp\htdocs\freshrss\lib\Minz\Configuration.php(120): Minz_Configuration::load('C:\\xampp\\htdocs...') #1 C:\xampp\htdocs\freshrss\lib\Minz\Configuration.php(33): Minz_Configuration->__construct('user', 'C:\\xampp\\htdocs...', NULL, NULL) #2 C:\xampp\htdocs\freshrss\app\Models\UserConfiguration.php(80): Minz_Configuration::register('user', 'C:\\xampp\\htdocs...', NULL) #3 C:\xampp\htdocs\freshrss\app\install.php(303): FreshRSS_UserConfiguration::init('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\freshrss\app\install.php(478): freshrss_already_installed() #5 C:\xampp\htdocs\freshrss\app\install.php(815): printStep1() #6 C:\xampp\htdocs\freshrss\p\i\index.php(32): require('C:\\xampp\\htdocs...') #7 {main} thrown in C:\xampp\htdocs\freshrss\lib\Minz\Configuration.php on line 50
 
 Please can you help.

**Comment by ghost** [comment]
@Frenzie Thanks.

I could do that (although I've no idea how?) but, in trying to find out how, I found this: https://github.com/FreshRSS/FreshRSS/issues/961 where the person wants to migrate from SQLite to Mysql. 

So I wonder if I'm better sticking with Mysql?

If I'm better off with SQLite, please could you guide me how to do that.

As I said, I've been following this guide: https://i12bretro.github.io/tutorials/0234.html - except that at the end I go to http://localhost/freshrss - as it says in the video https://www.youtube.com/watch?v=u_iQufgPkMo&t=6s - instead of http://DNSorIP:8089.

Then I select a Language and click Submit
Click the Go to the next step button
Complete the database configuration form as follows

Type of database: MySQL
Host: mariadb
Database username: freshrss_rw
Database password: Fr3s4R$S!!
Database: freshrss
Table prefix:

What should I do instead of the above in order to use SQLite?

**Comment by ghost** [comment]
I've sorted this out now. I should not have been specifying a host.

But, @Frenzie, if you have any advice on using SQLite instead, I'd still appreciate it.

**Comment by Alkarex** [comment]
SQLite is built-in and easiest and has fine performances for most cases.
If not enough, PostgreSQL would be the more powerful alternative (cf. https://github.com/FreshRSS/FreshRSS/pull/5648#issuecomment-1715843198 )
