### ISSUE TITLE
[BUG]The subscription source has garbled characters.

### ISSUE THREAD

**Issue by LinxHex** [FreshRSS/FreshRSS#6180]
**Describe the bug**
The subscription source has garbled characters.
https://peterwunder.de/projects/achievements/atom.xml

**To Reproduce**
It can be reproduced after subscription.

**Expected behavior**
The content is displayed normally.

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/92703641/bf37ffcc-7469-4917-bb5f-e7ba1f5072d4)

**Environment information (please complete the following information):**
- OS: Windows 11 23H2
- Browser: Chrome 122.0.6261.95
- FreshRSS version: 1.23.1
- PHP version: PHP 8.2.7
- Installation type: Docker Compose

**Comment by Alkarex** [comment]
Could you please try again with the edge version of FreshRSS?

**Comment by LinxHex** [comment]
> Could you please try again with the edge version of FreshRSS?

<img width="855" alt="PixPin_2024-03-08_17-46-17" src="https://github.com/FreshRSS/FreshRSS/assets/92703641/62ec763b-1bd4-4f8e-b863-ed8241c6de45">
<img width="841" alt="PixPin_2024-03-08_17-46-29" src="https://github.com/FreshRSS/FreshRSS/assets/92703641/b4527506-295a-4e36-988b-c20cdfdf4a99">

I have updated it to Edge, but it still doesn't work.

**Comment by Alkarex** [comment]
The bug comes from the feed, which contains `<content type="CDATA">` which is invalid.
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpeterwunder.de%2Fprojects%2Fachievements%2Fatom.xml

It should be `<content type="html">` instead.

The reason of the wrong characters are because such an unknown type must be processed as Base64 according to the specification
https://www.rfc-editor.org/rfc/rfc4287#section-4.1.3.3

So it could be good if you could inform the webmaster of the bug.

This seems to be a not-so-unique error:
https://github.com/search?type=code&auto_enroll=true&q=%3Ccontent+type%3D%22CDATA%22%3E
(this includes apparently a feed generator library in Python 🤦🏻‍♂️ https://github.com/lkiesow/python-feedgen Anyone to send them a bug report? https://github.com/lkiesow/python-feedgen/blob/97260abb1793eb164c458c10b493690beb413f6d/feedgen/entry.py#L29C1-L57C35)

So we could consider adding a compatibility for those bad feeds / bad libraries.
Please try this patch https://github.com/FreshRSS/FreshRSS/pull/6181

```yml
  freshrss:
    image: freshrss/freshrss:6181
    build:
      context: https://github.com/Alkarex/FreshRSS.git#atom-cdata
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

**Comment by Alkarex** [comment]
Ah, someone has sent a fix already https://github.com/lkiesow/python-feedgen/pull/123

**Comment by Alkarex** [comment]
The problematic feed does not seem to exist anymore, and the (probable) library that was generating it has a PR (consider voting on it),
