### ISSUE TITLE
Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.

### ISSUE THREAD

**Issue by rosolko** [FreshRSS/FreshRSS#6196]
**Describe the bug**
Hi, I have a problem with two feeds:
1. https://www.androidpolice.com/feed/
3. https://4pda.to/feed/

Both of them show an error `Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.` when I trying to add as feed 

Feed validity page said that feeds are valid:
1. https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.androidpolice.com%2Ffeed%2F
2. https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2F4pda.ru%2Ffeed%2F

Logs:
1.  cURL error 56: HTTP/2 stream 1 was reset [https://www.androidpolice.com/feed/] 
2. cURL error 22: The requested URL returned error: 403 [https://4pda.ru/feed/] 

I'm using https://freshrss.prodottoinrete.com server 

**Environment information (please complete the following information):**
- FreshRSS version: 1.22.1

**Comment by Alkarex** [comment]
Try to `curl -v 'https://4pda.to/feed/'` from the server if possible (second best, from your own computer)

* https://www.androidpolice.com/feed/ works for me, so it might be due to IP filtering, HTTP/2 problem...
* https://4pda.to/feed/ seems to be broken due to the use of Cloudflare

What you can do is also try to fetch the feed(s) through a proxy with another IP

**Comment by rosolko** [comment]
@Alkarex You were right. Seems like the problem was caused by IP filtering, HTTP/2 problem. Let's close it. Thanks!
