### ISSUE TITLE
[Bug] Docker compose instructions use invalid flags

### ISSUE THREAD

**Issue by JoshuaVandaele** [FreshRSS/FreshRSS#6411]
### Describe the bug

Certain flags in the instructions for Docker compose FRESHRSS setup use incorrect flags, for example using `api-enabled` instead of `api_enabled`

### To Reproduce

1. Follow the instructions
2. The installer errors out with `unknown options`

### FreshRSS version

N/A

### Environment information

N/A

**Comment by Frenzie** [comment]
Overlooked after #6028.

**Comment by Alkarex** [comment]
Hello,
The problem lies with the fact that we are just about to release 1.24.0.

* The documentation for stable / slow releases is https://github.com/FreshRSS/FreshRSS/blob/latest/Docker/README.md
* The documentation for rolling release is https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md

Please try with `freshrss/freshrss:edge`

**Comment by Frenzie** [comment]
Oops, I misread the problem the wrong way around. :-)
