### ISSUE TITLE
[Bug] opml/xml export does not contain css selector

### ISSUE THREAD

**Issue by sotn3m** [FreshRSS/FreshRSS#6433]
### Describe the bug

When downloading opml as xml from the feed management screen, the export misses css selector (`frss:cssFullContent`).
![image](https://github.com/FreshRSS/FreshRSS/assets/11821473/843b9092-9cc2-40d8-bcfd-5036a44f3867)

It works correctly when exporting all subscriptions though.

### To Reproduce

1. Go to subscription management
2. Choose a cog of a single feed that has CSS selector chosen.
3. Click on "Download" button at the end of the sidebar.

### Expected behavior

Complete file

### FreshRSS version

1.23.2-dev

### Environment information

- Database version: PostgreSQL 16
- docker: `freshrss/freshrss:edge`
- Raspberry Pi 4
- OS: Win11
- Browser: Edge

**Comment by math-GH** [comment]
There are some settings missed in the export

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/6435

**Comment by math-GH** [comment]
fields, that will not be exported:
- description (usually imported from the feed. Just to keep in mind, that here is an feature request that keeps the notices there)
- (category)
- (visibility)
- (automatically refresh)
- muted checkbox
- HTTP username + password (for security reasons it should no be exported)
- filter action dropdown lists
- max number of articles to keep unread
- proxy protocol (but the proxy address will be exported). When importing, it is impossible to import `frss:CURLOPT_PROXY`, because the protocol is missed, that means that the address will not be imported/stored
- timeout in seconds
- Verify SSL security
- Always clear cache checkbox

**Comment by sotn3m** [comment]
Two fields/attributes were added in comparison to my previous export:
* `frss:cssFullContent`
* `description`, which seems to contradict the above - unless "html + xpath" is supposed to export it.

**Comment by Alkarex** [comment]
I am not sure it makes sense to export all the parameters in OPML, but maybe a few more (but let's keep this issue focussed on bug fixing for 1.24 and open a new one for other aspects). The full SQLite-based export is there when there is a need to export everything.
@math-GH Could you please provide more details for the `CURLOPT_PROXY` bug? (here or in another issue)

**Comment by math-GH** [comment]
> I am not sure it makes sense to export all the parameters in OPML, but maybe a few more (but let's keep this issue focussed on bug fixing for 1.24 and open a new one for other aspects). The full SQLite-based export is there when there is a need to export everything. 

IMHO we should have an overview which options will be exported and which not. Currently it looks like that all options will be exported to the OPML file. What do you think about this idea: add a link next to the OPML export button. The link goes to the documentation, that gives a better overview of exported fields.

**Comment by math-GH** [comment]
>  @math-GH Could you please provide more details for the `CURLOPT_PROXY` bug? (here or in another issue)

see #6438

**Comment by Alkarex** [comment]
> What do you think about this idea: add a link next to the OPML export button

Good idea
