### ISSUE TITLE
Uberspace: Unable to load content: `Error fetching content: HTTP code 200`

### ISSUE THREAD

**Issue by Lucki** [FreshRSS/FreshRSS#6469]
Changing this line makes it working again:
https://github.com/FreshRSS/FreshRSS/blob/227233b4efab7618de77eef7dbd06abdbe51cf1e/lib/lib_rss.php#L456

~~~ diff
-		CURLOPT_ENCODING => '',	//Enable all encodings
+		CURLOPT_ENCODING => 'deflate, gzip',
~~~

It seems that FreshRSS doesn't know what to do with the brotli encoding.

_Originally posted by @Lucki in https://github.com/FreshRSS/FreshRSS/discussions/6410#discussioncomment-9456715_

**Comment by Alkarex** [comment]
This is handled by the curl library and as such is system-dependant. Could you please provide a bit of information regarding the system on which it was tested (OS, versions...). Docker?

**Comment by Lucki** [comment]
It's Uberspace 7 in version 7.15.15
Plain FreshRSS 1.23.1 - no docker.
I can choose between PHP 8.1..8.3 - all have the same issue. https://manual.uberspace.de/lang-php/

~~~
$ php --version
PHP 8.1.28 (cli) (built: Apr 10 2024 05:53:50) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.28, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.28, Copyright (c), by Zend Technologies
~~~

~~~
$ curl --version
curl 8.7.1 (x86_64-pc-linux-gnu) libcurl/8.7.1 OpenSSL/1.0.2k-fips zlib/1.2.7 brotli/1.0.9 libidn2/2.3.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.10.0 nghttp2/1.33.0 OpenLDAP/2.4.44
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe UnixSockets
~~~

**Comment by Alkarex** [comment]
Do you know what kind of Linux distribution that is?

**Comment by Alkarex** [comment]
Since there is no such problem with our Docker images (Debian or Alpine) and my tests on Ubuntu, I believe there is a misconfiguration with Uberspace.de hosting servers.

Would you be able to make a minimum example, which does not work in your case? For instance:

```php
<?php
<?php
$ch = curl_init('https://www.tagesschau.de/europawahl/wahl/eu-spitzenkandidaten-100.html');
curl_setopt_array($ch, [
		CURLOPT_HEADER => true,
		CURLOPT_TIMEOUT => 10,
		CURLOPT_ENCODING => '',	//Enable all encodings
	]);
curl_exec($ch);
print_r($info);
curl_close($ch);
```

<details>
<summary>Docker: Debian 12 with PHP 8.2.18</summary>
<pre>
HTTP/2 200 
content-type: text/html;charset=UTF-8
x-generated-by: tagesschau-live-7579697477-zfmfv
content-language: en-US
x-content-type-options: nosniff
permissions-policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
x-varnish: 1934232
x-varnish-cache: miss cached
x-frame-options: sameorigin
content-encoding: br
cache-control: max-age=159
date: Thu, 16 May 2024 12:44:56 GMT
content-length: 64974
strict-transport-security: max-age=15768000 ; includeSubDomains ; preload

<!DOCTYPE html>
...
</pre>
</details>

<details>
<summary>Docker: Alpine Linux 3.19 with PHP 8.2.19</summary>
<pre>
HTTP/2 200 
content-type: text/html;charset=UTF-8
x-generated-by: tagesschau-live-7579697477-zfmfv
content-language: en-US
x-content-type-options: nosniff
permissions-policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
x-varnish: 1934232
x-varnish-cache: miss cached
x-frame-options: sameorigin
content-encoding: br
cache-control: max-age=45
date: Thu, 16 May 2024 12:46:50 GMT
content-length: 64974
strict-transport-security: max-age=15768000 ; includeSubDomains ; preload

<!DOCTYPE html>
...
</pre>
</details>

**Comment by Lucki** [comment]
> Do you know what kind of Linux distribution that is?

Uberspace 6 was based of CentOS, I can't tell for Uberspace 7. Maybe @beerisgood knows how to get that information?

> Would you be able to make a minimum example, which does not work in your case?

I created that file with your example in my home and ran `php test.php`. The content was fetched perfectly fine.
I also changed the address to one from computerbase because those never worked inside FreshRSS but that content was also fetched without any issues.

According to the header, brotli was used just fine:

<details>
<summary>Header</summary>

~~~
$ php test.php 
HTTP/2 200 
content-type: text/html;charset=UTF-8
x-generated-by: tagesschau-live-7579697477-zfmfv
content-language: de-DE
x-content-type-options: nosniff
permissions-policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
x-varnish: 5080358
x-varnish-cache: miss cached
x-frame-options: sameorigin
content-encoding: br
content-length: 64676
cache-control: max-age=15
date: Thu, 16 May 2024 12:51:22 GMT
strict-transport-security: max-age=15768000 ; includeSubDomains ; preload

Content was here.
~~~

</details>

**Comment by Alkarex** [comment]
What about when you access `test.php` from your Web browser instead of the CLI?

**Comment by Alkarex** [comment]
See my proposition of work-around for https://github.com/FreshRSS/FreshRSS/discussions/6410#discussioncomment-9457788

**Comment by Lucki** [comment]
> What about when you access `test.php` from your Web browser instead of the CLI?

I get the content of the fetched website, somewhat broken, but the content is there. The header again says it fetched brotli.

<details>
<summary>Screenshot</summary>

![image](https://github.com/FreshRSS/FreshRSS/assets/1408843/70d108ce-09fe-4b77-93c2-90de596721dd)

</details>

**Comment by Alkarex** [comment]
Hummmm. Does https://github.com/FreshRSS/FreshRSS/discussions/6410#discussioncomment-9457788 work for you?
Otherwise it would be nice if you could find a way to reproduce the problem in the minimum example.

**Comment by Lucki** [comment]
> Does [#6410 (reply in thread)](https://github.com/FreshRSS/FreshRSS/discussions/6410#discussioncomment-9457788) work for you?

Yes, I fetched a few feeds manually and luckily they had new feed entries. The content was fetched.

> Otherwise it would be nice if you could find a way to reproduce the problem in the minimum example.

I'd like to, but it just works in the test example :shrug:

**Comment by Alkarex** [comment]
Strange. Might be good enough for now
