### ISSUE TITLE
[Bug] db-backup writes both to stdin and stderr

### ISSUE THREAD

**Issue by timendum** [FreshRSS/FreshRSS#6591]
### Describe the bug

I don't know if this is wanted or deliberate, but even if everything is done correctly, db-backup write something to standard output and other rows to standard error.

Are you interested in changing this?

### To Reproduce

1. Open a terminal
2. Runs /usr/bin/php ./cli/db-backup.php 2> /dev/null
3. Runs /usr/bin/php ./cli/db-backup.php 1> /dev/null
4. See the output

### Expected behavior

I'm expecting that also
```
Start SQL copy…
6841/6841
```

is written to standard output

### FreshRSS version

1.24.1

### Environment information

- Database version: Mysql 8.0
- PHP version: PHP 8.1
- Installation type: zip release
- Web server type: nginx
- Device: terminal
- OS: Ubuntu 22.04
- Browser: n/a

**Comment by Alkarex** [comment]
Progress information and other diagnostic information is by design supposed to go out to STDERR.
If you are interested in knowing whether the process has succeeded or not, you should test the exit code, not whether there is something on STDERR or not. Compare with e.g. a `curl` command.
See also https://github.com/FreshRSS/FreshRSS/issues/6582#issuecomment-2188197740

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6593
