### ISSUE TITLE
[Feature] Allow configuring purge policies at Feed/Category level

### ISSUE THREAD

**Issue by brpaz** [FreshRSS/FreshRSS#6601]
**Is your feature request related to a problem? Please describe.**
I would like to be able to configure different purge policies by feed or category.

For example, I have a "News" category,  that is a lot more "real time" and I don´t need to see news older than let´s say 1 week as they might be relevant anymore, but for example "Tech blogs" category,  it´s would be ok to see articles that have 1-month-old

**Describe the solution you’d like**

I would like a way to configure purge policies at the category level. (Feed level, would be a nice to have).

It would work exactly as the default purge policy. If a purge policy is active for the category, it will take precedence over the global one.

**Describe alternatives you’ve considered**
N/A

**Additional context**

**Comment by posita** [comment]
Should this be a bug report? I _**believe**_ categories have purge settings, but they're not honored in my setup. For example, I have a "noisy" category (akin to your "news" category). I set the purge limit to be articles older than some time limit, but when I look at those feeds read articles, I have many that are _**years**_ older than that limit would suggest. Are you seeing something similar?

![image](https://github.com/user-attachments/assets/ec5ba18a-84d4-4b6c-a906-4cc3b279fb83)

**Comment by Alkarex** [comment]
Purge options at category and feed levels (i.e. delete articles, which have been a long time in the database, or according to a maximum of articles to keep by feed) have been available since FreshRSS 1.15 https://github.com/FreshRSS/FreshRSS/pull/2335

A related option that exists at feed level but not yet at category level is a maximum number of articles to keep as unread in a given feed. That could be an example of feature request.

So most of what @brpaz was asking is already possible today. Let's close this issue and re-open questions and/or more precise feature requests as needed

Regarding @posita 's question, let's follow-up in https://github.com/FreshRSS/FreshRSS/issues/6863#issuecomment-2393835091

**Comment by brpaz** [comment]
@Alkarex ahh, I looked into it and couldn´t find the option. Now I checked again and found it!

![image](https://github.com/user-attachments/assets/605a8b03-675f-4b7a-b69c-6dfbf22db5bc)

IMO, it´s not very clear in the UI  that I need to unselect the `By default` option to allow me to configure the purge settings for the category. Maybe is that yellow warning, that triggered me to think, that if I unselect, it will not apply any policy.
