### ISSUE TITLE
How-to in English

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#671]
It seems the new reputation of FRSS brings a lot of English people. It could be great to have, at least, a little how-to in English to help users who don't speak French (see https://twitter.com/plurga/status/523326323876306944).

**Comment by yafp** [comment]
to be honest: 
it might even make sense to keep all issues/github input in english even if the devs are all located in france. Otherwise it might end up in duplicated issue reports (1 in french and 1 in english) and other multi-language effects. 

But i can for sure understand it aswell if you stick to french ;)
