### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mat-mo** [FreshRSS/FreshRSS#673]
Hello, thanks for this great application. Can you please add Right-to-left support? It used used for languages written from right to left such as Arabic, Hebrew, Parsi, and more.

**Comment by rezad1393** [comment]
any progress for this or do I need to open another bug report?

**Comment by Alkarex** [comment]
@rezad1393 I personally do not have experience with RTL, so help welcome. 
In particular, I am not sure how it is supposed to look like, how much the `dir` attribute can do, and what requires changes in the logic or themes

**Comment by Frenzie** [comment]
There's no point to opening another bug report, but adding some information could potentially be helpful. I don't know if @marienfressinaud still has his notes & branch around but I wouldn't mind seeing a link to an RTL newsfeed, for example.

I'm thinking the solution described above is too limited; isn't the language set using an attribute like this?

```xml
`xml:lang="ar"`
```

This language should simply be saved and transferred to the feed item. Then the browser will take care of displaying it correctly without us having to maintain any logic.

**Comment by mat-mo** [comment]
https://www.smashingmagazine.com/2017/11/right-to-left-mobile-design/ might be useful.

**Comment by Frenzie** [comment]
Sure, luckily that's 90 % a matter of sticking `dir=rtl` on the HTML element. Just some slightly off details as you can see.

<img src=https://user-images.githubusercontent.com/202757/68656865-e5323d00-0532-11ea-8d5d-08ac9adb4a3d.png width=30%>

Would you happen to know any examples of feeds? Because as [written above](https://github.com/FreshRSS/FreshRSS/issues/673#issuecomment-59640198):

> the important one, is to display the content correctly, so word don't show on the wrong side of the text. This is mostly a problem with mixed text in RTL and LTR text in the same sentence.

**Comment by mat-mo** [comment]
You can try with:
https://www.geektime.co.il/feed

**Comment by Frenzie** [comment]
And it's left bad, right good?

![Screenshot_2019-11-12_10-11-02](https://user-images.githubusercontent.com/202757/68657882-c339ba00-0534-11ea-8c9a-22a64fabf479.png)

**Comment by mat-mo** [comment]
> And it's left bad, right good?
> 
> ![Screenshot_2019-11-12_10-11-02](https://user-images.githubusercontent.com/202757/68657882-c339ba00-0534-11ea-8c9a-22a64fabf479.png)

Yes, exactly.

**Comment by rezad1393** [comment]
quiterss application has this feature that you can use RTL for each feed you specify.
I think this can be simply fixed by the same way in freshrss.
there are not a lot of feeds that have entries that are in rtl and ltr but in separate entries
like having one entry in rtl and then the next item in ltr. usually if the main language is in rtl then all the items are in rtl.

for example in parsi (persian) this is the mixed title that is shown ltr (wrong) 
"رشد ۶۴ درصدی درآمدهای فصلی Alibaba از خدمات ابری"

but copy pasting the same title and using right to left in libreoffice will show it correctly like this:
![Screenshot_20191112_133607](https://user-images.githubusercontent.com/7523164/68662100-68628b80-0551-11ea-9b37-256cffb0872e.png)

**Comment by Frenzie** [comment]
That's taken care of automatically by #2656, except more `auto`s need to be spread around for full effect. A forced override could be a nice later addition but that's nothing I have time for atm. Luckily it shouldn't normally be necessary.

The minor UI hiccups can be fairly easily solved. The ideal would be to use selectors like `#nav_entries:dir(rtl)`. To be compatible with more than just Firefox, adding a `class="rtl"` attribute to the root element would easily allow for selectors like `html.rtl #nav_entries` (or perhaps `[dir="rtl"] #nav_entries`).

The only thing I'm not fully sure of is how to add the dir=RTL & class=rtl to the HTML element. What do you suppose would be the best way to add it to the localization metadata, @Alkarex?

PS Some resources:
https://en.wikipedia.org/wiki/Bidirectional_text#Strong_characters
https://www.w3.org/International/articles/inline-bidi-markup/#dirauto

**Comment by Alkarex** [comment]
For the record, response in https://github.com/FreshRSS/FreshRSS/pull/2658#issuecomment-553011822

**Comment by rezad1393** [comment]
I think there is some confusion.
I dont actually need the internationalaztion of the program itself (as in translation and I18n  and so on) 
I am just trying to get rtl only for some feeds.
that should not  be related to the program interface language.

**Comment by Frenzie** [comment]
Like I said, #2656 already fixed that. There are purposefully two distinct PRs. One for telling specific elements to figure out their direction by themselves (#2656), another for fixing up the UI in RTL (#2658).
