### ISSUE TITLE
[Bug] [edge] RSS <title> elements with Unicode not translated to human-readable.

### ISSUE THREAD

**Issue by gnatbandanna** [FreshRSS/FreshRSS#6979]
### Describe the bug

I believe this to be an issue with Edge (1.24.x worked fine) **and** `Lemmy` RSS feeds (probably others).  Lemmy [feeds](https://lemmy.ml/feeds/c/privacy.xml?sort=Active) are coming across as:

```
<title>Polling the group: what do y&amp;#x27;all know about the Orion browser from Kagi?</title>
```

Which is then just displayed as is without translating to something more readable, such as `'`:

![image](https://github.com/user-attachments/assets/80280d2c-58db-43ab-93fd-0552e2f73c19)

I suppose that's fine, but this wasn't an issue with the 1.24.x branch. The titles were properly parsed and displayed.

### To Reproduce

Presumably add a feed like the one above and then look at the title with any client/browser to see the unicode jibberish.

### Expected behavior

I'd expect something like `[...] what do y'all know [...]` 

### FreshRSS version

1.25.0-dev

### Environment information

- Database version: sqlite
- PHP version: PHP 8.2
- Installation type: Docker (RPi)
- Web server type: Apache
- Device: iPhone SE2, Mac
- OS: Debian 12, Mint 22, iOS18x
- Browser: Safari iOS, LibreFox 132

**Comment by Alkarex** [comment]
Same as https://github.com/FreshRSS/FreshRSS/issues/754 , which was fixed by https://github.com/FreshRSS/FreshRSS/pull/813 and sent upstream as https://github.com/simplepie/simplepie/pull/400 but then reverted upstream as https://github.com/simplepie/simplepie/pull/433 , which made that we lost the fix during the big SimplePie refactoring https://github.com/FreshRSS/FreshRSS/pull/4374

However, the fix was probably not correct for all cases, so should be re-evaluated.
https://validator.w3.org/feed/docs/warning/ContainsHTML.html
https://www.rssboard.org/rss-profile#data-types-characterdata

In any case, the feed is not following the recommendations
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Flemmy.ml%2Ffeeds%2Fc%2Fprivacy.xml%3Fsort%3DActive

**Comment by Alkarex** [comment]
Looking at this specific feed and bug, the original source is:

```xml
<title>Polling the group: what do y&amp;#x27;all know about the Orion browser from Kagi?</title>
```

(This means a double XML encoding)

**Comment by Frenzie** [comment]
That definitely shouldn't be supported by default. ^_^

**Comment by Alkarex** [comment]
Indeed, I have been looking at what could / should be done, and I do not believe this invalid feed can be be supported without breaking legitimate use cases in other valid feeds.

Valid representations should be:

```xml
<title>Polling the group: what do y'all know about the Orion browser from Kagi?</title>

<title>Polling the group: what do y&#x27;all know about the Orion browser from Kagi?</title>
```

**Comment by Alkarex** [comment]
The bug should be reported to https://github.com/LemmyNet/lemmy/issues

**Comment by gnatbandanna** [comment]
> The bug should be reported to https://github.com/LemmyNet/lemmy/issues

Will do, thanks!! 

Edit: I put together a simple FreshRSS [extension](https://github.com/gnatbandanna/xExtension-RemoveLDE) to clean up the feeds a bit until Lemmy has an official [solution](https://github.com/LemmyNet/lemmy/issues/5171#issuecomment-2462289252). If this is driving anyone else crazy, here you go.

Note, I knew nothing about freshrss plugins up to this point, so there may be bugs or better ways of addressing this. _Caveat Emptor_!

**Comment by Frenzie** [comment]
It's fixed in Lemmy: https://github.com/LemmyNet/lemmy/commit/556358f53e386dcea738271ce2d9ad154603197b
