### ISSUE TITLE
[Bug] Cannot delete muted feeds

### ISSUE THREAD

**Issue by thompcha** [FreshRSS/FreshRSS#7026]
### Describe the bug

In Subscription Management, when "Delete muted feeds" is clicked, a message appears that says "Category cannot be updated" and muted feeds are not deleted.

### To Reproduce

1. Go to Subscription Management
2. Click the gear icon next to a category that contains at least one muted feed.
3. Click the red button that says "Delete muted feeds"
4. Click "OK" to confirm the browser dialog that appears that says "Are you sure you want to perform this action? It cannot be cancelled!"

### Expected behavior

Muted feeds removed

### FreshRSS version

1.24.3

### Environment information

- Database version: SQLite
- PHP version: 8.2.15
- Installation type: Manual
-Web server type: Apache
- Device: MacBook Pro
- OS: MacOS 14.5
- Browser: Chrome Version 131.0.6778.86 (Official Build) (arm64)

**Comment by math-GH** [comment]
Cannot confirm with 1.25.0-dev

**Comment by thompcha** [comment]
Here is an OPML file that contains the feeds I'm trying to remove:
[old_reader.opml.zip](https://github.com/user-attachments/files/17925664/old_reader.opml.zip)

**Comment by math-GH** [comment]
The OPML has about 400 feeds. It is not connected with the muted feeds.

Are there any log entries?

**Comment by thompcha** [comment]
All I see in the log is the 404 responses for the ones it couldn't connect to. There doesn't appear to be anything written to the log when it fails to remove them.

Does a channel have to succeed at connecting and then later fail and be muted in order to be removed using the "Delete muted feeds" feature?

**Comment by Alkarex** [comment]
@thompcha I am guessing this might be due to a misunderstanding.
*Muted feeds* are not the same than feeds with errors.

Here is an example of muted feed:
![image](https://github.com/user-attachments/assets/122d51ad-1cb8-430f-92f3-7337bb1e308b)

![image](https://github.com/user-attachments/assets/2af1c251-b774-4abd-b95b-2d265f78c5c3)

If there is no muted feed in the category, then clicking on the *Delete muted feed* button will lead to the symptoms you describe.

If that is not the correct diagnostic, send screenshots or a screen recording

**Comment by Alkarex** [comment]
I have added a new button for you: *Delete feeds in error*, in the settings of categories

See https://github.com/FreshRSS/FreshRSS/pull/7030
Tests welcome

**Comment by thompcha** [comment]
Oh, I see. Yes, I mistakenly assumed that feeds with errors were muted. Thank you!
