### ISSUE TITLE
[Feature] Support CSS selectors to retrieve full articles

### ISSUE THREAD

**Issue by Tywele** [FreshRSS/FreshRSS#7084]
**Is your feature request related to a problem? Please describe.**
Right now only CSS selectors in the form of `div[data-sanitized-class~="classname"]` work as CSS selectors even though I expect `.classname` to work as well.

**Additional context**
This seems to be a regression due to #7037 because it worked before fixing that. Additionally due to this change all CSS selectors I have set for my feeds don't work anymore due to the new syntax used.

**Comment by Alkarex** [comment]
Related https://github.com/FreshRSS/FreshRSS/pull/7083

**Comment by Alkarex** [comment]
We need to think a bit about how to do that.
Before, we used to do the sanitization after the CSS selection for content retrieval. This lead to a different syntax than for CSS exclusion of content from the feeds, was not compatible with what was visible inside FreshRSS, and gave unpredictable results on buggy HTML content.

After https://github.com/FreshRSS/FreshRSS/pull/7037 we have the same syntax for everything, but lost the ability to select with a short syntax like `.classname` because the content does not have `<div class="classname"` anymore after sanitization.

It does not seem doable to apply the CSS selector both before and after the sanitization. One option would be to automatically transform `.classname` selectors to `*[data-sanitized-class~="classname"]`. Thoughts and PR welcome

**Comment by Frenzie** [comment]
One thing that's for sure is that not being able to use `.classname` for content retrieval is very unintuitive because it doesn't correspond to the original page at all.

So for automatic transformation I'd say to do that with the other one, unless there's a reason not to.

**Comment by Alkarex** [comment]
> So for automatic transformation I'd say to do that with the other one, unless there's a reason not to.

Can you please reformulate? I am not sure to understand

**Comment by Frenzie** [comment]
1. You go to the website
2. You see an element has .classname

1, 2 ⇒ You expect to be able to use .classname, not to have to translate it into some weird custom syntax unique to FreshRSS

**Comment by Alkarex** [comment]
Sure, that is what this issue is about, but that does not help finding an implementation solution

**Comment by Frenzie** [comment]
I'm not sure what you mean? You proposed rewriting `.classname` to `*[data-sanitized-class~="classname"]`. That sounds like a good idea.

**Comment by Alkarex** [comment]
> 'm not sure what you mean? You proposed rewriting `.classname` to `*[data-sanitized-class~="classname"]`.

Yes, an automatic rewrite.

Alternatives include changing the workflow like: CSS retrieval > sanitize > CSS deletion

A drawback is that the CSS retrieval and CSS deletion would not have the same behaviour, which might be confusing

**Comment by Tywele** [comment]
I agree with @Frenzie your initially proposed solution seems like a good idea.

**Comment by Alkarex** [comment]
Please test https://github.com/FreshRSS/FreshRSS/pull/7091
