### ISSUE TITLE
Articles in chronological Order

### ISSUE THREAD

**Issue by Silviojjb** [FreshRSS/FreshRSS#742]
Hi, is it possible to show the articles in chronological order, no matter to what feed they are linked?
For instance, after updating 4 feeds, the mainstream shows all articles in chronological order by feed.

Many thanks.

**Comment by Alkarex** [comment]
Hello,
There has been several discussions on the topic (e.g. https://github.com/FreshRSS/FreshRSS/issues/344 in French), and here is a brief summary:
- Many feeds have date problems: missing, erroneous, a long time in the past, in the future, wrong time zone, etc. Therefore, the date provided by the feeds cannot be trusted, and using it would cause problems such as articles appearing in places not seen by the reader, or remaining at the top of the list all the time, etc.
- In order to have a working synchronisation between different FreshRSS sessions (including the cron job updating feeds in the background, and the API for mobile devices), we need to maintain some properties, among others that we should limit the cases when articles are inserted in the database at an older index/date than the newest one. Otherwise, articles may be marked as read even when they are not, and other similar problems. The best approach found was to use the time of insertion in the database as an ID/date for an article.
- An improvement on the current system is already planned in https://github.com/FreshRSS/FreshRSS/issues/530 which should solve your precise example.

Let me know if this answers your question, and if https://github.com/FreshRSS/FreshRSS/issues/530 is enough to close your issue.

**Comment by Silviojjb** [comment]
Thank you Alkarex,

Still, is it possible to make any change on the current version that allows me to achieve what I've requested, where can i edit the code that just fetch the results from Mysql in Chronological order.

Many Thanks.

**Comment by Alkarex** [comment]
You would have to replace `ORDER BY xxx.id` by `ORDER BY xxx.date` at a few places. I believe the following two should be enough, but not tested:
https://github.com/FreshRSS/FreshRSS/blob/beta/app/Models/EntryDAO.php#L499
https://github.com/FreshRSS/FreshRSS/blob/beta/app/Models/EntryDAO.php#L513

But doing so WILL generate some bugs during synchronisations, during paging, when _marking as read_ while a background refresh is taking place, when refreshing and displaying feeds with erroneous dates, etc.

**Comment by Alkarex** [comment]
The discussion continues in https://github.com/FreshRSS/FreshRSS/issues/530

**Comment by Alkarex** [comment]
An implementation of the more natural order is available. Tests much welcome https://github.com/FreshRSS/FreshRSS/pull/1470
