### ISSUE TITLE
"Mark as read" doesn't work in IE11

### ISSUE THREAD

**Issue by rnwgnr** [FreshRSS/FreshRSS#772]
Hi,

i recently switched to FreshRSS. I started with the official version 0.8.1 and updated later to github-version 0.9.4.
It looks like the "Mark as read"-button does not work when using Internet Explorer 11.
Everything is fine with Opera 26.

Has anyone come accross the same issue?

Kind regards.

**Comment by marienfressinaud** [comment]
Thanks for reporting.

I guess problem comes from "Mark as read" button was in fact a link before (i.e. `<a />` tag) and now it is a real button (for security reasons) but with `form` and `formaction` attributes which may be not supported by IE11.

Time to say that, I have checked on the [IE dev center](https://msdn.microsoft.com/en-us/library/ie/hh772932%28v=vs.85%29.aspx) which says `formAction` is supported since IE 10. My guess is IE doesn't support `formaction` without a capital `A` but in this case it is a bug from IE (html is case insensitive).

Sadly, I have no Internet Explorer under my keyboard to test myself :(

**Comment by rnwgnr** [comment]
Thanks for the fast reply.
I´ll try to prove your assumption this evening and report the result.

IE ist not my default browser, but unfortunately there is one environment where i can´t switch browser as i´d like to. ;)

**Comment by rnwgnr** [comment]
Hi,

using a capital A doesn´t do anything, still nothing happening with IE11.
I´ll ask a colleague tomorrow who should be more familiar with these things than i am.

Keep you updated.

Kind regards

**Comment by Alkarex** [comment]
No, the `formaction` works fine in IE. The problem seems to be with the [`form` attribute](http://www.w3.org/TR/html5/forms.html#attr-fae-form). Moving the `button` inside the form makes it work.
MSDN does not say anything about this attribute being writeable https://msdn.microsoft.com/en-us/library/ie/ms533768.aspx

**Comment by Alkarex** [comment]
FYI, I have just tested with a preview of Microsoft Edge (next version of IE) and it is the same.

**Comment by Alkarex** [comment]
Patched in https://github.com/FreshRSS/FreshRSS/pull/1188
