### ISSUE TITLE
Call for testing /dev before 1.1.1 beta

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#845]
Hello everybody,
Without further delay, it is now time to release a new beta of FreshRSS, [version 1.1.1](https://github.com/FreshRSS/FreshRSS/milestones/1.1.1), and [following the tradition](https://github.com/FreshRSS/FreshRSS/issues/725), I would like to invite you all to test the [current /dev branch](https://github.com/FreshRSS/FreshRSS/tree/dev), which will become the next beta.

We need to test in particular:
- [x] Fresh installation with MySQL
- [x] Update from the previous beta, using MySQL
- [x] Fresh installation with SQLite
- [x] Update from the previous beta, using SQLite

So when some of you report whether _it works_ or not, please remember to state in which case you are (fresh or update, MySQL or SQLite).

The list of issues included in this beta is listed in the [milestone 1.1.1](https://github.com/FreshRSS/FreshRSS/issues?q=milestone%3A1.1.1). The [main changes](https://github.com/FreshRSS/FreshRSS/blob/a19e908b73b3fe011bc40609d1edb7f7da6030c8/CHANGELOG) include:
- [New option to detect and mark updated articles as unread](https://github.com/FreshRSS/FreshRSS/issues/798).
  - Be aware of that if you start seeing [articles that are _reappearing_](https://github.com/FreshRSS/FreshRSS/issues/493#issuecomment-102491457) (should be off be default, though).
- [Support for internationalized domain name](https://github.com/FreshRSS/FreshRSS/issues/819) ([IDN](https://en.wikipedia.org/wiki/Internationalized_domain_name)).
- [Improved logic for automatic deletion of old articles](https://github.com/FreshRSS/FreshRSS/issues/493).
- [Attempt to better handle encoded titles](https://github.com/FreshRSS/FreshRSS/issues/754).
- A [new option to turn on/off the logging of SimplePie requests in the syslog](https://github.com/FreshRSS/FreshRSS/issues/711)
- Updated languages (French, English, German), including a new [Czech translation](https://github.com/FreshRSS/FreshRSS/issues/814) by @Tets42.
- Several other smaller improvements

When this version [beta 1.1.1](https://github.com/FreshRSS/FreshRSS/milestones/1.1.1) is released (~30 May), the focus will then be on [beta 1.1.2](https://github.com/FreshRSS/FreshRSS/milestones/1.1.2) and the exiting [new PubSubHubbub instant notification system](https://github.com/FreshRSS/FreshRSS/issues/312) (~30 June).

Thanks to the contributors, and thanks in advance for testing!
@marienfressinaud, @Alkarex, @aledeg, et al.

**Comment by Alwaysin** [comment]
1) I'm testing an installation and was wondering what is the purpose of having two buttons at the first step.
For the language selection we can "validate" or "go to next step". Not sure about English phrasing as I was in French by default but it raises two more suggestions/questions : 2) it could be nice to automatically change the strings to the language selected so that no one will be lost if they do not speak French and 3) isn't it possible to auto-detect the browser language to automatically pre-select the right one?

4) Not sure about "Installation · FreshRSS" field. I think it is the name which will then be used in the title but it could be more descriptive.

5) "Adresse courriel de connexion (pour Mozilla Persona)" : it could be great if only appearing if Mozilla Persona is selected for the authentication!

6) Little suggestion (which may be dumb but I'm just sharing the ideas going through my mind when installing ^^): why not maybe add a feed by default? Marien spoke about a specific feed for FreshRSS news that he wants to create, if I recall correctly.

And finally, I've tested SQLite for the first time and it apparently works very fine!

EDIT: I would release PubSubHubbub feature for 1.2 - it is a killer feature which needs at least the second number to increase :D - even if we don't really care about version numbers ^^)

**Comment by Alkarex** [comment]
Thanks for the feedback, and here is a quick response already, @Alwaysin :
1) I will look at it
2) and 3) The system should already pick the language defined in the browser, if this language exists in FreshRSS, otherwise fall back to English. If this is not the case, then there is a bug.
4) We could maybe remove the _title_ field during the installation since it is not really important
6) Good idea
7) Let see with @marienfressinaud when he is back for the numbering of the following beta :-)

**Comment by Alwaysin** [comment]
My system is in English, and so is my browser. However, French is pre-selected. Is the detection based on the IP address?

Another suggestion is to give indications as to how resolve a problem if there is one. For example if the rights are bad, "use chown ..." but I know it could get tricky since commands are not the same depending on the system.

**Comment by Alwaysin** [comment]
On step 2 of configuration, the field "Authentication method" is very frustrating when navigating with the keyboard. It automatically teleport you to the next field when trying to select the authentication you want.

**Comment by Alkarex** [comment]
@Alwaysin Could you please open issues so that these things get fixed in the following beta? I would like to avoid making too many changes just before this beta release.

**Comment by Alwaysin** [comment]
Yup, no problem!

EDIT : I think it's ok, I hope I haven't opened too many.

I didn't open one for the 1) ("validate" and "go to next step") because I didn't understand but there's probably a reason - had you time to check?

**Comment by Alkarex** [comment]
You are all very welcome to test the /beta branch (default branch), in which I have just merged /dev. If all goes well, I will make a tag/release (1.1.1-beta) tomorrow evening.

**Comment by Alkarex** [comment]
Since I have just made a couple of changes in /beta, I will wait one day more before doing the release/tag 1.1.1. Any feedback from test welcome :-)

**Comment by Jucgshu** [comment]
I'm testing dev branch with sqlite and all seems ok to me, but one small detail : the Sticky Feeds extension looks broken. I tried to activate/ de-activate with no success.

I didn't test the other extensions though.

**Comment by Alkarex** [comment]
Thanks @Jucgshu for testing :-) Could you please open a new issue for the problem you have spotted?

**Comment by Alkarex** [comment]
FreshRSS 1.1.1 beta is released https://github.com/FreshRSS/FreshRSS/releases/tag/1.1.1

**Comment by Jucgshu** [comment]
@Alkarex : done in #862

Thanx very much for your work :-)

**Comment by marienfressinaud** [comment]
Auto-update is coming tonight! Sorry for the delay ;).

Edit: it is available and should work!
