### ISSUE TITLE
Language selection when installing

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#856]
As stated here : https://github.com/FreshRSS/FreshRSS/issues/845#issuecomment-104945293

> My system is in English, and so is my browser. However, French is pre-selected. Is the detection based on the IP address (which indeed is French)?

During fresh installation.

**Comment by aledeg** [comment]
If I look at the code, the language selection search:
- the selected language
- the server language
- English

I guess your server accept French that's why you have French selected. There is no IP detection to select the language at this point.

I don't know what would be best here.
I think we could remove the server language step and default to English since it is more widespread than other languages.

**Comment by aledeg** [comment]
@Alwaysin could you confirm your server configuration?

**Comment by Alkarex** [comment]
See also my comment https://github.com/FreshRSS/FreshRSS/issues/857#issuecomment-109580995

**Comment by Alwaysin** [comment]
My server uses en_GB.UTF-8 but indeed as pointed by Alkwarex in the other thread, my Accept-Language header states FR and then EN.

Sorry for the false issue!
