### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#861]
Hello together

How can i upgrade Freshrss? I fount nothing in the documentation. Just overriding the files do not work. :-)

regards
Thomas

**Comment by Alkarex** [comment]
Hello Thomas,
It depends a bit on how you installed FreshRSS, and also from which to which version you are upgrading. (Please note that I am right now in the process of releasing a new beta version, so today/tomorrow is a bit special).

1) There is a built-in upgrade system in the Web interface of FreshRSS. (But I was not the one developing this mechanism and I have never used it, so I am not sure of the details)

2) If you are familiar with git, it is also convenient. But you may have to keep a eye on the release notes if there are some things to do manually. If your current version is >= 1.0, then it should be fine.

Install:

``` bash
git clone https://github.com/FreshRSS/FreshRSS.git
```

Update:

``` bash
cd ./FreshRSS/
git reset --hard
git pull
```

3) Otherwise, override your files with the files of the new version, and do not delete your existing `./data/` directory. So "just overriding the files" should work in most cases. What is your problem, more precisely ?

**Comment by Alkarex** [comment]
To be revised as part of https://github.com/FreshRSS/FreshRSS/issues/861

**Comment by Alkarex** [comment]
Some more examples of managing FreshRSS updates with git are included in https://github.com/FreshRSS/FreshRSS/tree/dev/cli#using-git

**Comment by kevinpapst** [comment]
Your linked article should go somewhere else, e.g. the official documentation. I updated my installation with the web installer and that crashed my FreshRSS installation. I guess because some file permissions where wrong and the installer did only half of the work (a check upfront  would be a good idea to be included in the updater).
I tried about an hour until I found this URL and the info which files I had to restore and that I had to delete the "force installation" file. 
Would you consider to move that docu to the GitHub pages documentation? I would sit down and write it/copy & paste it if you are willing to include it via PR. What do you think @Alkarex ?
