### ISSUE TITLE
Install: load existing config.default.php and config.php

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#890]
https://github.com/FreshRSS/FreshRSS/pull/869#issuecomment-109581185

**Comment by Alkarex** [comment]
Also needed for
https://github.com/FreshRSS/FreshRSS/issues/680
https://github.com/FreshRSS/FreshRSS/issues/892
https://github.com/FreshRSS/FreshRSS/issues/865
https://github.com/FreshRSS/FreshRSS/issues/897

**Comment by marienfressinaud** [comment]
I don't really understand why we need to load existing config: install.php is used only the first time we install FRSS, ~~so when there is no user yet~~ (sorry, we talk about general configuration :)).

**Edit**: well, I see benefit for SSL option for DB but not for the other tickets...

**Edit 2**: in fact, no, I don't see any interest. Install process is aimed to create `config.php`... and we don't need to load default values since we only want to overwrite them.

**Comment by Alkarex** [comment]
I see, we need to clarify the desired behaviour:
1) Even during the first install, I think it is cleaner to load `config.default.php` instead of having the values hard-coded in `install.php` https://github.com/FreshRSS/FreshRSS/blob/4032bf5d8501768647eac67b4692662defd50e46/app/install.php#L171
2) I thought `install.php` was supposed to be called at every update, except in the case of automatic update;
3) At least in the past, there has been some update recommendations in the lines of a) keep the `data`directory, b) deploy the new code (which also contains some files in `data`. This is also what I [suggest for git update](https://github.com/FreshRSS/FreshRSS/blob/c31a6bf5ef7babe1fd5440e406e5bda372aa0f08/README.md#example-of-full-installation-on-linux-debianubuntu), with a `git reset --hard && git pull` which will also re-create the `data/install.txt`;
4) Since there is therefore ( a risk | an expectation ) that `install.php` is called after an update, if we do not want `install.php` to re-create `config.php`, it should maybe jump over some steps when `config.php` already exists;

Do we want `install.php` to be called after an update not done by an automatic update?

**Comment by marienfressinaud** [comment]
1. Ok but the line you commented is not the most appropriate because we can just remove these two hard-coded variables (environment and simplepie_syslog_enabled). But it makes sense in the view, true.
2. Not since I introduced the automatic update. The goal was to simplify this script which was very hard to maintain and not the best place to handle updating process.
3. I always recommend automatic update for users and Git for developers. Now I see this part in the README (but it should be in the documentation instead!) and I realize that Git update should be fully-supported too. To avoid code duplication, we should write update scripts into a specific directory (e.g. `./app/updates`). These scripts would be called after an automatic update or a Git update and it should be transparent for the user (unless an information should be given by him). But for now, `install.php` script doesn't handle any update process and it should not.
4. Maybe just showing a sort of warning to inform FreshRSS has already been installed and to ask if he's sure to continue?

**Comment by Alkarex** [comment]
1. Ok for removing the two lines (`environment` and `simplepie_syslog_enabled`)
2. Ok
3. Yes indeed, I think update code should be shipped with new versions. I think fundamental things such as install/update should be in the documentation _too_ while keeping some mainstream info in the readme anyway https://github.com/FreshRSS/FreshRSS/issues/822 (we should add links to the documentation from the different readme sections)
4. Ok, I suggest jumping directly from the step verifying the system requirements to a step verifying that the database connexion work. For the time being, I suggest making a long jump to one of the latest steps, together with a warning.

**Comment by marienfressinaud** [comment]
I'm ok to put mainstream info in the README of course and I wanted to put links to the documentation website indeed :).

I suggest to open new tickets for 3 and 4.

**Comment by Alkarex** [comment]
Ok, I have added the tickets https://github.com/FreshRSS/FreshRSS/issues/907 https://github.com/FreshRSS/FreshRSS/issues/908 https://github.com/FreshRSS/FreshRSS/issues/909

**Comment by Alkarex** [comment]
We can keep this ticket open until your pull request for https://github.com/FreshRSS/FreshRSS/compare/dev...marienfressinaud:890-load-existing-config
