### ISSUE TITLE
dirname() has an unexpected behaviour in Minz_Request::getBaseUrl()

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#906]
In `Minz_Request::getBaseUrl()`, `dirname()` function is called to remove the last part of `$_SERVER['REQUEST_URI']` (see https://github.com/FreshRSS/FreshRSS/blob/beta/lib/Minz/Request.php#L103).

But we can face two cases:
- /p/i/ (i.e. most of the time) which is transformed into /p/
- /p/i/index.php (e.g. during installation) which is transformed into /p/i/

Expected result: always have the same result (i.e. /p/i/) for both cases.

Note: if we keep /p/i/, we should change `Minz_Url::display()` which calls `Minz_Request::getBaseUrl(PUBLIC_TO_INDEX_PATH)`.

Needed for #865

**Comment by Alkarex** [comment]
Ok, I will have a look.

**Comment by Alkarex** [comment]
Not tested yet, but should already be more consistent with https://github.com/Alkarex/FreshRSS/commit/2d22bf300a8dabcc77237f4bb56bf6532486fca2
It does not return the trailing slash, so it would be `/p/i` in both cases, so we can keep the convention we have in `constants.php` in which path constants start with a slash.
The value parameter `PUBLIC_TO_INDEX_PATH` is only used when the ~~using~~ retrieving the base URL from the `config.php`.

**Comment by marienfressinaud** [comment]
>  The value parameter PUBLIC_TO_INDEX_PATH is only used when the using retrieving the base URL from the config.php.

Do you mean `getBaseUrl()` will return:
- `http://example.com/p/i` if `base_url` is not present in `config.php`
- `http://example.com/p` if it is (and so we should call `getBaseUrl(PUBLIC_TO_INDEX_PATH)` to have the previous behaviour)

I think it's a bit confusing. It would be more consistent to always return `http://example.com/p` in both cases (I didn't think about it when writing my first message) and to always add the `$baseUrlSuffix` if given.

**Comment by Alkarex** [comment]
If `base_url` is present in config.php, then this is the value that is returned, together with the suffix `PUBLIC_TO_INDEX_PATH`.
If `base_url` is empty in config.php, then the base url is calculated (and the value `PUBLIC_TO_INDEX_PATH` is not used because we directly get the `/p/i` path)

In both cases, we should have identical results when calling FreshRSS from a Web browser.

**Comment by marienfressinaud** [comment]
Yes but if we call `getBaseUrl()` without `PUBLIC_TO_INDEX_PATH`, the results will be different. That's my problem.

By the way, we need `base_url` without `/i` for the PubSubHubbub feature.

**Comment by Alkarex** [comment]
Yes, `getBaseUrl` has an optional suffix given in parameter, which is only added when constructing the address from `base_url` given in `config.php`. I did it like that to avoid putting too much info in Minz.
I agree that this is not a very nice behaviour.

PubSubHubbub needs `base_url` directly from `config.php` (without `/i` indeed, because it will call something underneath `/api/`).

Example of possibilities:
1. We can chose to always return exactly the value from `config.php`;
2. We can move the logic "add the suffix only when coming from `config.php`" to the caller (I do not like it);
3. We can split the function into two: one that returns the public URL (without `/i`), another one that returns the index URL (with `/i).

**Comment by marienfressinaud** [comment]
The current function is quite good, what I meant was just to remove `/i` from `$_SERVER['REQUEST_URI']` and store the result in `config.php` during the installation so:
- `getBaseUrl()` returns `/p` if `base_url` doesn't exist (guessed from `$_SERVER['REQUEST_URI']`)
- `getBaseUrl()` returns `/p` if `base_url` exists
- `getBaseUrl(PUBLIC_TO_INDEX_PATH)` returns `/p/i` if `base_url` doesn't exist (guessed from `$_SERVER['REQUEST_URI']`)
- `getBaseUrl(PUBLIC_TO_INDEX_PATH)` returns `/p/i` if `base_url` exists

But now I wrote this, I just realised why you don't like this solution: `/i` is FreshRSS-dependant! What about this solution:
- A `guessBaseUrl()` method which returns info from `$_SERVER['REQUEST_URI']` only. It would be useful during installation and before saving this information, we should remove the `/i` part.
- A `getBaseUrl($baseUrlSuffix = '')` method which returns `base_url` from configuration only.

**Comment by Alkarex** [comment]
Yes, sorry, I should have been more explicit regarding the Minz/FreshRSS division of work :-)
And yes, I think your proposition is fine. For the `guessBaseUrl()`, Minz could return the full path including `/i` (but excluding additional files or queries such as `./i/index.php?xxx`), and then FreshRSS can perform a `dirname()` to strip it.

**Comment by marienfressinaud** [comment]
Exactly what I thought! :)

**Comment by marienfressinaud** [comment]
Do you want to continue on this ticket or should I write the patch? I would like to continue on #865 but I  need this patch first.

**Comment by Alkarex** [comment]
You are welcome to proceed, because I will not have much time for the next ~2 days.
