### ISSUE TITLE
Czech and German translations for 1.1.2-beta

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#930]
Hi @Tets42, @thomasE1993 and @ealdraed,

we still have some strings untranslated in FreshRSS and we plan a new release tomorrow and it could be nice to have a fully-translated version. You can give the translations in comments.

Here is what we need.

**Czech**:

```
'There is %d account created yet',
'There are %d accounts created yet',
'Allow account creation',
'0 means that there is no account limit',
'Max number of accounts',
'Account deletion',
'Your account and all the related data will be deleted.',
'The maximum amount of accounts has been updated.',
'New account',
'Create an account?',
'Account creation',
'Keep previous installation',
'Reinstall FreshRSS',
'We have detected that FreshRSS is already installed!',
'You will lose your previous configuration by reinstalling FreshRSS. Are you sure you want to continue?',
```

**German**:

```
'There is %d account created yet',
'There are %d accounts created yet',
'Allow account creation',
'0 means that there is no account limit',
'Max number of accounts',
'Account deletion',
'Your account and all the related data will be deleted.',
'The maximum amount of accounts has been updated.',
'New account',
'Create an account?',
'Account creation',
```

Thanks for your help!

By the way, I plan to open this kind of ticket each time we plan to release a new version. Is it fine for you or you would prefer another process? Note we may have to change in the future if we have more languages to support.

**Comment by ghost** [comment]
Hello together

German:

'There is %d account created yet',
Es wurde bis jetzt noch keinen Account erstellt.

 'There are %d accounts created yet', 
Es wurden bis jetzt x Accounts erstellt

'Allow account creation', 
Erlaube die Accounterstellung

'0 means that there is no account limit',
0 meint, dass es kein Account Limit gibt

 'Max number of accounts', 
Maximale Anzahl von Accounts

'Account deletion', 
Accountlöschung

'Your account and all the related data will be deleted.', 
Dein Account und alle damit bezogenen Daten werden gelöscht.

'The maximum amount of accounts has been updated.', 
Die maximale Anzahl von Accounts wurde aktualisiert.

'New account', 
Neuer Account

'Create an account?', 
Erstelle einen Account?

'Account creation',
Accounterstellung

Instead of Account --> "Konto" is also possible

What means the %d? Maybe the sentence has to be corrected. 

Please check for errors, I am on holiday and on my smartphone :-)

**Comment by marienfressinaud** [comment]
Thank you!

%d is replaced by a number dynamically.

Have nice holiday!

**Comment by ghost** [comment]
Then you have to change things a little:

'There is %d account created yet',
Es wurde bis jetzt 1 Account erstellt.
Es wurden bis jetzt 0 Accounts erstellt.

**Comment by ghost** [comment]
Hi, it's not too late, is it? Here it is:

**Comment by ghost** [comment]
Ufff, sorry. Accidently pressed "CTRL+Enter", not just "Enter" :-(

'There is %d account created yet',
'Zatím je vytvořen %d účet',
'There are %d accounts created yet',
'Zatím je vytvořeno %d účtů',
'Allow account creation',
'Povolit vytváření účtů',
'0 means that there is no account limit',
'0 znamená žádná omezení účtu',
'Max number of accounts',
'Maximální počet účtů',
'Account deletion',
'Smazání účtu',
'Your account and all the related data will be deleted.',
'Váš účet bude smazán spolu se všemi souvisejícími daty',
'The maximum amount of accounts has been updated.',
'Maximální počet účtů byl změněn',
'New account',
'Nový účet',
'Create an account?',
'Vytvořit účet?',
'Account creation',
'Vytvoření účtu',
'Keep previous installation',
'Zachovat předchozí instalaci',
'Reinstall FreshRSS',
'Reinstalovat FreshRSS',
'We have detected that FreshRSS is already installed!',
'Zjistili jsme, že FreshRSS je již nainstalován!',
'You will lose your previous configuration by reinstalling FreshRSS. Are you sure you want to continue?'
'Reinstalací FreshRSS ztratíte předchozí konfiguraci. Opravdu chcete pokračovat?',

I'm not sure the that the first phrase with "%d" will work correctly :-(

**Comment by marienfressinaud** [comment]
Thank you for your reply too! :) It's not too late, no. I will add the strings tonight when I will have few time and I hope to release the new version tomorrow during the afternoon.

**Comment by marienfressinaud** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/933
