### ISSUE TITLE
Smileys from Wordpress are too big

### ISSUE THREAD

**Issue by NerosTie** [FreshRSS/FreshRSS#996]
This is a normal smiley: 

![tmp2](https://cloud.githubusercontent.com/assets/4572452/10459542/4c34fb6e-71d0-11e5-8614-8584ab7cf1aa.png)

This is a smiley, from the same article, in freshrss:

![tmp3](https://cloud.githubusercontent.com/assets/4572452/10459565/6b05909e-71d0-11e5-9cec-226657c3f1da.png)

(if you want to try: http://grisebouille.net/ailleurs-cest-pire/ )

**Comment by Alkarex** [comment]
Hum, it will not be easy to solve globally.
The original image is the large one, which is reduced by styling. And we (SimplePie) are removing the styling.

``` html
<img style="height: 1em; max-height: 1em;" class="wp-smiley" alt=":)" src="http://grisebouille.net/wp-includes/images/smilies/simple-smile.png">
```

A quick fix would be to add a custom CSS (see the FreshRSS extension for that) with

``` css
.wp-smiley { height: 1em; max-height: 1em; }
```

**Comment by marienfressinaud** [comment]
`class` seems to be removed as well so custom CSS would not work...

**Comment by NerosTie** [comment]
Yes, it doesn't work with a custom css (I tried)

**Comment by Alkarex** [comment]
Damn, you are right.
This should work, but is even less universal...:

``` css
img[alt=':)'] { height: 1em; max-height: 1em; }
```

**Comment by NerosTie** [comment]
Yes, it works, but it's not really a good solution (but better than no solution at all!)

**Comment by Wanabo** [comment]
Not tested, but try this for universal:

```
img[src*="/wp-includes/images/smilies/"] { max-height: 25px; }
```

https://css-tricks.com/attribute-selectors/

**Comment by NerosTie** [comment]
@Wanabo it doesn't work (I don't know why...)

**Comment by Wanabo** [comment]
You could try:

```
img[src*="/smilies/"] { max-height: 25px; }
```

Can you provide a link to an article on your fressrss website where those big smileys occur?

**Comment by NerosTie** [comment]
@Wanabo It doesn't work either.

You can test with this blog: http://metropolife.net/  
Look at this post, she uses 3 different emojis: http://metropolife.net/what-i-have-learned-about-denmark/

**Comment by Wanabo** [comment]
Sorry need a link to an article on your fressrss website where those big smileys occur. Only then I can fiddle with firebug to see what css will work.

**Comment by NerosTie** [comment]
Sorry but my freshrss is not public. To test, just add the website from above (or any wordpress site which use emojis) in your freshrss.

**Comment by JD557** [comment]
`img[src*="/wp-includes/images/smilies/"] { max-height: 25px; }` seems to work when injected on chrome's web inspector.

Maybe the problem is related to the custom CSS extension?

**Comment by marienfressinaud** [comment]
Problem comes from extension: quotes are html-encoded

**Comment by NerosTie** [comment]
Maybe we can resolve this issue by replacing all emojis with those from emojione https://github.com/Ranks/emojione
I use them on my blog and I think it could be a good solution for Freshrss.

**Comment by Alkarex** [comment]
@NerosTie Thanks for the proposition, but it is not FreshRSS that is using smileys: they come from various feeds as images.
Edit: Ah, you knew that of course, sorry. In any case, the problem is not the replacement, but matching / finding / filtering them.

**Comment by NerosTie** [comment]
@Alkarex Yes I know, but these websites using emojis are an issue in Freshrss. Emojione could be used as a new plugin or integrated with "custom CSS" as an unique rule for every emojis coming from any RSS feed.

**Comment by Frenzie** [comment]
This issue (or at least the one that kept custom CSS from working properly) was fixed last year by https://github.com/FreshRSS/Extensions/pull/4.

**Comment by NerosTie** [comment]
@Frenzie Are you sure? I still have big smileys froms wordpress in my Freshrss.

**Comment by Frenzie** [comment]
@NerosTie I mean that a line of CSS such as above in https://github.com/FreshRSS/FreshRSS/issues/996#issuecomment-160419106 will now work correctly rather than being mangled by the CustomCSS extension. Note that you'll have to update the CustomCSS extension manually. Alternatively you could edit the CSS file without using the web GUI, but then it'd get mangled if you ever forgot about that issue.

Personally I would use something like this:

```css
img[src*="/smilies/"], img[src*="%2Fsmilies%2F"] {max-height:1.25rem; vertical-align:middle}
```

The `%2Fsmilies%2F` matches the encoded URL as used by ImageProxy.

As for a global solution, perhaps we could keep classes from the original feed in a prefixed form. In other words, transform `wp-smiley` into something like `freshrss-safe-prefix--wp-smiley`. A style addressing that prefixed class could perhaps even be part of the default setup. WordPress is quite popular, after all.

NB The proposed prefixed solution isn't about `wp-smiley`, which is innocent enough by itself. It's mainly about other classes that might unintentially clash with FreshRSS itself, such as `icon`, `favicon`, `item`, `date`, `title`, etc.

**Comment by aledeg** [comment]
The size of those icons were bothering me as well. I used the [CustomCSS extension](https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS) with the following rule:
```css
img[src^="https://s.w.org/images/core/emoji"] {height: 1rem;width: 1rem;vertical-align:middle;}
```

I  think there is no need for a dedicated extension to address that issue. I suggest we close it and we add a set of rules in the extension documentation.

Ping @NerosTie, @Alkarex, @marienfressinaud, @Frenzie

**Comment by Frenzie** [comment]
I doubt anyone's of the opinion that there should be such a thing as a Wordpress CSS extension. (I'd oppose it.) However, due to the ubiquity of Wordpress it might be worth asking whether a rule like this should be part of the default stylesheet.

Regardless of the above, the undesirable way in which SimpePie completely filters classes like `wp-smiley` doesn't make things any easier. Case in point, `wp-smiley` will work on pretty much any WP version ever and that smiley CDN is pretty recent. (Also, classes are faster but I suppose that shouldn't really matter much for this one.)

**Comment by NerosTie** [comment]
Emojis are integrated in every web browsers now and wordpress use native emojis: 

https://en.support.wordpress.com/emoji/

I think this issue is obsolete.

**Comment by Alkarex** [comment]
Great, and thanks for the feedback @NerosTie 👍
